= Карточка "Дополнительное соглашение"

Карточка xref:dm-cards/add-aggreement-register-tab.adoc["Дополнительное соглашение"] предназначена для хранения сведений о документе, который прилагается к заключенному ранее договору какой-либо сделки. Предполагается, что согласно данному соглашению стороны фиксируют возможные изменения, которые состоялись после заключения договора.

.Карточка состоит из следующих элементов:
* xref:dm-cards/add-aggreement-ribbon.adoc[Лента].
* Поле _Связанный договор_ в котором отображается ссылка на связанную карточку договора.
* Набор вкладок:
** xref:dm-cards/add-aggreement-register-tab.adoc[Регистрация].
** xref:dm-cards/contract/files-tab.adoc[Файлы].
** xref:dm-cards/contract/links-tab.adoc[Связи].
** xref:dm-cards/contract/catgories-tab.adoc[Категории].
** xref:dm-cards/contract/tasks-tab.adoc[Задания].
** xref:dm-cards/contract/comments-tab.adoc[Комментарии].
** xref:dm-cards/contract/history-tab.adoc[История].
+
[NOTE]
====
Поля всех вкладок карточки _Доп. Соглашения_, кроме вкладки _Регистрация_, полностью аналогичны вкладкам карточки _Договор_.
====
+
* Строка состояния.
