= Аннотация

Приложение "{dm}" добавляет в систему {dv} 5.5 (далее -- {dv}) типовую реализацию электронного документооборота организации и функции для работы с договорами.

Приложение предполагается применять в организациях, использующих систему {dv}.

== Назначение документа

Настоящий документ является руководством администратора приложения "{dv} 5. {dm}" (далее -- "Приложение").

Документ содержит инструкцию по установке и первоначальной настройке Приложения (серверной и клиентской частей); перечислены функции администратора.

Документ предназначен для администраторов и инженеров системы {dv}.

Настоящий документ является руководством пользователя приложения "{dv} 5. {dm}" (далее -- "Приложение").

Документ содержит описание видов карточек Приложения, приведена инструкция по работе с документами и заданиями в {wincl}е.

[NOTE]
====
Инструкция по работе с согласованиями приведена в документе _Модуль "{dv} 5. {ad}". Руководство пользователя_.
====

Документ предназначен для пользователей системы {dv}.

"{dv} 5. {dm}" является _базовым модулем_ системы "{dv} 5.5", содержащим готовое к использованию прикладное _решение_ по работе с обычными и договорными документами. Предоставляемое Приложением _решение_ ориентировано на массовое использование -- повседневную работу сотрудников и их взаимодействие в составе рабочих групп.

Приложение является удобным средством для эффективной и упорядоченной работы с документами на любом предприятии, где нет сложной системы делопроизводства, либо планируется начать автоматизацию документооборота с простых процессов.

В приложении "{dm}" реализованы в упрощенном виде основные элементы классического делопроизводства:

* регистрация, хранение и поиск электронных документов;
* классификация документов;
* согласование и подписание документов;
* согласование проектов договоров, в том числе с контрагентом;
* ознакомление;
* фиксация хода исполнения договоров, в том числе:
** прикрепление рабочих материалов (файлов и карточек);
** прикрепление результатов (консолидированной версии договорного документа, актов, дополнительных соглашений, других дополнительных документов);
* работа с заданиями.

== Уровень подготовки пользователя

Для эксплуатации приложения "{dm}" определены две пользовательские роли: администратор {dv} и конечный пользователь. Настройку _решения_ на базе системы {dv} с использованием Приложения выполняет инженер {dv}.

Администратор {dv} устанавливает Приложение (серверную и клиентскую части), выполняет первоначальную настройку, выявляет неполадки в работе бизнес-процессов Приложения в процессе эксплуатации.

Инженер {dv} настраивает работу с карточками Приложение с помощью предоставляемых _конструкторов_ и _справочников_ {dv}, разрабатывает скрипты карточек, настраивает бизнес-процессы.

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой, согласованием и т.п.

Администратор или конечный пользователь {dv} заполняют и актуализируют справочники {dv}.

Все пользователи Приложение должны обладать базовыми навыками работы на персональном компьютере, в программе "{wincl}" (модуль "{dv} 5. {wincl}").

Администратор {dv} должен обладать навыками настройки модуля "{dv} 5. {pl}"; а также ознакомиться с документом _Приложение "{dv} 5. {dm}". Руководство администратора_.

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}, иметь опыт разработки на языке C# или Visual Basic .NET; должен ознакомиться с данным руководством пользователя, с документами _Приложение "{dv} 5. {dm}". Руководство администратора_# и _Docsvision 5.5. Руководство программиста_.

Конечные пользователи должны ознакомиться с данным руководством пользователя.

[#arrangement]
== Как организована документация модуля

.Документация модуля содержит следующие разделы:
. xref:admin:General_information.adoc[Общие сведения] (приведены общие сведения о Приложении, требования Приложения к программному и аппаратному обеспечению компьютера).
. xref:admin:Structureof_program.adoc[Структура Приложения] (перечислены составные части Приложения).
. xref:admin:Install_and_configuration.adoc[Установка и настройка] (содержит инструкцию по установке Приложения).
. xref:admin:UpdateVersion.adoc[Установка новой версии приложения] (содержит инструкцию по установке новой версии Приложения).
. xref:admin:Administrator_functions.adoc[Функции администратора] (содержит описание настроек Приложения, выполняемых администратором {dv}).
. xref:user:Introduction.adoc[Введение] (приведены общие сведения о Приложении, требования к подготовке пользователей).
. xref:user:Preparationfor_work.adoc[Подготовка к работе] (приведены условия для работы с карточками Приложения в программе {wincl}/РМА).
. xref:user:Operations.adoc[Описание операций] (приведено описание операций с карточками _Документ УД_, _Задание УД_, _Группа заданий УД_).

[#capabilities]
== Назначение и функции Приложения

"{dv} 5. {dm}" является _базовым модулем_ системы "{dv} 5.5", содержащим готовое к использованию прикладное _решение_ по работе с обычными и договорными документами. Предоставляемое Приложением _решение_ ориентировано на массовое использование -- повседневную работу сотрудников и их взаимодействие в составе рабочих групп.

Приложение является удобным средством для эффективной и упорядоченной работы с документами на любом предприятии, где нет сложной системы делопроизводства, либо планируется начать автоматизацию документооборота с простых процессов.

В приложении "{dm}" реализованы в упрощенном виде основные элементы классического делопроизводства:

* регистрация, хранение и поиск электронных документов;
* классификация документов;
* согласование и подписание документов;
* согласование проектов договоров, в том числе с контрагентом;
* ознакомление;
* фиксация хода исполнения договоров, в том числе:
** прикрепление рабочих материалов (файлов и карточек);
** прикрепление результатов (консолидированной версии договорного документа, актов, дополнительных соглашений, других дополнительных документов);
* работа с заданиями.

Приложение может быть модифицировано под требования конкретного предприятия.

