= Бизнес-процессы

Приложение {dm} добавляет в систему {dv} бизнес-процессы, перечисленные далее.

. "Мониторинг договоров для автоматического продления".
+
Бизнес-процесс предназначен для периодического поиска карточек вида _Договор_ с истекшим сроком действия. Если для найденной карточки в поле *Периодическое продление* настроен один из вариантов автоматического продления, бизнес-процесс обновляет срок действия договора на указанный период и фиксирует в истории дату переноса срока.
+
В первый раз бизнес-процесс запускается вручную администратором при установке приложения. Далее запуск выполняется по расписанию, указанному в настройках шаблона (по умолчанию один раз в `5` минут).
+
. "Изменение срока действия Договора при заключении ДС о переносе сроков".
+
Бизнес-процесс предназначен для изменения срока действия карточки вида _Договор_ на сроки, указанные в связанной карточке вида _Доп. соглашение о продлении сроков_. Если в дополнительном соглашении сроки не указаны, сроки в договоре остаются без изменений.
+
Бизнес-процесс запускается при переходе карточки вида _Доп. соглашение о продлении сроков_ в состояние `Заключёно` (по выполнению команды *Заключить* на ленте карточки).
