= Виды карточек

.Приложение {dm} добавляет в _Справочник видов карточек_ следующие виды карточек:
. _Документ УД_ с подвидами:
.. _Входящий_ -- предназначен для хранения в системе файлов входящей корреспонденции.
.. _Исходящий_ -- предназначен для хранения в системе файлов исходящей корреспонденции.
.. _ОРД_ -- предназначен для работы с внутренними организационно-распорядительными документами.
.. _Служебная записка_ -- документ информационно-справочного характера, используемый для ведения деловой переписки внутри предприятия.
.. _Заявка_ -- предназначен для хранения в системе файлов внутренней корреспонденции, используемых для отправки различных заявок.
.. _Рабочий_ -- предназначен для выполнения произвольных задач документооборота. Использование документа предполагается внутри рабочих групп.
.. _Договор_ -- предназначен для хранения данных о заключаемом договоре; с подвидами:
... _Акт_ -- предназначен для хранения сведений об акте по договору.
... _Дополнительное соглашение_ -- предназначен для хранения сведений о дополнительном соглашении.
. _Файл_ -- предназначен для хранения файлов различных форматов.
. _Задание УД_ с подвидами:
.. _На исполнение_ -- предназначен для отправки пользователю задания на исполнение.
.. _На ознакомление_ -- предназначен для отправки пользователю задания на ознакомление.
. Группа заданий УД -- предназначен для рассылки заданий группе пользователей.
