= Общие сведения о модуле

[#general-info]
Приложение {dm} добавляет в систему {dv} типовую реализацию электронного документооборота организации и функции для работы с договорами.

Приложение предполагается применять в организациях, использующих систему {dv}.

{dm} является _базовым модулем_ системы {dv}, содержащим готовое к использованию прикладное _решение_ по работе с обычными и договорными документами. Предоставляемое Приложением _решение_ ориентировано на массовое использование -- повседневную работу сотрудников и их взаимодействие в составе рабочих групп.

Приложение является удобным средством для эффективной и упорядоченной работы с документами на любом предприятии, где нет сложной системы делопроизводства, либо планируется начать автоматизацию документооборота с простых процессов.

.В приложении {dm} реализованы в упрощенном виде основные элементы классического делопроизводства:
* Регистрация, хранение и поиск электронных документов.
* Классификация документов.
* Согласование и подписание документов.
* Согласование проектов договоров, в том числе с контрагентом.
* Ознакомление.
* Фиксация хода исполнения договоров, в том числе:
** Прикрепление рабочих материалов (файлов и карточек).
** Прикрепление результатов (консолидированной версии договорного документа, актов, дополнительных соглашений, других дополнительных документов).
* Работа с заданиями.

Приложение может быть модифицировано под требования конкретного предприятия.

[#purpose]
== Назначение документации

Настоящая документация содержит инструкции по администрированию и использованию приложения _{dm}_ (далее -- "Приложение"), а также описание видов карточек Приложения, и инструкцию по работе с документами и заданиями в {wincl}е.

[NOTE]
====
Инструкция по работе с согласованиями приведена в xref:approval:user:create-launch-approval.adoc[документации] Модуля _{ad}_.
====

[#arrangement]
== Как организована документация модуля

.Документация модуля содержит следующие разделы:
* <<general-info,Общие сведения>> о Приложении.
* xref:requirements.adoc[Требования] Приложения к программному и аппаратному обеспечению компьютера.
* xref:structure.adoc[Структура Приложения] -- перечисление составных частей Приложения.
* xref:admin:install.adoc[Установка и настройка] -- инструкция по установке Приложения.
* xref:admin:update-module.adoc[Установка новой версии приложения] -- инструкция по установке новой версии Приложения.
* Функции администратора -- описание настроек Приложения, выполняемых администратором {dv}.
* xref:user:preparation.adoc[Подготовка к работе] -- условия для работы с карточками Приложения в программе {wincl}/РМА.
* Раздел "Работа с модулем "Управление Документами" -- описание операций с карточками _Документ УД_, _Задание УД_, _Группа заданий УД_.
