= Необходимые ресурсы

== Необходимое техническое обеспечение

См. требования в пункте "Необходимое техническое обеспечение" xref:backoffice::requirements.adoc#hard[документации] модуля _{bo}_.

[#soft]
== Требования к системе {dv}

Для корректной работы данной версии модуля _{dm}_ требуется установить *серверную* и *клиентскую* части следующих модулей:

.. Серверная часть модуля _{pl}_ {pl-req} и выше.
.. Серверная часть модуля _{bo}_ {bo-req} и выше.
.. Серверная часть модуля _{wf}_ {wf-req} и выше.
.. Серверная часть модуля _{ad}_ {ad-req} и выше.
.. Серверная часть приложения _{to}_ {to-req} и выше.
.. Серверная часть модуля _{wincl}_ {win-req} и выше.

[#license]
== Лицензия

Для работы с приложением {dm} необходима лицензия на систему {dv}.

// tag::contracts[]
Для работы с договорами лицензия {dv} должна содержать лицензионную опцию _{dv} Contracts_. При отсутствии лицензии пользователь не сможет создавать и открывать карточки _Договор_, _Акт_, _Дополнительное соглашение_.
// end::contracts[]
