= Необходимые ресурсы

== Необходимое техническое обеспечение

См. требования в пункте "Необходимое техническое обеспечение" xref:backoffice::requirements.adoc#hard[документации] модуля _{bo}_.

[#soft]
== Требования к системе {dv}

// TODO -- установка только на Линукс, потом поправить.
Для корректной работы данной версии модуля _{dm}_ требуется установить *серверные* компоненты модулей системы. Серверные компоненты устанавливаются на ОС Linux из репозиториев {dv}. Также серверные компоненты необходимо ставить на ОС Windows при помощи инсталляторов для обеспечения работы Консоли настройки {dv}.

.. Серверная часть модуля _{pl}_ {pl-req} и выше.
.. Серверная часть модуля _{bo}_ {bo-req} и выше.
.. Серверная часть модуля _{wf}_ {wf-req} и выше.
.. Серверная часть модуля _{ad}_ {ad-req} и выше.
.. Серверная часть приложения _{to}_ {to-req} и выше.
.. Серверная часть модуля _{wincl}_ {win-req} и выше.

*Клиентские* компоненты необходимо ставить на ОС Windows, если планируется использовать {wincl}.

[#license]
== Лицензия

Для работы с приложением {dm} необходима лицензия на систему {dv}.

// tag::contracts[]
Для работы с договорами лицензия {dv} должна содержать лицензионную опцию _{dv} Contracts_. При отсутствии лицензии пользователь не сможет создавать и открывать карточки _Договор_, _Акт_, _Дополнительное соглашение_.
// end::contracts[]
