= Необходимые ресурсы

== Необходимое техническое обеспечение

См. требования в пункте "Необходимое техническое обеспечение" xref:backoffice::requirements.adoc#hard[документации] модуля "{bo}".

[#soft]
== Необходимое программное обеспечение

Для корректной работы данной версии модуля "{dm}" требуется установить *серверную* и *клиентскую* части следующих модулей:

.. Серверная часть модуля {dv} 5. {pl} {pl-req} и выше.
.. Серверная часть модуля {dv} 5. {bo} {bo-req} и выше.
.. Серверная часть модуля {dv} 5. {wf} {wf-req} и выше.
.. Серверная часть модуля {dv} 5. {ad} {ad-req} и выше.
.. Серверная часть приложения {dv} 5. Делопроизводство 4.5 {dp-req} и выше.
.. Серверная часть модуля {dv} 5. {wincl} {win-req} и выше.

[#license]
== Лицензия

Для работы с приложением {dm} необходима лицензия на систему {dv}.

Для работы с договорами лицензия {dv} должна содержать лицензионную опцию _{dv} Contracts_. При отсутствии лицензии пользователь не сможет создавать и открывать карточки _Договор_, _Акт_, _Дополнительное соглашение_.
