= Папки

.Приложение {dm} добавляет в систему {dv} папки:
. _Документы_ -- содержит набор подпапок, каждая из которых предназначена для работы с определенным подвидом карточек вида _ДокументУД_.
. _Отчеты_ -- содержит виртуальные папки, позволяющие получить документы, находящиеся на подписании, на согласовании, и задания за период времени, к исполнению.
. _Служебные_ -- доступная только администратору {dv} папка со служебными подпапками:
* _Бизнес-календарь_ -- папка для хранения бизнес-календарей.
* _Бизнес-процессы_ -- папка для хранения бизнес-процессов, используемых для работы специализированных карточек приложения.
* _Маршрутизация_ -- папка для хранения структурированных папок с настроенными поисковыми запросами.
* _Предустановки согласования_ -- содержит шаблоны БП согласования.
. _Договоры_ -- содержит папки, используемые при работе с договорами:
* _Договорные документы_ -- папка, предназначенная для создания карточек договорных документов.
* _Отчеты_ -- папка для хранения отчетов по договорным документам.
* _Служебные_ -- папки для хранения административных настроек приложения. Данные папки доступны администратору приложения.

Набор отображаемых папок зависит от прав пользователя.

Параметры папок перечислены в xref:admin:module-folders.adoc[Приложении A].
