= Служебные группы

Приложение {dm} добавляет в систему {dv} служебные группы, перечисленные далее.

. _Администраторы УД_.
+
Сотрудники, включенные в эту группу, имеют права на модификацию структуры папок _Управления документами_, а также права на чтение и запись карточек заданий. Также сотрудники данной группы включаются в роль _Администратор УД_.
+
. _Администраторы РГ_.
+
Сотрудники, включенные в эту группу, имеют права на управление рабочими группами: создание, удаление, включение пользователей.
+
У пользователя, включенного в данную группу, в {wincl}е появится вкладка _Рабочие группы_. Описание действий по управлению рабочими группами приведено в разделе _Работа с модулем "Управление документами"_.
+
. _Системная для WF_.
+
Группа предназначена для обеспечения доступа к карточкам БП. В данную группу включается пользователь, под учетной записью которого запущен сервис Workflow.
+
. _Печать Договоров_
+
Группа, сотрудники которой получают задание распечатать бумажный оригинал согласованного договора перед началом его подписания в _демонстрационном маршруте согласования_.
+
. _Согласование Договоров_
+
Группа сотрудников, которым будут рассылаться задания на согласование договорных документов при использовании _демонстрационного маршрута согласования_.
+
. _Чтение всех договоров_ -- группа, сотрудники которой получают возможность создания отчётов по договорным документам.
