= Уровень подготовки пользователя

Для эксплуатации приложения {dm} определены две пользовательские роли: администратор {dv} и конечный пользователь. Настройку _решения_ на базе системы {dv} с использованием Приложения выполняет инженер {dv}.

Администратор {dv} устанавливает Приложение (серверную и клиентскую части), выполняет первоначальную настройку, выявляет неполадки в работе бизнес-процессов Приложения в процессе эксплуатации.

Инженер {dv} настраивает работу с карточками Приложения при помощи предоставляемых _конструкторов_ и _справочников_ {dv}, разрабатывает скрипты карточек, настраивает бизнес-процессы.

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой, согласованием и т.п.

Администратор или конечный пользователь {dv} заполняют и актуализируют справочники {dv}.

Все пользователи Приложения должны обладать базовыми навыками работы на персональном компьютере, в xref:winclient::index.adoc[программе {wincl}].

Администратор {dv} должен обладать навыками настройки модуля {pl}, а также ознакомиться с xref:admin:install.adoc[документацией] по администрированию Приложения _{dm}_.

.Инженер {dv}:
* Должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}.
* Иметь опыт разработки на языке C# или Visual Basic .NET
* Должен ознакомиться с данной документацией для Приложения _{dm}_, а также с документацией xref:programmer::index.adoc[{dv} 5.5. Руководство программиста].

Конечные пользователи должны ознакомиться с xref:user:preparation.adoc[разделом документации] для пользователей.
