= Роли

.Приложение {dm} добавляет в систему {dv} пользовательские роли для работы с документами.
. Общие роли:
+
* _Администратор УД_ -- сотрудники включенные в группу _Администраторы УД_. Данной роли предоставляется разрешение на операцию "Просмотр истории".
* _Системная для WF_ -- сотрудники включенные в группу _Системная для WF_. Роль предназначена для предоставления доступа к карточкам системному пользователю, от имени которого СУБП (Workflow) работает с {dv}.
+
. Роли карточек вида _Документ УД_:
+
* _Регистратор_ -- сотрудник, создавший документ в системе.
* _Все руководители_ -- руководитель и его заместители для регистратора и участников согласования.
* _Участник задания с отчетом_ -- _Автор_, _Контролер_ или _Исполнитель_ задания, к которому данный документ приложен в качестве отчета. Роль предоставляет право на чтение документа-отчета.
* _Участник задания по документу_ -- _Автор_, _Контролер_ или _Исполнитель_ задания по документу (включая подчиненные), а также все их заместители (постоянные и временные).
+
Также используется для назначения прав доступа участникам согласования по документу.
+
* _Участник рабочей группы_ -- сотрудник, входящий в состав рабочей группы _Справочника сотрудников_, указанной в поле _Рабочая группа_. Роль открывает доступ на чтение карточек сотрудникам, входящим в состав группы. Данная роль используется только в виде _Документ УД/Рабочий_.
+
. Роли карточек вида _Договор_:
+
* _Группа ознакомления_ -- сотрудники, имеющие право на чтение карточки договора.
+
Определяется через принадлежность к Группе договора в Конструкторе справочников.
+
* _Все руководители_ -- сотрудники, являющиеся руководителями лиц, участвующих в карточке _Договор_ и имеющие право на ее чтение.
* _Подготовил_ -- сотрудник, инициирующий все действия с договором. Как правило, является помощником _Ответственного_ лица.
* _Ответственный_ -- сотрудник, ответственный за договор. При работе с приложением имеет те же права, что и роль _Подготовил_.
* _Участник согласования_ -- сотрудник, участвующий в согласовании и подписании договора.
* _Участник задания по документу_ -- сотрудник, исполняющий роль в задании, созданном из карточки договора.
* _Чтение всех договоров_ -- сотрудники, имеющие право на чтение карточки договора.
+
Определяется через принадлежность к группе _Чтение всех договоров_.
+
Роль используется для создания отчетов по договорным документам.
+
. Роли карточек вида _Договор -- Акт_:
+
* Подготовил -- сотрудник, инициирующий все действия с актом. Как правило, является помощником _Ответственного_ лица.
* _Ответственный_ -- сотрудник, ответственный за акт. При работе с приложением имеет те же права, что и роль _Подготовил_.
* _Все руководители_ -- сотрудники, являющиеся руководителями лиц, участвующих в карточке _Акт_ и имеющие право на ее чтение.
* _Участник задания по документу_ -- сотрудник, исполняющий роль в задании, созданном из карточки акта.
+
. Роли карточек вида _Договор -- Дополнительное соглашение_:
+
* _Подготовил_ -- сотрудник, инициирующий все действия с дополнительным соглашением. Как правило, является помощником _Ответственного_ лица.
* _Ответственный_ -- сотрудник, ответственный за дополнительное соглашение. При работе с приложением имеет те же права, что и роль _Подготовил_.
* _Группа ознакомления с дополнительным соглашением_ -- сотрудники, имеющие право на чтение карточки дополнительного соглашения.
+
Определяется через принадлежность к _Группе договора_ в Конструкторе справочников.
+
* _Все руководители_ -- сотрудники, являющиеся руководителями лиц, участвующих в карточке _Дополнительное соглашение_ и имеющие право на ее чтение.
* _Участник согласования_ -- сотрудник, участвующий в согласовании и подписании дополнительного соглашения.
* _Участник задания по документу_ -- сотрудник, исполняющий роль в задании, созданном из карточки дополнительного соглашения.
* _Чтение всех договоров_ -- сотрудники, имеющие право на чтение карточки договора.
+
Определяется через принадлежность к группе _Чтение всех договоров_ в Справочнике сотрудников. Роль используется для создания отчетов по договорным документам.
+
. Роли карточек вида _Задание УД_:
+
* _Автор_ -- сотрудник, указанный в поле _Автор_, а также его постоянные и временные заместители.
* _Исполнитель_ -- текущий исполнитель задания, а также его постоянные и временные заместители.
* _Делегировавший_ -- сотрудник, когда-либо выполнявший делегирование задания.
* _Контролер_ -- сотрудник, указанный в поле _Контролёр_, а также его постоянные и временные заместители.
* _Все руководители_ -- руководители и заместители руководителей текущих _Исполнителей_ или _Автора_ задания.
* _Ответственный исполнитель_ -- сотрудник, отвечающий за исполнение заданий группы заданий, может завершать задания других исполнителей, осуществлять контроль и приемку.
+
Роль используется только в заданиях, сформированных при помощи _Группы заданий_.
+
* _Автор, исполнитель или контролер родительского задания_ -- сотрудник-участник родительского задания, роль используется для доступа к дочерним заданиям из родительских.
+
В заданиях _На исполнение_ используются роли: _Автор_, _Автор, исполнитель или контролер родительского задания_, _Все руководители_, _Делегировавший_, _Исполнитель_, _Контролер_, _Ответственный исполнитель_.
+
В заданиях _На ознакомление_ используются роли: _Автор_, _Автор, исполнитель или контролер родительского задания_, _Все руководители_, _Исполнитель_.
+
. Роли карточек вида _Группа заданий УД_:
+
* _Автор_ -- сотрудник, указанный в поле _Автор_, по умолчанию -- текущий сотрудник.
* _Читатель_ -- сотрудник, который может открыть карточку на чтение (Исполнитель задания Группы заданий).
* _Ответственный исполнитель_ -- один из пользователей с ролью Исполнитель, имеющий доступ к заданиям остальных исполнителей, с возможностью изменения сроков выполнения, отзыва и завершения заданий.
