= Предварительный просмотр файла

Предварительный просмотр поддерживается как для _основных_, так и для _дополнительных_ файлов.

Для открытия файла в режиме чтения используется _Область предварительного просмотра_ карточки _Документ_, или _Панель просмотра_ {wincl}а. Если формат файла не поддерживается, или не установлено соответствующее приложение, предварительный просмотр будет невозможен.

Предварительный просмотр файла в теле карточки поддерживается только для тех форматов, для которых в системе Windows установлено средство предварительного просмотра.

.В большинстве случаев предварительный просмотр используется для файлов следующих форматов:
* Простые текстовые файлы без форматирования.
* Файлы документов _Microsoft Office_ (`.doc`,`.docx`,`.xls`, `.xlsx` и остальные) версий 2016x86 и младше;
* Файлы PDF.
* Файлы в графических форматах (`.jpg`, `.bmp`, `.png` и остальные).

При работе в ОС Windows 2003 с карточкой документа, в области предварительного просмотра могут отображаться не все форматы файлов. В частности, не будут отображаться картинки и файлы MS Office, содержащие изображения.
