= Просмотр журнала исходящих документов

_Журнал исходящих документов_ предназначен для поиска всех документов вида _Документ УД -- Исходящий_, доступных роли текущего пользователя, за период, указанный пользователем.

.Для поиска информации в журнале можно воспользоваться следующими функциями:
* Фильтрация доступна по виду документа. По умолчанию -- _Исходящий и его дочерние_.
** По состоянию. По умолчанию -- _Все_.
** По периоду регистрации. По умолчанию -- _Неделя_.
* Группировка доступна по дате регистрации и организации.
* Сортировка доступна по дате регистрации. По умолчанию -- по убыванию.

.Чтобы открыть журнал:
. В _Дереве папок_ откройте папку menu:Документы[Исходящие > Журнал исходящих документов].
. В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.
. Нажмите на кнопку *ОК*.
+
Найденные карточки будут отображены в _Области представления_. Для отображения будет использован вид представления: menu:Отчёты[Журнал исходящих документов].
