= Настройка режима создания карточки

Администратор {dv} может определить различные режимы создания карточек. Для приложения {dm} предусмотрен дополнительный способ создания карточек: xref:card-kinds/modes-response.adoc[в ответ на полученную карточку].

.При установке приложения по умолчанию для карточек уже настроены следующие режимы создания:
* Для карточки _Документ_:
** Для вида _Документ УД/Исходящий_ -- режим "Исходящий в ответ на входящий": из карточки вида _Входящий_ будет создана карточка _Исходящий_.
** Для вида _Документ УД/Входящий_ -- режимы:
*** "Входящий в ответ": из карточки _Исходящий_ будет создана карточка _Входящий_.
*** _Входящий по штрих-коду_: из карточки _Входящий_ при сканировании штрих-кода документа будет автоматически создаваться новая карточка вида _Входящий_.
** Для вида _Документ УД/Договор/Акт_ -- режим _Акт_: из карточки вида _Договор_ будет создана карточка _Договор/Акт_.
** Для вида _Документ УД/Договор/Дополнительное соглашения_ -- режимы:
*** _Доп. соглашение_: из карточки вида _Договор_ будет создана карточка _Договор/Дополнительное соглашения_.
*** _Доп. соглашение о продлении сроков_ -- из карточки вида _Договор_ будет создана карточка _Договор/Дополнительное соглашения_ с новыми сроками действия договора.
* Для карточки _Задание_ -- вариант создания задания xref:card-kinds/modes-response.adoc[без размещения]:
** Для вида _На исполнение_ режим _На исполнение_: в случае создания задания на исполнение при помощи кнопки _Создать задание_ на ленте {wincl}а ярлык карточки не будет сохранен в выбранной папке _Дерева папок_.

При необходимости администратор {dv} может настроить другие xref:dev@desdirs:card-kinds:card-create-mode.adoc[режимы создания карточек] в _Справочнике видов карточек_.
