= Допустимые и недопустимые изменения

[#permitted]
== Допустимые изменения

.Допускаются изменения, не влияющие на логику поведения и работоспособность приложения, а именно:
* Справочник видов карточек:
** Изменение специальных настроек карточки _Документ_.
** Изменение специальных настроек карточки _Задание_.
** Изменение специальных настроек карточки _Группа заданий_.
** Добавление и настройка режимов создания видов карточек.
** Конструктор состояний:
** Изменение доступности операций редактирования.
** Добавление состояний.
* Конструктор ролей:
** Добавление новых ролей, их переименование, изменение и удаление.
** Настройка матрицы доступа (в том числе -- для базовых ролей).
* Конструктор разметок:
** Добавление расширенного поля.
** Изменение разметки:
*** Смена места расположения преднастроенных элементов управления и добавление элементов, не влияющих на бизнес-логику карточек,
*** Удаление элементов управления и изменение Дерева дизайнов (кроме видов Документ УД и Задание УД).
** Изменение иконок кнопок.
** Конструктор правил нумерации:
** Изменение настроенных записей в настроенных правилах нумерации.
** Добавление собственных правил.
* Конструктор справочников:
** Ограничения отсутствуют.
* Справочник ссылок:
** Добавление новых записей в справочник, удаление и изменение существующих записей.
* Справочник категорий:
** Ограничения отсутствуют.
* Справочник меток подписей:
** Добавление новых записей в справочник, удаление и изменение существующих записей.
* Отчеты (Excel):
** Добавление новых отчетов, удаление и изменение существующих.
* Справочники и настройки библиотеки Делопроизводства 4.5: ограничения отсутствуют.
* Добавление, удаление и изменение собственных представлений и поисковых запросов:
** Ограничения отсутствуют.
* Скрипты Конструктора скриптов:
** Любые изменения кроме корневых видов Документ УД, Задание УД.
+
При обновлении версии модуля скрипты карточки Группа заданий УД будут перезаписаны. При необходимости, предварительно сохраненные скрипты могут быть восстановлены после обновления.
+
* Изменение структуры общих папок (в том числе для поиска), кроме папок, указанных в списке _Недопустимые изменения_.

[#forbidden]
== Недопустимые изменения

. Удаление групп из _Справочника сотрудников_:
+
* _Системная для Workflow_.
* _Администраторы УД_.
* _Администраторы РГ_.
* _Администраторы КС_.
+
. Удаление или модификация бизнес-процессов в папках: menu:{ad}[Бизнес-процессы > Шаблоны] и menu:Служебные[Бизнес-процессы].
. Удаление или изменение стандартных папок, включая папки: menu:Договоры[Служебные], menu:Служебные[Маршрутизация] и их подпапки.
. Удаление или изменение стандартных представлений и поисковых запросов.
