= Типовые сценарии модификации

В данном пункте приведены правила, которых следует придерживаться при выполнении модификации приложения {dm}.

.В тексте используются термины:
* Стандартный вид -- вид документа, включенный в поставку приложения.
* Дочерний вид -- вид документа, добавленный как подчиненный к виду документа, включенному в поставку приложения.

Требуемые изменения и рекомендованные способы их выполнения перечислены далее.

== Добавление нового вида карточки со стандартной логикой обработки

В Справочнике видов карточек добавить в Дерево видов собственные виды с полным наследованием от родительского вида.

При обновлении приложения новые виды, относящиеся к приложению {dm}, останутся без изменений.

== Исключение из использования стандартных видов карточек

В Справочнике видов карточек установить флаги "Запретить создание карточек данного вида", "Сделать вид недоступным для выбора".

После обновления флаг "Сделать вид недоступным для выбора" необходимо установить повторно.

== Настройка Справочника сотрудников

Настройка выполняется стандартным образом.

При обновлении приложения данные Справочника сотрудников не изменятся.

== Настройка дерева папок

Настройка выполняется стандартным образом. Демонстрационные данные приложения можно переименовать или удалить, кроме обозначенных как недопустимые изменения.

При обновлении приложения будет выполнено обновление папки с шаблонами бизнес-процессов; папка Договоры и её подпапки, кроме папки Служебные, при обновлении не меняются; на папку Договоры будут восстановлены стандартные права доступа.

== Изменение структуры папок маршрутизации Замещение, Мои задания, Мои документы

В дереве папок настроить собственную структуру маршрутизации. Структуру папок приложения не использовать.

При обновлении приложения пользовательская структура папок не изменяется. Структура папок приложения будет обновлена.

== Изменение папки Договоры/Служебные и её подпапок

Скопировать нужные папки и вносить изменения в копии.

При обновлении приложения папка может измениться.

== Изменение стандартных фильтров и представлений

Изменение и удаление базовых фильтров и представлений приложения {dm} допускается. Можно настроить новые и подключить в дерево папок. Изменение и удаление базовых фильтров и представлений, используемых в папке Договоры не рекомендуется. Можно настроить новые и подключить в дерево папок.

При обновлении приложения пользовательские фильтры и представления не изменятся; существующие фильтры папки Договоры будут восстановлены.

== Ролевая модель. Настройка Матрицы доступа

Разрешено изменение Матрицы доступа для существующих видов карточек.

При обновлении приложения матрица доступа не обновляется. 

== Ролевая модель. Добавление новой роли, изменение существующей роли

Допускается добавление новых ролей. Допустимо изменение всех флагов в Матрице доступа. Изменение и удаление базовых ролей приложения {dm} запрещено. Разрешено изменение/удаление ролей дочерних видов.

При обновлении приложения добавленные роли и матрица доступа не изменяются.

== Настройка Конструктора правил нумерации*.

Допускается изменение настроек существующих правил нумерации. Допускается добавление новых правил нумерации.

== Изменения отчётов

Допускается добавление пользовательских отчётов.

== Настройка Справочника ссылок

Допускается добавление пользовательских типов ссылок.

== Настройка Конструктора справочников для узла {dm}

Добавление записей в справочник осуществляется стандартным образом.

== Настройка Конструктора справочников для узла "Группы договоров"

Добавление записей в справочник осуществляется стандартным образом.

== Изменение автомата состояний*.

Изменение автомата состояний для базовых видов карточек приложения {dm} запрещено. Разрешена операция копирования вида без наследования, с последующей настройкой Автомата состояний. Запрещено изменять автомат состояний видов Договор, Акт, Дополнительное соглашение.

== Добавление поля в карточку

Необходимо добавление расширенного поля в карточку. Если поле необходимо вывести в разметке, требуется изменение разметки.

== Изменение разметки

Изменение разметки для базовых видов карточек приложения {dm} разрешено, за исключением видов Документ УД, Задание УД, Договор, Акт и Дополнительное соглашение. Нужно добавить дочерний вид карточки без использования наследования разметок.

== Изменение настроек Справочника видов карточек

Изменение настроек справочника для базовых видов карточек приложения {dm} разрешено, за исключением видов Документ УД и Задание УД.

== Изменение скриптов

Изменение скриптов для видов карточек приложения {dm} разрешено, за исключением видов Документ УД, Задание УД, Договор, Акт, Дополнительное соглашение. Допускается изменение скриптов и для пользовательских видов (даже если все настройки наследуются) путем переопределения методов от родительского вида.

== Изменение маршрута согласования

Разрешены изменения маршрута согласования в видах Договор, Акт, Дополнительное соглашение. Новый маршрут может быть подключен путем добавления соответствующего режима создания стандартной карточки согласования. Демонстрационный маршрут согласования договоров, включенный в поставку, может быть отключен путем удаления соответствующего режима создания карточки согласования.
