= Создание группы заданий по документу

Группы заданий позволяют создавать детализированные распоряжения по документу, предназначенные для выполнения сразу несколькими исполнителями. В зависимости от настройки, задания могут быть отправлены либо одновременно всем назначенным исполнителям, либо последовательно "передаваться" от одного исполнителя к другому. В последнем случае отправка задания следующему исполнителю будет происходить после завершения задания предыдущим исполнителем из очереди.

Для создания группы заданий в приложении _{dm}_ предусмотрена специальная xref:cards/task-group.adoc[карточка "Группа заданий УД"]. После активизации данной карточки система Создаёт бизнес-процесс в соответствии с указанными параметрами, и рассылаются задания исполнителям.

Каждое из заданий, отправленных исполнителям, снабжено описанием работ, сроками их исполнения и другими параметрами, а также предусматривает контроль за ходом выполнения задания.

Работа с данным видом заданий описана в разделе xref:tasks/create-groups/new-group.adoc[Создание группы заданий].
