= Подписание договора

См. также "xref:docs-sign.adoc[]".

В демонстрационном согласовании договор подписывают сотрудники, указанные в поле _Подписывает_ карточки Договор.

При получении задания на подписание подписант может ознакомиться с уже согласованными документами и высказать положительное или отрицательное решение.

include::5.5.17@webclient:user:partial$excerpts.adoc[tags=incomingFolder]
+
. Откройте полученное задание с описанием _Подписание документов_ в состоянии `Не начато`.
. Чтобы принять решение по подписанию на xref:5.5.17@webclient:user:cards-terms.adoc#cards-operations[панели операций] нажмите кнопку:
* *Подписано*. Договорной документ будет переведен в состояние `Подписан`.
+
include::5.5.4@documentmgmt:user:partial$excerpts.adoc[tags=35mb]
+
[NOTE]
====
include::5.5.17@webclient:user:user:partial$excerpts.adoc[tags=signature]
====
+
* *Отказано в подписании* -- договорной документ будет переведен в состояние Подготовка.
+
****
После проставления отметки о подписании, в соответствии с демонстрационным маршрутом согласования будет выполнен переход к этапу _Завершён этап подписания_.

Соответствующее задание поступит пользователю, указанному в поле `Подготовил` карточки договора.
****
