= Перечень полей входящего документа

xref:webclient:user:appendix/simple-fields.adoc[Тема]::
Название документа.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:webclient:user:appendix/numerator.adoc[Регистрационный номер]::
Регистрационный номер документа. Может быть получен из списка свободных номеров. Ручной ввод номера не предусмотрен.

xref:webclient:user:appendix/date-time.adoc[Дата регистрации]::
Дата регистрации документа в организации. По умолчанию устанавливаются текущие дата и время.

xref:webclient:user:appendix/staff-directory-items.adoc[Регистратор]::
Сотрудник, который будет регистрировать документ. По умолчанию выбирается текущий сотрудник.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:webclient:user:appendix/text.adoc[Описание]::
Дополнительная информация по документу.

xref:webclient:user:appendix/files.adoc[Файлы]::
Файлы документа.
include::partial$excerpts.adoc[tags=scanOrFileSystem]
+
xref:webclient:user:appendix/staff-directory-items.adoc[Получатели]::
Сотрудники организации, которые должны быть ознакомлены с документом.

Отправитель-контрагент::
Информация об организации-отправителе документа.

xref:webclient:user:appendix/partner-company.adoc[Организация-отправитель]:::
Контрагент, отправивший документ.

xref:webclient:user:appendix/partner.adoc[Сотрудник-отправитель]:::
Ответственный сотрудник контрагента.

xref:webclient:user:appendix/simple-fields.adoc[Номер отправителя]:::
Номер документа, который был присвоен в организации-отправителе.
+
Вводится вручную.

xref:webclient:user:appendix/date-time.adoc[Дата отправки]:::
Дата регистрации документа в организации-отправителе.
+
По умолчанию устанавливаются текущие дата и время.
