= Перечень полей задания на исполнение

xref:5.5.17@webclient:user:appendix/simple-fields.adoc[Тема]::
Тема задания.
+
include::5.5.17@webclient:user:partial$excerpts.adoc[tags=mandatory]

xref:5.5.17@webclient:user:appendix/staff-directory-items.adoc[Исполнители]::
Исполнители задания.
+
include::5.5.17@webclient:user:partial$excerpts.adoc[tags=mandatory]
+
Задание будет отправлено всем выбранным сотрудникам и сотрудникам выбранных организаций, подразделений, групп и ролей. Фактическим исполнителем станет первый сотрудник, взявший задание в работу.
+
[NOTE]
====
Если нужно отправить каждому сотруднику собственное задание, используйте xref:task-groups.adoc[Группу заданий].
====

xref:5.5.17@webclient:user:appendix/date-time.adoc[Срок исполнения]::
Плановый срок исполнения задания выбранными исполнителями. По умолчанию устанавливаются текущие дата и время.

xref:5.5.17@webclient:user:appendix/text.adoc[Примечание]::
Дополнительная информация по заданию.

Поставить на контроль::
Включает функции xref:tasks-user-controller.adoc[контроля исполнения] задания ответственным сотрудником. При включённом контроле станут доступны параметры контроля:

xref:5.5.17@webclient:user:appendix/staff-directory-items.adoc[Контролёр]:::
Сотрудник, который контролирует выполнение задания.

xref:5.5.17@webclient:user:appendix/date-time.adoc[Дата контроля]:::
Дата, когда должен быть выполнен контроль выполнения задания.

xref:tasks-controller-accept.adoc[Требуется приёмка]:::
Включает функцию приёмки задания контролёром. После выполнения задания исполнителем, контролёр может принять результат выполнения или отказать. При включении приёмки будет автоматически включается контроль.

xref:5.5.17@webclient:user:appendix/task-card-file-panel.adoc[Добавить файл]::
Файлы задания.
