= Перечень полей задания на ознакомление

xref:5.5.17@webclient:user:appendix/simple-fields.adoc[Тема]::
Тема задания.
+
include::5.5.17@webclient:user:partial$excerpts.adoc[tags=mandatory]

xref:5.5.17@webclient:user:appendix/staff-directory-items.adoc[Исполнители]::
Исполнители задания.
+
include::5.5.17@webclient:user:partial$excerpts.adoc[tags=mandatory]
+
Задание будет отправлено всем выбранным сотрудникам и сотрудникам выбранных организаций, подразделений, групп и ролей. Фактическим исполнителем станет первый сотрудник, взявший задание в работу.
+
[NOTE]
====
Если нужно отправить каждому сотруднику собственное задание, создайте их с помощью xref:task-groups.adoc[Группы заданий].
====

xref:5.5.17@webclient:user:appendix/date-time.adoc[Срок ознакомления]::
Плановый срок ознакомления исполнителей с приложенным к заданию документом. По умолчанию устанавливаются текущие дата и время.

xref:5.5.17@webclient:user:appendix/text.adoc[Примечание]::
Дополнительная информация по заданию.

xref:5.5.17@webclient:user:appendix/task-card-file-panel.adoc[Добавить файл]::
Файлы задания.
