= Замещение при исполнении заданий

В приложении {dm} предусмотрено несколько вариантов замещения сотрудника при выполнении заданий:

* Сотрудник может быть назначен постоянным заместителем -- в этом случае ему будут всегда доступны задания замещаемого.
* Сотрудник может являться временным заместителем -- в данном случае задания замещаемого будут доступны ему только во время неактивности (болезнь, командировка и т. п.), если при создании задания был установлен флаг xref:tasks/create-tasks/deputy.adoc["Доступно заместителю"].

.Заместители работают с заданиями замещаемого сотрудника с помощью папок:
* menu:Замещение[Входящие] -- для поступающих заданий;
** menu:Замещение[Входящие > В работе] -- для заданий замещаемого сотрудника, находящихся в работе.
** menu:Замещение[Входящие > На контроле] -- для заданий замещаемого сотрудника, находящихся на контроле.
** menu:Замещение[Входящие > Ответственное исполнение] -- для заданий замещаемого сотрудника, в которых он является ответственным исполнителем.
* menu:Замещение[Исходящие] -- для заданий, автором которых является замещаемый сотрудник.
** menu:Замещение[Исходящие > Делегировано] -- для делегированных заданий, автором которых является замещаемый сотрудник.
** menu:Замещение[Исходящие > Завершено] -- для делегированных заданий, автором которых является замещаемый сотрудник.

Настройка замещения может быть выполнена как администратором (см. xref:tasks/deputies.adoc["Настройка замещения"]), так и самим сотрудником (см. подробнее xref:winclient:user:employee-status.adoc[в документации модуля {wincl}]).

[#deputy-work]
== Работа заместителя с заданиями замещаемого

Чтобы получить задание замещаемого сотрудника:

. Перейдите в папку:
+
* menu:Замещение[Входящие] -- если нужно взять задание в работу.
* menu:Замещение[Входящие > На контроле] или menu:Замещение[Входящие > Ответственное исполнение] -- если нужно взять в работу задание, находящееся на контроле или ответственном исполнении у замещаемого сотрудника.
+
. Откройте любое из полученных заданий.
. Выполните доступные операции с заданием.
+
Заместитель может в задании замещаемого выполнять все действия, доступные замещаемому. При этом действуют следующие правила:
+
* Если заместитель xref:tasks/performance.adoc#accept[взял в работу] задание замещаемого сотрудника, _Исполнителем_ задания будет считаться заместитель. В задании автоматически фиксируется делегирование типа `Автоматически`.
* Если заместитель xref:tasks/finish.adoc[завершил] задание, он будет указан в задании в качестве завершившего задание _Исполнителя_.
+
После завершения данных заданий они будут возвращены _Автору_ задания.
+
Задания, делегированные заместителем, будут возвращены в зависимости от xref:tasks/deputies.adoc#delegate-deputy[способа] делегирования.

[#delegate-deputy]
== Делегирование задания заместителем

Возникают ситуации, когда заместитель по каким-либо причинам отказывается от самостоятельного выполнения задания и хочет передать его другому исполнителю. Для таких ситуаций можно использовать операцию делегирования.

Выполнение делегирования задания заместителем выполняется аналогично xref:tasks/performance.adoc#delegate[обычному] делегированию, за исключением некоторых особенностей.

.Чтобы делегировать задание, заместителю необходимо выполнить следующие действия:
. Чтобы делегированное задание вернулось заместителю, перед делегированием задания необходимо выполнить любое из следующих действий:
+
* xref:tasks/performance.adoc#accept[Взять в работу].
* Делегировать задание самому себе.
+
.Чтобы делегировать задание себе:
.. Нажмите на кнопку *Делегировать* в карточке задания.
.. В открывшемся окне _Делегирования_ в поле _Делегаты_ выберите текущего сотрудника (себя).
.. Нажмите на кнопку *Принять*.
+
При этом карточка задания будет закрыта, ярлык задания будет перемещен в папку menu:Замещение[Входящие] заместителя. Заместитель станет текущим исполнителем данного задания.
+
Далее можно заново открыть карточку задания и снова выполнить операцию делегирования, только выбрать в качестве делегата другого исполнителя и установить флаг `*Возврат с делегирования*`.
+
. Чтобы делегированное задание вернулось с делегирования назначенному _Исполнителю_, следует делегировать задание, не беря его в работу (из состояния `Не начато`). Для этого выполните следующие действия:
+
.. Нажмите на кнопку *Делегировать* в карточке задания.
.. В открывшемся окне _Делегирования_ в поле _Делегаты_ выберите нового исполнителя задания.
.. Нажмите на кнопку *Принять*.
+
При завершении такое задание попадёт в папку menu:Мои задания[Входящие] замещаемого сотрудника.
