= Завершение задания

.Задание могут завершить:
* _Исполнитель_, его _Заместитель_ или _Делегат_, после окончания работы над заданием;
* _Автор задания_ или _Контролёр_ могут xref:tasks/manage-launched.adoc#force-finish[прекратить] выполнение задания, когда посчитают, что задание уже выполнено.

Для делегированных заданий вида _На исполнение_ _Исполнитель_ или его _Заместитель_ могут завершить задание без взятия его в работу.

.Чтобы завершить задание для исполнителя:
. Откройте карточку _Задание УД_.
. Если это предусмотрено, добавьте отчёт в текстовое поле `Отчёт`.
. При необходимости приложите файл отчёта или выберите для отчёта карточку документа.
+
Добавленная в качестве отчёта карточка будет доступна автору задания, если для документа настроена ролевая модель, предусматривающая данную возможность.
+
. Нажмите кнопку *Завершить* на ленте инструментов карточки _Задание_.
+
Карточка задания будет закрыта. Ссылка на карточку будет перемещена в папку menu:Мои задания[Входящие > Завершено].

****
* Если задание было делегировано, и был настроен xref:tasks/performance.adoc#delegate[возврат] с делегирования, ярлык для доступа к карточке будет перемещен в папку menu:Мои задания[Входящие] исполнителя, делегировавшего задание.
* Если для задания требовалась xref:tasks/control.adoc#acceptance[приёмка], после завершения исполнителем оно перейдет на приёмку к _Контролёру_.
+
При соответствующей настройке, контролёру может быть отправлено по электронной почте уведомление следующего содержания: `В системе {dv} Вам передано на приёмку задание "Название задания", в котором Вы назначены контролёром. Для того, чтобы получить детальную информацию и ознакомиться с результатами исполнения задания, перейдите по ссылке. Будет открыта карточка задания.`
* После перехода задания в состояние `завершено` _Автору_ задания может быть отправлено по электронной почте уведомление следующего содержания: `В системе {dv} пользователем "ФИО сотрудника, завершившего задание" было завершено задание "Название задания", автором которого Вы являетесь. Для того, чтобы ознакомиться с результатами, перейдите по ссылке. Будет открыта карточка задания`.
****
