= Настройка карточек договорных документов

[#use-templates]
== Настройка использования шаблонов документов

В _Справочнике видов карточек_ на вкладке _Документы_ в таблице _Файлы_ можно указать шаблоны документов, которые будут прикладываться к создаваемым карточкам документа данного вида.

В карточки договоров включены два предварительно настроенных шаблона. См. описание шаблонов в xref:user:templates.adoc[документации пользователя]:

* Шаблон договора.
* Шаблон дополнительного соглашения.

Для поставляемых шаблонов настроена синхронизация полей в направлении "из карточки в файл".

[#template-sync]
== Настройка синхронизации полей для шаблонов документов

Под синхронизацией подразумевается настройка автоматического копирования значений ряда полей из карточки во вложенный в карточку файл и наоборот.

Синхронизацию выполняет администратор приложения в _Справочнике видов карточек_. Данная операция является базовой для системы {dv} и подробнее xref:backoffice:user:document/file-card-properties-sync.adoc[описана] в документации модуля {bo}.

В карточках видов _Договор_ и _Дополнительное соглашение_ по умолчанию настроена синхронизация полей в файл договорного документа. Для обеспечения синхронизации договорные документы должны быть созданы на основе шаблонов, входящих в комплект поставки. Администратор может изменить параметры синхронизации.

[#doc]
=== Преднастроенная синхронизация полей в договоре

Для карточки вида _Договор_ настроена синхронизация полей между карточкой и поставляемым шаблоном договора.

.Копируются значения для следующих полей:
* Рег.номер (постоянный).
* Дата заключения договора.
* Предмет.
* Организация контрагента.
* Контактное лицо контрагента.
* Наименование организации.
* Начало действия договора.
* Завершение действия договора.
* Сумма в рублях.

[#add-agger]
=== Преднастроенная синхронизация полей в доп. соглашении

Для карточки вида _Договор_ настроена синхронизация полей между карточкой и поставляемым шаблоном договора.

.Значения копируются для следующих полей:
* Рег.номер (постоянный).
* Дата заключения договора.
* Организация контрагента.
* Контактное лицо контрагента.
* Наименование организации.
