= Настройка папок

Перед началом работы пользователей с приложением администратору рекомендуется изменить структуру папок следующим образом:

* <<personal-folder,Настроить>> _Личные_ папки пользователей.
* <<search-queries,Настроить>> папки для поисковых запросов по годам.

Если по каким-либо причинам для работы пользователей с заданиями невозможно использовать папки маршрутизации Приложения, администратору следует добавить в _Дерево папок_ новые папки и настроить их в соответствии с регламентом организации.

[#personal-folder]
== Настройка личной папки пользователя приложения

В _Личную папку_ пользователя могут быть добавлены папки-делегаты на настроенные администратором папки маршрутизации.

.В стандартной поставке Приложения настроены следующие наборы папок маршрутизации:
* _Мои договоры_ -- для поиска карточек договоров различных состояний, а также для контроля хода согласования договора. Предназначена для пользователей, исполняющих роли _Ответственный_ и _Подписал_.
* _Договоры к ознакомлению_ -- для поиска карточек договоров. Предназначена для пользователей, исполняющих роль _Группа ознакомления_.

Настроить личную папку сотрудника для работы с договорами, можно одним из описанных ниже способов.

.Чтобы создать папки маршрутизации для всех пользователей:
. Добавьте папки ветки (menu:Договоры[Служебные > Маршрутизация]) _Мои договоры_ и/или папки ветки _Договоры к ознакомлению_ в использующуюся структуру маршрутизации (например, папку menu:Служебные[Маршрутизация].
+
.Для этого выполните действия:
.. Откройте {wincl} и выделите в _Дереве папок_ папку _Мои договоры_ или _Договоры к ознакомлению_.
.. Выберите из контекстного меню опцию _Копировать структуру папки_ или _Создать делегата на эту папку_.
.. В открывшемся окне _Выбор папки_ выделите папку маршрутизации (если используется маршрутизация приложения _{dm}_, то это папка _Маршрутизация_); нажмите кнопку выбора.
+
После обновления дерева папок скопированная ветка появится в личных папках пользователей приложения.
+
. Чтобы создать папки маршрутизации в личной папке определенного пользователя, настройте для него делегаты на нужные папки ветки menu:Договоры[Служебные > Маршрутизация].

[#search-queries]
== Настройка поисковых запросов по годам

Папка _Заключённые договоры_ предназначена для выполнения поиска договоров по годам.

.В Приложении настроены папки поиска договоров 2018 и 2019 годов:
* "2018 -- договоры и дополнительные соглашения";
* "2019 -- договоры и дополнительные соглашения".

Для поиска заключённых в другие годы договоров администратору следует настроить соответствующие виртуальные папки, используя вышеуказанные как образец.

В качестве примера при настройке можно использовать папку ветки menu:Договоры[Договорные документы > Заключённые договоры].
