= Демонстрационный процесс согласования

Приложение включает демонстрационный процесс согласования, по которому могут согласовываться и подписываться карточки _Договор_ и _Дополнительное соглашение_.

[NOTE]
====
Для _Демонстрационного процесса согласования_ используется маршрут _Согласование договоров_, описание которого приведено xref:admin:contracts/approval/settings.adoc[в документации по администрированию Приложения].
====

.Перед запуском процесса необходимо добавить пользователей в группы:
* _Согласование договоров_.
* _Печать договоров_.

.А также заполнить поля карточки "Договор" или "Дополнительное соглашение":
* menu:С нашей стороны[Подготовил].
* menu:С нашей стороны[Ответственный].
* menu:С нашей стороны[Подписывает].
* menu:Контрагент[Контактное лицо], в _Справочнике контрагентов_ для данного сотрудника должен быть указан e-mail.

.Демонстрационный процесс согласования представляет собой выполнение следующего сценария работы с договором:
. Согласование документа внутри организации:
+
При запуске согласования карточка договорного документа переводится в состояние `На согласовании`.
+
Всем пользователям, состоящим в группе _Согласование Договоров_ рассылаются задания вида _На согласование_, к которым приложены согласуемые файлы. Режим исполнения заданий -- *_Параллельно_*, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.
+
В процессе согласования документа исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок на ленте карточки задания _На согласование_. Решение по согласованию выносится сразу для всех файлов, приложенных к карточке задания.
+
См. xref:contracts/approval/receive.adoc[Согласование договора (дополнительного соглашения) внутри организации]
+
. Консолидация -- создание итогового документа по итогам согласования внутри организации::
+
Когда все согласующие лица высказали свое мнение по документу, консолидатор, в роли которого выступает _Инициатор_ согласования, должен принять решение о дальнейшей судьбе договора.
+
.. Если принято решение о том, что договор в текущей редакции _не согласован_, то консолидатор может:
+
* Составить новую редакцию договора и отправить её на согласование.
* Отменить согласование.
+
.. Если договор _согласован_ или _согласован с замечаниями_, карточка договорного документа переводится в состояние `Согласован`.
+
--
.После выбора итоговой на данном этапе версии документа консолидатор может:
* Отправить договор на согласование с контрагентом.
* Отправить договор на печать, если согласование с контрагентом было произведено ранее.
* Отменить согласование.
--
+
См. xref:contracts/approval/inside-consolidation.adoc[Консолидация согласованного договора].
+
. Согласование и подписание документа с контрагентом:
+
При переходе к этому этапу карточка договорного документа переводится в состояние `На согласовании Контрагентом`.
+
_Ответственному_ за договорной документ приходит задание вида _Согласование с контрагентом_, к которому приложена согласованная внутри организации версия договора.
+
Получив такое задание, сотрудник должен передать полученную версию договора на согласование в организацию контрагента, получить ответ контрагента и принять решение о дальнейшей судьбе договора.
+
.. Если принято решение о том, что договор в текущей редакции _не согласован_, то _Ответственный_ может:
+
* Погрузить в карточку версию, полученную от контрагента и отправить её на согласование внутри организации.
* Отменить согласование.
+
.. Если договор _согласован_ или _согласован с замечаниями_, _Ответственный_ может:
+
--
* Отправить договор на печать.
* Отправить договор на подписание внутри организации, если от контрагента вернулся _подписанный оригинал_.
* Отменить согласование.
--
+
См. xref:tasks/control.adoc#acceptance[Выполнение приёмки задания].
+
[NOTE]
====
Этапы согласования договора внутри организации, консолидации и согласования с контрагентом могут циклически повторяться до выработки одобренного всеми согласующими варианта договора.
====
+
. Печать бумажного экземпляра документа:
+
Этап является техническим, предваряющим подписание бумажного оригинала договорного документа. При передаче на печать карточка договорного документа переводится в состояние `На подписании`.
+
Печать договора осуществляет сотрудник из _Группы печати_, получивший задание вида _Подписание_. После печати бумажный оригинал договорного документа передается на подписание сотрудникам, указанным в поле _Подписал_ карточки договорного документа.
+
. Подписание документа внутри организации:
+
При передаче на подписание карточка договорного документа переводится (или остается) в состояние `На подписании`.
+
Всем пользователям, указанным в поле _Подписано_ рассылаются задания вида _Подписание_, к которым приложены согласованные договорные документы, требующие подписания. Режим исполнения заданий -- _Параллельно_, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.
+
В процессе подписания документа исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок на ленте карточки задания вида _Подписание_. Решение по подписанию выносится сразу для всех _Основных_ файлов, приложенных к карточке.
+
[WARNING]
====
При согласовании договора (дополнительного соглашения) с использованием демонстрационного процесса, заполнение полей _Подписано_ и _Ответственный_ в карточке _Договор_ (_Дополнительное соглашение_) является обязательным.
====
+
. Консолидация -- создание итогового документа по итогам подписания внутри организации и завершение маршрута:
+
Когда все подписанты высказали свое мнение по документу, консолидатор, в роли которого выступает _Инициатор_ согласования, должен принять решение о дальнейшей судьбе договора.
+
.. Если в подписании отказано, то консолидатор может:
+
* Составить новую редакцию договора и начать новый цикл согласования.
* Отменить согласование.
+
.. Если договор _подписан_, консолидатору следует:
+
* Завершить согласование, если ранее договор был согласован, подписан контрагентом.
* Передать договор на согласование, подписание контрагенту, если ранее этого сделано не было.
