= Согласование и подписание договорных документов

Согласовать договорные документы можно средствами модуля _{ad}_. Модуль позволяет настроить маршрут согласования таким образом, чтобы он полностью соответствовал бизнес-процессам использующего его предприятия.

В Приложение включён "xref:contracts/approval/demo.adoc[демонстрационный процесс согласования]", в рамках которого выполняется:

* Согласование внутри компании с подготовкой итогового варианта документа.
* Отправка итогового варианта документа на согласование контрагенту и проставление отметки о согласовании контрагентом.
* Печать согласованного варианта договорного документа.
* Подписание документа внутри компании и подписание документа контрагентом с проставлением соответствующих отметок в карточке.

В поставляемых видах карточек _Договор_ и _Дополнительное соглашение_ _Демонстрационного процесса согласования_ запускается командой *Создать согласование*. После разработки предприятием собственных маршрутов согласования, администратор приложения заменяет для данной команды демонстрационный маршрут на актуальный.

После запуска процесса согласования, система формирует задания (на согласование, консолидацию или подписание) и рассылает эти задания назначенным участникам. +
Участники согласования получают задания и принимают решения по согласованию (создают собственные версии документов, добавляют комментарии, накладывают согласующие подписи и т.д.). +
Согласование считается завершённым после принятия положительного решения всеми согласующими на всех этапах согласования.

[NOTE]
====
Описание правил завершения согласования см. в документации xref:6.1@approval:admin:approval-finish-rules.adoc[Модуля "{ad}"].
====

Инициатор согласования может управлять запущенным согласованием (наблюдать за ходом согласования, приостанавливать и повторно запускать процесс). Доступ к управлению открывается по команде *Открыть согласование*, расположенной на ленте карточек договорных документов.
