= Просмотр журнала входящих документов

_Журнал входящих документов_ предназначен для поиска всех документов вида _Документ УД -- Входящий_, доступных роли текущего пользователя, за период, указанный пользователем.

.Для поиска информации в журнале можно воспользоваться следующими функциями:
* Фильтрация доступна:
** По виду документа. По умолчанию -- _Входящий и его дочерние_.
** По состоянию. По умолчанию -- _Все_.
** По периоду регистрации. По умолчанию -- _Неделя_.
* Группировка доступна по дате регистрации и получателю.
* Сортировка доступна по дате регистрации. По умолчанию -- по убыванию.

.Чтобы открыть журнал:
. В _Дереве папок_ откройте папку menu:Документы[Входящие > Журнал входящих документов].
. В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.
. Нажмите на кнопку *ОК*.
+
Найденные карточки будут отображены в _Области представления_. Для отображения будет использован вид представления: menu:Отчеты[Журнал входящих документов].
