= Изменение разметок карточек

[#web]
== Изменение web-разметок

Возможность изменения настроек Решений _{bo}_, _{dm}_, _{am}_ и решений сторонних производителей по умолчанию заблокирована. Заблокированные решения не отображаются в списке. Как разблокировать изменение Решений, см. в пункте "xref:5.5.17@webclient:layouts:solutions-change-mode.adoc[]" документации {wc}а.

Описание элементов управления приведено в разделе "Описание стандартных элементов управления" xref:5.5.17@webclient:layouts:ctrl-library-standard.adoc[документации модуля {wc}].

[NOTE]
====
Вместо изменения стандартных Разметок можно скопировать данные разметки в собственное Решение или в _Мои настройки_. Копии Разметок могут быть изменены без ограничений.
====

[#windows]
== Изменение разметок в конструкторе разметок

.В разметку карточки могут быть включены следующие виды элементов управления:
* Встроенные -- элементы, добавляемые в разметку в коде программы.
* Подключаемые -- элементы, добавляемые в разметку из библиотеки элементов управления Конструктора разметок.

Описание элементов управления приведено в разделе "Описание конструкторов и справочников" xref:5.5.5@backoffice:desdirs:layouts/designer.adoc[документации модуля {bo}].

При необходимости некоторые встроенные элементы могут быть заменены на подключаемые или удалены, однако при выполнении данной операции следует учитывать ограничения, зависящие от вида карточки и выбранной разметки.
