= Просмотр журнала организационно-распорядительных документов

Журнал _Действующие ОРД_ предназначен для поиска документов вида _Документ УД -- Организационно-распорядительный_, которые были назначены действующими. Результаты поиска будут содержать только документы, доступные роли пользователя.

.Для поиска информации в журнале можно воспользоваться следующими функциями:
* Фильтрация:
** По виду документа. По умолчанию -- _ОРД и его дочерние_.
** По состоянию. По умолчанию -- _Действует_.
* Группировка доступна по подразделению.
* Сортировка доступна по дате регистрации. По умолчанию -- по убыванию.

.Чтобы открыть журнал:
. В Дереве папок откройте папку menu:Документы[Организационно-распорядительные > Действующие ОРД].
. В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.
. Нажмите на кнопку *ОК*.
+
Найденные карточки будут отображены в _Области представления_. Для отображения будет использован вид представления: menu:Отчеты[Действующие ОРД].
