[[ariaid-title1]]
== Бизнес-процессы

Приложение «Управление документами» добавляет в систему Docsvision бизнес-процессы, перечисленные далее.

. «УД Отправка на ознакомление».
+
Осуществляет отправку на ознакомление карточки вида [.dfn .term]_Задания УД_ и [.dfn .term]_Группа заданий УД_.
+
Запускается из карточек вида [.dfn .term]_Документ УД_ при отправке документа на ознакомление по нажатию кнопки [.ph .uicontrol]*На ознакомление*.
. «УД Отзыв заданий ГЗ».
+
Осуществляет отзыв карточки [.dfn .term]_Группа заданий УД_.
+
Запускается автоматически из карточек вида [.dfn .term]_Группа заданий УД_ при отзыве запущенной группы заданий Автором или Ответственным исполнителем.
. «УД Отправка почтовых уведомлений».
+
Осуществляет отправку уведомлений сотрудникам на указанный в [.dfn .term]_Справочнике сотрудников_ адрес электронной почты.
+
Запускается как самостоятельно, так и из других БП, предназначенных для отправки почтовых уведомлений.
+
В частности, с помощью данного БП выполняется:

* отправка уведомлений участникам рабочей группы о включении и исключении из состава группы, а также уведомления об удалении рабочей группы;
* отправка уведомлений об изменении состояний карточек [.dfn .term]_Задание УД_, [.dfn .term]_Задание КС_ и [.dfn .term]_Группа заданий УД_.
. «УД Отправка почтового уведомления о начале приемки задания».
+
Осуществляет отправку уведомлений о переходе карточки [.dfn .term]_Задание УД/На исполнение_ в состояние «На приемке»: Контролеру; Ответственному исполнителю (для заданий, созданных из [.dfn .term]_Группы заданий УД_).
. «УД Отправка почтового уведомления об отклонении задания автору».
+
Осуществляет отправку уведомлений Автору задания о переходе карточки [.dfn .term]_Задание_ в состояние «Отклонено».
. «УД Отправка почтового уведомления о завершении задания автору».
+
Осуществляет отправку уведомлений Автору задания о переходе карточки [.dfn .term]_Задание_ в состояние «Завершено».
. «УД Отправка почтового уведомления о завершении группы заданий автору».
+
Осуществляет отправку уведомлений Автору группы заданий о переходе карточки [.dfn .term]_Группа заданий УД_ в состояние «Завершено».
+
[NOTE]
====
[.note__title]#Важное замечание:# Для возможности отправки уведомлений бизнес-процессами необходимо настроить систему Docsvision. Требования приведены в разделе xref:Notification.adoc[Настройка уведомлений].
====
. «Изменение срока действия Договора при заключении ДС о переносе сроков».
+
Бизнес-процесс предназначен для изменения срока действия карточки вида [.dfn .term]_Договор_ на сроки, указанные в связанной карточке вида [.dfn .term]_Доп. соглашение о продлении сроков_. Если в дополнительном соглашении сроки не указаны, сроки в договоре остаются без изменений. Запуск бизнес-процесса выполняется при переходе карточки вида [.dfn .term]_Доп. соглашение о продлении сроков_ в состояние `Заключено` (по выполнению команды [.keyword]*Заключить* ленты карточки).
. «Мониторинг договоров для автоматического продления».
+
Бизнес-процесс предназначен для периодического поиска карточек вида [.dfn .term]_Договор_ с истекшим сроком действия. Если для найденной карточки в поле [.keyword]*Периодическое продление* настроен один из вариантов автоматического продления, бизнес-процесс обновляет срок действия договора на указанный период и фиксирует в истории дату переноса срока. Первичный запуск бизнес-процесса выполняется вручную администратором при установке приложения. Далее запуск выполняется по расписанию, указанному в настройках шаблона (по умолчанию один раз в 5 минут).

*На уровень выше:* xref:../topics/Structureof_program.adoc[Структура Приложения]
