[[ariaid-title1]]
== Виды карточек

Приложение «Управление документами» добавляет в [.dfn .term]_Справочник видов карточек_ виды карточек, перечисленные далее.

. [.dfn .term]_Документ УД_ с подвидами:
[loweralpha]
.. [.dfn .term]_Входящий_ – предназначен для хранения в системе файлов входящей корреспонденции.
.. [.dfn .term]_Исходящий_ – предназначен для хранения в системе файлов исходящей корреспонденции.
.. [.dfn .term]_ОРД_ – предназначен для работы с внутренними организационно-распорядительными документами.
.. [.dfn .term]_Служебная записка_ – документ информационно-справочного характера, используемый для ведения деловой переписки внутри предприятия.
.. [.dfn .term]_Заявка_ – предназначен для хранения в системе файлов внутренней корреспонденции, используемых для отправки различных заявок.
.. [.dfn .term]_Рабочий_ – предназначен для выполнения произвольных задач документооборота. Использование документа предполагается внутри рабочих групп.
.. [.dfn .term]_Договор_ – предназначен для хранения данных о заключаемом договоре; с подвидами:
[lowerroman]
... [.dfn .term]_Акт_ – предназначен для хранения сведений об акте по договору.
... [.dfn .term]_Дополнительное соглашение_ – предназначен для хранения сведений о дополнительном соглашении.
. [.dfn .term]_Файл_ – предназначен для хранения файлов различных форматов.
. [.dfn .term]_Задание УД_ с подвидами:
[loweralpha]
.. [.dfn .term]_На исполнение_ – предназначен для отправки пользователю задания на исполнение.
.. [.dfn .term]_На ознакомление_ – предназначен для отправки пользователю задания на ознакомление.
. Подвиды [.dfn .term]_Задание КС / На консолидацию_:
[loweralpha]
.. [.dfn .term]_Согласование с контрагентом_ – предназначен для совершения операций с отдельным заданием по согласованию договорного документа с контрагентом; задание этого вида создается системой автоматически.
.. [.dfn .term]_Консолидация договора_ – предназначен для совершения операций с отдельным заданием по консолидации договорного документа в процессе его исполнения; задание этого вида создается системой автоматически.
. Группа заданий УД – предназначен для рассылки заданий группе пользователей.

*Parent topic:* xref:../topics/Structureof_program.adoc[Структура Приложения]
