= Настройка безопасности

[#create-admin]
== Назначение администраторов УД

_Администраторы УД_ -- группа пользователей, которым предоставлены дополнительные права (относительно других пользователей) на модификацию структуры папок Приложения, а также права на просмотр истории карточек УД.

Сравнение прав Администратора УД и рядового пользователя приведено в таблице ниже.

.Сравнение прав администратора УД и пользователя
[cols="50%,50%",options="header"]
|===
|Группа пользователей |Права
|*Права на общие папки*
a|.Администраторы УД:
* Полный доступ.
* Может создавать и менять настройки папок, включая настройки безопасности.

.Все пользователи:
* Создание карточек, просмотр атрибутов и настроек.
+
* Запрещены операции:
** Удаление общих папок.
** Изменение атрибутов и настроек безопасности.
* К папкам отчётов и поиска по категориям всем пользователям назначается доступ на чтение.

|*Шаблонная структура папок маршрутизации*
a|.Администраторы УД:
* Полный доступ.
* Может настраивать и менять атрибуты.

.Все пользователи:
* Только просмотр папок-делегатов.
|===

Администратор {dv} должен назначить _Администраторов УД_.

.Чтобы назначить "Администратора УД":
. Откройте {wincl} от имени администратора {dv}.
. Откройте _Справочник сотрудников_.
. Добавьте требуемого сотрудника в группу "Администраторы УД".
+
Если при включении пользователя в группу система выдала сообщение о нехватке прав, выдайте себе права на редактирование группы сотрудников _Администраторы УД_ по дискреционной модели.
include::partial$excerpts.adoc[tags=wincl]

[#designer-access]
== Настройка прав доступа на конструкторы и справочники

По умолчанию все пользователи {dv} имеют полные права на справочники и конструкторы: _Конструктор справочников_, _Справочник сотрудников_, _Справочник контрагентов_, _Справочник ссылок_, _Справочник категорий_, _Конструктор правил нумерации_.

Администратор {dv} должен самостоятельно настроить права доступа к справочникам и конструкторам: предоставить или ограничить доступ пользователей.

Права доступа настраиваются с помощью дискреционной модели безопасности.
include::partial$excerpts.adoc[tags=wincl]

[#wf-admin]
== Предоставление прав СУБП

Администратор {dv} должен добавить в _Справочник сотрудников_ технологического сотрудника, от имени которого сервис Workflow будет работать с карточками Приложения.

. Запустите {wincl} от имени администратора {dv}.
. Откройте _Справочник сотрудников_.
. Добавьте нового сотрудника, указав в поле `Пользователь` учетную запись сервиса Workflow (см. Руководство администратора_ модуля {wf}), и любое допустимое значение в поле `Фамилия` -- прочие данные можно не указывать.
. Предоставьте администратору {dv} права на редактирование группы сотрудников _Системная для WF_ по дискреционной модели безопасности.
include::partial$excerpts.adoc[tags=wincl]
. Добавьте созданного на шаге 3 сотрудника в группу _Системная для WF_.
+
Если для обработки БП используется кластер Workflow с разными учетными записями сервисов Workflow, создайте технологического сотрудника для каждой учетной записи СУБП.
