= Папка "Мои договоры"

Служебная папка маршрутизации _Мои договоры_ представляет собой структуру папок с настроенными поисковыми запросами, которая предназначена для:

* поиска карточек договоров в различных состояниях;
* контроля за ходом согласования договоров.

В _Личной_ папке пользователя, который может исполнять роли _Ответственный_ или _Подготовил_, администратор создает папку-делегат на _Мои договоры_. Данная папка включает несколько дочерних папок, предназначенных для поиска карточек в определенных состояниях.

== Описание папки "Мои договоры"

Мои договоры::
Назначение::
Новые договоры пользователя: договоры в состоянии `Подготовка`, _Ответственным_ или _Подготовившим_ которых является текущий пользователь или временно замещаемый им сотрудник.
Завершенные::
Назначение::
Карточки _Договор_ и _Дополнительное соглашение_ в состоянии `Завершен`.
 Группировка::
По договору.
Заключенные::
Назначение::
Карточки _Договор_ в состоянии `Заключен`, в которых текущий пользователь является _Ответственным_ или _Подготовившим_ и связанные с этими договорами карточки _Акт_ и _Дополнительное соглашения_ с любыми параметрами.
 Группировка::
По договору.
Подготовка и согласование::
Назначение::
Карточки _Договор_ в состоянии `Подготовка`, `На согласовании`, `На согласовании с контрагентом`, `Согласован`, `На подписании`, `Подписан`, `На подписании контрагентом`, в которых текущий пользователь является _Ответственным_ или _Подготовившим_.
 Группировка::
По состоянию.
