= Папка 'Договоры к ознакомлению'

Служебная папка маршрутизации *Договоры к ознакомлению* предназначена для сотрудников группы ознакомления. Она представляет собой структуру папок с настроенными поисковыми запросами, предназначенную для поиска карточек договоров, с которыми может ознакомиться текущий пользователь.

В _Личной_ папке пользователя может быть создана папка-делегат на папку *Договоры к ознакомлению*.

== Описание папки "Договоры к ознакомлению"

Договоры к ознакомлению::
  Назначение;;
    Физическая папка.
Заключенные::
  Назначение;;
    Карточки _Договор_ и _Дополнительное соглашение_ в состоянии `Заключен`, в которых текущий пользователь входит в [.keyword .parmname]_Группу ознакомления_ с договором.
  Сортировка;;
    По дате заключения.
Согласование::
  Назначение;;
    Карточки _Договор_ и _Дополнительное соглашение_ в состоянии `Подготовка`, `На согласовании`, `На согласовании с контрагентом`, в которых текущий пользователь входит в [.keyword .parmname]_Группу ознакомления_ с договором.

