[[ariaid-title1]]
== Папка «Договоры - Договорные документы»

Для работы с договорами предназначена группа папок [.keyword]*Договорные документы*.

В корневой папке данной группы предполагается создание пользователями карточек договорных документов различных видов, остальные папки группы – виртуальные, предназначены для отображения карточек договорных документов, отобранных по различным параметрам.

* [.keyword .parmname]_Действующие договоры_ – система виртуальных папок с договорами, отбираемыми по различным параметрам:
** [.keyword .parmname]_По контрагенту_ – действующие договоры, сгруппированные по контрагенту;
** [.keyword .parmname]_По сроку действия_ – действующие договоры, сгруппированные по сроку действия (по кварталам).
* [.keyword .parmname]_Заключенные договоры_ – система виртуальных папок с договорами по годам заключения.
** [.keyword .parmname]_2018 – договоры и дополнительные соглашения_ – договоры и дополнительные соглашения, заключенные в 2018 году и сгруппированные по контрагенту;
** [.keyword .parmname]_2019 – договоры и дополнительные соглашения_ – договоры и дополнительные соглашения, заключенные в 2019 году и сгруппированные по контрагенту.
+
[NOTE]
====
[.note__title]#Прим.:# Для договоров и дополнительных соглашений других годов предполагается создание аналогичных папок администратором.
====
* [.keyword .parmname]_Договоры с доп. соглашением_ – договоры и дополнительные соглашения, сгруппированные по договорам; при переходе в папку запрашивается интересующий период заключения договора.
* [.keyword .parmname]_Исполнение договоров_ – договоры и акты, сгруппированные по договорам; при переходе в папку запрашивается интересующий период заключения договора.
* [.keyword .parmname]_Поиск_ – папка для параметрического поиска договорного документа; при переходе в папку запрашиваются параметры, представленные на следующем рисунке.

*На уровень выше:* xref:../topics/Appendix_A.adoc[Приложение A. Папки приложения «Управление документами»]
