= Папка "Договоры -- Договорные документы"

Для работы с договорами предназначена группа папок *Договорные документы*.

В корневой папке данной группы предполагается создание пользователями карточек договорных документов различных видов, остальные папки группы -- виртуальные, предназначены для отображения карточек договорных документов, отобранных по различным параметрам.

* _Действующие договоры_ -- система виртуальных папок с договорами, отбираемыми по различным параметрам:
** _По контрагенту_ -- действующие договоры, сгруппированные по контрагенту;
** _По сроку действия_ -- действующие договоры, сгруппированные по сроку действия (по кварталам).
* _Заключенные договоры_ -- система виртуальных папок с договорами по годам заключения.
** _2018 -- договоры и дополнительные соглашения_ -- договоры и дополнительные соглашения, заключенные в 2018 году и сгруппированные по контрагенту;
** _2019 -- договоры и дополнительные соглашения_ -- договоры и дополнительные соглашения, заключенные в 2019 году и сгруппированные по контрагенту.
+
[NOTE]
====
Для договоров и дополнительных соглашений других годов предполагается создание аналогичных папок администратором.
====
* _Договоры с доп. соглашением_ -- договоры и дополнительные соглашения, сгруппированные по договорам; при переходе в папку запрашивается интересующий период заключения договора.
* _Исполнение договоров_ -- договоры и акты, сгруппированные по договорам; при переходе в папку запрашивается интересующий период заключения договора.
* _Поиск_ -- папка для параметрического поиска договорного документа; при переходе в папку запрашиваются параметры, представленные на следующем рисунке.
