[[ariaid-title1]]
== Папка 'Мои договоры'

Служебная папка маршрутизации [.keyword .parmname]_Мои договоры_ представляет собой структуру папок с настроенными поисковыми запросами, которая предназначена для:

* поиска карточек договоров в различных состояниях;
* контроля за ходом согласования договоров.

В [.dfn .term]_Личной_ папке пользователя, который может исполнять роли [.dfn .term]_Ответственный_ или [.dfn .term]_Подготовил_, администратор создает папку-делегат на [.keyword .parmname]_Мои договоры_. Данная папка включает несколько дочерних папок, предназначенных для поиска карточек в определенных состояниях.

=== Описание папки "Мои договоры"

Мои договоры::
  Назначение;;
    Новые договоры пользователя: договоры в состоянии `Подготовка`, [.keyword .parmname]_Ответственным_ или [.keyword .parmname]_Подготовившим_ которых является текущий пользователь или временно замещаемый им сотрудник.
Завершенные::
  Назначение;;
    Карточки [.dfn .term]_Договор_ и [.dfn .term]_Дополнительное соглашение_ в состоянии `Завершен`.
  Группировка;;
    По договору.
Заключенные::
  Назначение;;
    Карточки [.dfn .term]_Договор_ в состоянии `Заключен`, в которых текущий пользователь является [.keyword .parmname]_Ответственным_ или [.keyword .parmname]_Подготовившим_ и связанные с этими договорами карточки [.dfn .term]_Акт_ и [.dfn .term]_Дополнительное соглашения_ с любыми параметрами.
  Группировка;;
    По договору.
Подготовка и согласование::
  Назначение;;
    Карточки [.dfn .term]_Договор_ в состоянии `Подготовка`, `На согласовании`, `На согласовании с           контрагентом`, `Согласован`, `На           подписании`, `Подписан`, `На           подписании контрагентом`, в которых текущий пользователь является [.keyword .parmname]_Ответственным_ или [.keyword .parmname]_Подготовившим_.
  Группировка;;
    По состоянию.

*На уровень выше:* xref:../topics/Navigator_folders_DCmodul_personal.adoc[Личная папка пользователя]
