[[ariaid-title1]]
== Папка 'Договоры к ознакомлению'

Служебная папка маршрутизации [.keyword]*Договоры к ознакомлению* предназначена для сотрудников группы ознакомления. Она представляет собой структуру папок с настроенными поисковыми запросами, предназначенную для поиска карточек договоров, с которыми может ознакомиться текущий пользователь.

В [.dfn .term]_Личной_ папке пользователя может быть создана папка-делегат на папку [.keyword]*Договоры к ознакомлению*.

=== Описание папки "Договоры к ознакомлению"

Договоры к ознакомлению::
  Назначение;;
    Физическая папка.
Заключенные::
  Назначение;;
    Карточки [.dfn .term]_Договор_ и [.dfn .term]_Дополнительное соглашение_ в состоянии `Заключен`, в которых текущий пользователь входит в [.keyword .parmname]_Группу ознакомления_ с договором.
  Сортировка;;
    По дате заключения.
Согласование::
  Назначение;;
    Карточки [.dfn .term]_Договор_ и [.dfn .term]_Дополнительное соглашение_ в состоянии `Подготовка`, `На согласовании`, `На согласовании с контрагентом`, в которых текущий пользователь входит в [.keyword .parmname]_Группу ознакомления_ с договором.

*На уровень выше:* xref:../topics/Navigator_folders_DCmodul_personal.adoc[Личная папка пользователя]
