= Служебные группы

Приложение "{dm}" добавляет в систему {dv} служебные группы, перечисленные далее.

. "Администраторы УД".
+
Сотрудники, включенные в эту группу, имеют права на модификацию структуры папок "Управления документами", а также права на чтение и запись карточек заданий. Также сотрудники данной группы включаются в роль "Администратор УД".
. "Администраторы РГ".
+
Сотрудники, включенные в эту группу, имеют права на управление рабочими группами: создание/удаление, включение пользователей.
+
У пользователя, включенного в данную группу, в {wincl}е появится вкладка [.keyword .wintitle]*Рабочие группы*. Описание действий по управлению рабочими группами приведено в документе _Приложение "{dv} 5. {dm}". Руководство пользователя_.
. "Системная для WF".
+
Группа предназначена для обеспечения доступа к карточкам БП. В данную группу включается пользователь, под учетной записью которого запущен сервис Workflow.
. "Печать Договоров"
+
Группа, сотрудники которой получают задание распечатать бумажный оригинал согласованного договора перед началом его подписания в [.keyword .parmname]_демонстрационном маршруте согласования_.
. "Согласование Договоров"
+
Группа сотрудников, которым будут рассылаться задания на согласование договорных документов при использовании [.keyword .parmname]_демонстрационного маршрута согласования_.
. "Чтение всех договоров" -- группа, сотрудники которой получают возможность создания отчетов по договорным документам.

