= Настройка автоматического завершения и отзыва подчиненных заданий и групп заданий

Администратор {dv} может настроить поведение подчиненных заданий и групп заданий при завершении и отзыве родительского задания.

. Откройте _Справочник видов карточек_.
. Выберите в поле _Тип карточки_ значение *_Задание_*.
. Выберите в перечне видов нужный вид задания.
. Перейдите на вкладку _Подчиненное задание_.
. В области _Поведение подчинённых заданий при отзыве_ выберите вариант завершения подчиненных заданий при отзыве родительского:
+
* Не менять -- состояние подчиненных заданий не будет изменяться.
* Отозвать -- подчиненные задания будут отзываться.
* Удалить -- подчиненные задания будут удаляться.
+
. Аналогичным образом на вкладке _Подчиненная группа заданий_ настройте поведение подчиненных групп задания при отзыве родительского задания.
. Перейдите на вкладку _Завершение задания_.
. Установите флаг `*При завершении задания автоматически завершать подчиненные группы заданий*`, чтобы при завершении родительского задания автоматически завершались все подчиненные группы заданий (фактически завершаются задания из групп).
. Установите флаг `*При завершении задания автоматически завершать подчиненные задания*`, чтобы при завершении родительского задания автоматически завершались все подчиненные задания.
