[[ariaid-title1]]
== Настройка способа создания связанных карточек

С карточкой договора могут быть связаны другие карточки. Например, из карточки договора может быть создана связанная карточка дополнительного соглашения или акта.

Добавить связанную карточку можно либо на вкладке [.keyword]*Связи* карточки, либо при помощи специальной команды ленты [.keyword]*Создание карточки*. Использование команды ленты позволяет упросить создание наиболее часто используемых видов связанных карточек, но требует от администратора дополнительной настройки вида в [.dfn .term]_Справочнике видов карточек_.

Для вида карточки [.dfn .term]_Договор_ настроены следующие режимы создания связанных карточек:

* xref:task_Mode_Creating_Doc_in_SuppAgreement.adoc[Акт].
* xref:task_Mode_Creating_Doc_in_Act.adoc[Доп. соглашение];
* xref:task_Mode_Creating_Doc_in_SuppAgreement_prolongation.adoc[Доп. соглашение о продлении сроков];

Используя эти способы создания, администратор Docsvision может определить другие способы создания связанных карточек договорных документов.

* *xref:../topics/task_Mode_Creating_Doc_in_Act.adoc[Способ создания «Акт»]* +
* *xref:../topics/task_Mode_Creating_Doc_in_SuppAgreement.adoc[Способ создания «Доп. соглашение»]* +
* *xref:../topics/task_Mode_Creating_Doc_in_SuppAgreement_prolongation.adoc[Способ создания «Доп. соглашение о продлении сроков»]* +

*На уровень выше:* xref:../topics/ConfigurationToWorkWithContracts.adoc[Функции администратора при работе с договорами]
