= Папки

Приложение "{dm}" добавляет в систему {dv} папки:

. "Документы" -- содержит набор подпапок, каждая из которых предназначена для работы с определенным подвидом карточек вида _ДокументУД_.
. "Отчеты" -- содержит виртуальные папки, позволяющие получить документы, находящиеся на подписании, на согласовании, и задания за период времени, к исполнению.
. "Служебные" -- доступная только администратору {dv} папка со служебными подпапками:
* "Бизнес-календарь" -- папка для хранения бизнес-календарей;
* "Бизнес-процессы" -- папка для хранения бизнес-процессов, используемых для работы специализированных карточек приложения;
* "Маршрутизация" -- папка для хранения структурированных папок с настроенными поисковыми запросами;
* "Предустановки согласования" -- содержит шаблоны БП согласования.
. "Договоры" -- содержит папки, используемые при работе с договорами:
* "Договорные документы" -- папка, предназначенная для создания карточек договорных документов;
* "Отчеты" -- папка для хранения отчетов по договорным документам;
* "Служебные" -- папки для хранения административных настроек приложения. Данные папки доступны администратору приложения.

Набор отображаемых папок зависит от прав пользователя.

Параметры папок перечислены в xref:Appendix_A.adoc[Приложении A].

