[[ariaid-title1]]
== Папка «Отчеты»

Для работы с отчетами в Приложении предназначена группа папок [.ph .filepath]`Отчеты` с виртуальными папками:

* [.keyword]*Документы на подписании* – для поиска документов всех видов, находящиеся в состоянии `На подписании`, доступные роли текущего пользователя, за указанный период;
* [.keyword]*Документы на согласовании* – для поиска документов всех видов, находящиеся в состоянии `На согласовании`, доступные роли текущего пользователя, за указанный период;
* [.keyword]*Задания за период* – для поиска заданий, доступные роли текущего пользователя, за указанный период;
* [.keyword]*Задания к исполнению* – для поиска заданий, доступные роли текущего пользователя, во всех состояниях, кроме `Подготовка` и `Завершено`.

Для работы с отчетами по договорам предназначена группа папок [.ph .filepath]`Договоры/Отчеты` с виртуальными папками:

* [.keyword]*Договоры и ДС без подписанного оригинала* – для поиска карточек договоров и дополнительных соглашений в состояниях `Подписан` и `Заключен`, для которых отсутствует подписанный оригинал (в карточке не заполнено поле [.keyword]*Получен оригинал*).
* [.keyword]*Договоры с истекающим сроком окончания* – для поиска карточек договоров в состояниях `Подписан` и `Заключен`, у которых заканчивается срок действия.

*На уровень выше:* xref:../topics/Appendix_A.adoc[Приложение A. Папки приложения «Управление документами»]
