= Папка "Отчеты"

Для работы с отчетами в Приложении предназначена группа папок `Отчеты` с виртуальными папками:

* *Документы на подписании* -- для поиска документов всех видов, находящиеся в состоянии `На подписании`, доступные роли текущего пользователя, за указанный период;
* *Документы на согласовании* -- для поиска документов всех видов, находящиеся в состоянии `На согласовании`, доступные роли текущего пользователя, за указанный период;
* *Задания за период* -- для поиска заданий, доступные роли текущего пользователя, за указанный период;
* *Задания к исполнению* -- для поиска заданий, доступные роли текущего пользователя, во всех состояниях, кроме `Подготовка` и `Завершено`.

Для работы с отчетами по договорам предназначена группа папок `Договоры/Отчеты` с виртуальными папками:

* *Договоры и ДС без подписанного оригинала* -- для поиска карточек договоров и дополнительных соглашений в состояниях `Подписан` и `Заключен`, для которых отсутствует подписанный оригинал (в карточке не заполнено поле *Получен оригинал*).
* *Договоры с истекающим сроком окончания* -- для поиска карточек договоров в состояниях `Подписан` и `Заключен`, у которых заканчивается срок действия.
