= Роли

Приложение "{dm}" добавляет в систему {dv} пользовательские роли для работы с документами.

. Общие роли:
* Администратор УД -- сотрудники включенные в группу "Администраторы УД". Данной роли предоставляется разрешение на операцию "Просмотр истории".
* Системная для WF -- сотрудники включенные в группу "Системная для WF ". Роль предназначена для предоставления доступа к карточкам системному пользователю, от имени которого СУБП (Workflow) работает с {dv}.
. Роли карточек вида _Документ УД_:
[loweralpha]
.. Регистратор -- сотрудник, создавший документ в системе.
.. Все руководители -- руководитель и его заместители для регистратора и участников согласования.
.. Участник задания с отчетом -- Автор, Контролер или Исполнитель задания, к которому данный документ приложен в качестве отчета. Роль предоставляет право на чтение документа-отчета.
.. Участник задания по документу -- Автор, Контролер или Исполнитель задания по документу (включая подчиненные), а также все их заместители (постоянные и временные). Также используется для назначения прав доступа участникам согласования по документу.
.. Участник рабочей группы -- сотрудник, входящий в состав рабочей группы _Справочника сотрудников_, указанной в поле *Рабочая группа*. Роль открывает доступ на чтение карточек сотрудникам, входящим в состав группы. Данная роль используется только в виде _Документ УД/Рабочий_.
. Роли карточек вида _Договор_:
[loweralpha]
.. Группа ознакомления -- сотрудники, имеющие право на чтение карточки договора; определяется через принадлежность к Группе договора в Конструкторе справочников.
.. Все руководители -- сотрудники, являющиеся руководителями лиц, участвующих в карточке Договор и имеющие право на ее чтение.
.. Подготовил -- сотрудник, инициирующий все действия с договором. Как правило является помощником Ответственного лица.
.. Ответственный -- сотрудник, ответственный за договор. При работе с приложением имеет те же права, что и роль "Подготовил".
.. Участник согласования -- сотрудник, участвующий в согласовании и подписании договора.
.. Участник задания по документу -- сотрудник, исполняющий роль в задании, созданном из карточки договора.
.. Чтение всех договоров -- сотрудники, имеющие право на чтение карточки договора; определяется через принадлежность к группе "Чтение всех договоров". Роль используется для создания отчетов по договорным документам.
. Роли карточек вида _Договор -- Акт_:
[loweralpha]
.. Подготовил -- сотрудник, инициирующий все действия с актом. Как правило является помощником Ответственного лица.
.. Ответственный -- сотрудник, ответственный за акт. При работе с приложением имеет те же права, что и роль "Подготовил".
.. Все руководители -- сотрудники, являющиеся руководителями лиц, участвующих в карточке Акт и имеющие право на ее чтение.
.. Участник задания по документу -- сотрудник, исполняющий роль в задании, созданном из карточки акта.
. Роли карточек вида _Договор -- Дополнительное соглашение_:
[loweralpha]
.. Подготовил -- сотрудник, инициирующий все действия с дополнительным соглашением. Как правило является помощником Ответственного лица.
.. Ответственный -- сотрудник, ответственный за дополнительное соглашение. При работе с приложением имеет те же права, что и роль "Подготовил".
.. Группа ознакомления с дополнительным соглашением -- сотрудники, имеющие право на чтение карточки дополнительного соглашения; определяется через принадлежность к "Группе договора" в Конструкторе справочников.
.. Все руководители -- сотрудники, являющиеся руководителями лиц, участвующих в карточке Дополнительное соглашение и имеющие право на ее чтение.
.. Участник согласования -- сотрудник, участвующий в согласовании и подписании дополнительного соглашения.
.. Участник задания по документу -- сотрудник, исполняющий роль в задании, созданном из карточки дополнительного соглашения.
.. Чтение всех договоров -- сотрудники, имеющие право на чтение карточки договора; определяется через принадлежность к группе "Чтение всех договоров" в Справочнике сотрудников. Роль используется для создания отчетов по договорным документам.
. Роли карточек вида _Задание УД_:
[loweralpha]
.. Автор -- сотрудник, указанный в поле [.ph .uicontrol]*Автор*, а также его постоянные/временные заместители.
.. Исполнитель -- текущий исполнитель задания, а также его постоянные/временные заместители.
.. Делегировавший -- сотрудник, когда-либо выполнявший делегирование задания.
.. Контролер -- сотрудник, указанный в поле [.ph .uicontrol]*Контролёр*, а также его постоянные/временные заместители.
.. Все руководители -- руководители и заместители руководителей текущих Исполнителей или Автора задания.
.. Ответственный исполнитель -- сотрудник, отвечающий за исполнение заданий группы заданий, может завершать задания других исполнителей, осуществлять контроль и приемку. Роль используется только в заданиях, сформированных при помощи Группы заданий.
.. Автор, исполнитель или контролер родительского задания -- сотрудник-участник родительского задания, роль используется для доступа к дочерним заданиям из родительских.
+
В заданиях "На исполнение" используются роли: "Автор", "Автор, исполнитель или контролер родительского задания", "Все руководители", "Делегировавший", "Исполнитель", "Контролер", "Ответственный исполнитель".
+
В заданиях "На ознакомление" используются роли: "Автор", "Автор, исполнитель или контролер родительского задания", "Все руководители", "Исполнитель".
. Роли карточек вида _Группа заданий УД_:
* Автор -- сотрудник, указанный в поле [.ph .uicontrol]*Автор*, по умолчанию -- текущий сотрудник;
* Читатель -- сотрудник, который может открыть карточку на чтение (Исполнитель задания Группы заданий);
* Ответственный исполнитель -- один из пользователей с ролью Исполнитель, имеющий доступ к заданиям остальных исполнителей, с возможностью изменения сроков выполнения, отзыва и завершения заданий.

*Parent topic:* xref:../topics/Structureof_program.adoc[Структура Приложения]
