= Настройка согласования

Для настройки маршрутов согласования договоров должен быть установлен модуль "{dv} 5. {ad}".

В Приложение входит _демонстрационный процесс согласования_, сценарий которого включает основные этапы типового согласования договорных документов предприятия.

Для работы _демонстрационного процесса согласования_ настроены следующие объекты:

* маршрут согласования xref:Route_Contracts_Approvement.html[*Согласование договоров*];
* этапы согласования, включенные в маршрут:
** xref:Stage_approvment_inside_company.html[*Согласование внутри организации*];
** xref:Stage_approved_our_side.html[*Согласовано с нашей стороны*];
** xref:Stage_not_approved_our_side.html[*Не согласовано с нашей стороны*];
** xref:Stage_approvment_partner.html[*Согласование с контрагентом*];
** xref:Stage_print.html[*Печать*];
** xref:Stage_signing.html[*Подписание*];
** xref:Stage_sign_finished.html[*Завершен этап подписания*];
* шаблон согласования *Согласование*

Для проведения согласования при помощи данного маршрута, необходимо предварительно включить сотрудников в служебные группы *Согласование договоров* и *Печать договоров* (см. xref:Settings_Security_Reference_Employees.adoc[Включение сотрудников в группы "Согласование Договоров" и "Печать договоров"]).
