[[ariaid-title1]]
== Этап «Согласовано с нашей стороны»

Этап [.keyword]*Согласовано c нашей стороны* маршрута [.keyword]*Согласование договоров* предназначен для демонстрации сценария консолидации - подготовки итогового документа по результатам согласования внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: [.keyword]*Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: [.keyword]*Последовательное*;
** [.keyword .parmname]_Согласующие_: [.keyword]*Инициатор* (использовать значение из поля карточки [.keyword]*С нашей стороны>Подготовил*).
* настройки заданий:
** [.keyword .parmname]_Вид_: [.keyword]*Консолидация договора*;
** [.keyword .parmname]_Варианты решений_: [.keyword]*На подписание*, [.keyword]*На согласование с контрагентом*, [.keyword]*Отменить*;
** [.keyword .parmname]_Содержание_: [.keyword]*Договор согласован с нашей стороны. При необходимости учтите замечания и инициируйте согласование с контрагентом*;
** [.keyword .parmname]_Уровень дерева версий_: [.keyword]*Процесс*;
** [.keyword .parmname]_Длительность указана для этапа_: [.keyword]*24*
** [.keyword .parmname]_Автосогласование_: [.keyword]*Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа [.keyword]*согласован* при отрицательном результате настроено состояние [.keyword]*На согласовании*.

*На уровень выше:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут «Согласование договоров»]
