= Этап "Не согласовано с нашей стороны"

Этап *Не согласовано c нашей стороны* маршрута *Согласование договоров* предназначен для демонстрации сценария повторного согласования внутри организации и консолидации -- подготовки итогового документа по результатам согласования внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** _Режим_: *Консолидация*;
** _Тип маршрутизации_: *Последовательное*;
** _Согласующие_: *Инициатор* (использовать значение из поля карточки *С нашей стороны>Подготовил*).
* настройки заданий:
** _Вид_: *Консолидация договора*;
** _Варианты решений_: *Отмена*, *Повторить согласование*;
** _Содержание_: *Этап согласования с нашей стороны завершился отрицательно. Примите решение о продолжении согласования.*;
** _Уровень дерева версий_: *Процесс*;
** _Длительность указана для этапа_: *0*
** _Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** _Семантика завершения этапа по умолчанию_: *Положительное*.
