[[ariaid-title1]]
== Этап «Печать»

Этап [.keyword]*Печать* маршрута [.keyword]*Согласование договоров* предназначен для демонстрации сценария печати бумажного экземпляра документа.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: [.keyword]*Согласование*;
** [.keyword .parmname]_Тип маршрутизации_: [.keyword]*Альтернативное*;
** [.keyword .parmname]_Согласующие_: использовать значение из группы [.keyword]*Печать договоров*.
* настройки заданий:
** [.keyword .parmname]_Вид_: [.keyword]*На подписание*;
** [.keyword .parmname]_Варианты решений_: [.keyword]*Распечатано*;
** установлен флаг [.keyword]*Не добавлять решение в Лист согласования*;
** [.keyword .parmname]_Содержание_: [.keyword]*Распечатайте, пожалуйста, приложенные файлы для подписания Договора.*;
** [.keyword .parmname]_Уровень дерева версий_: [.keyword]*Этап*;
** [.keyword .parmname]_Автосогласование_: [.keyword]*Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_ для состояния этапа [.keyword]*на подписании* при отрицательном результате настроено состояние [.keyword]*На подписании*.
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: [.keyword]*Положительное*.

*На уровень выше:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут «Согласование договоров»]
