= Этап "Согласовано с нашей стороны"

Этап *Согласовано c нашей стороны* маршрута *Согласование договоров* предназначен для демонстрации сценария консолидации - подготовки итогового документа по результатам согласования внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** _Режим_: *Консолидация*;
** _Тип маршрутизации_: *Последовательное*;
** _Согласующие_: *Инициатор* (использовать значение из поля карточки *С нашей стороны>Подготовил*).
* настройки заданий:
** _Вид_: *Консолидация договора*;
** _Варианты решений_: *На подписание*, *На согласование с контрагентом*, *Отменить*;
** _Содержание_: *Договор согласован с нашей стороны. При необходимости учтите замечания и инициируйте согласование с контрагентом*;
** _Уровень дерева версий_: *Процесс*;
** _Длительность указана для этапа_: *24*
** _Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** _Матрица состояний_: для видов _Договор_, _Дополнительное соглашение_ для состояния этапа *согласован* при отрицательном результате настроено состояние *На согласовании*.
