= Этап "Согласование внутри организации"

Этап *Согласование внутри организации* маршрута *Согласование договоров* предназначен для демонстрации сценария согласования внутри собственной организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** _Режим_: *Согласование*;
** _Тип маршрутизации_: *Параллельное*;
** _Согласующие_: использовать значение из группы *Согласование договоров*.
* настройки заданий:
** _Вид_: *На согласование*;
** _Варианты решений_: *Согласовано*, *Согласовано с замечаниями*, *Не согласовано*;
** _Содержание_: *Примите, пожалуйста, участие в согласовании договорного документа. Файлы для согласования приложены к данному заданию.*;
** _Уровень дерева версий_: *Этап*;
** _Длительность указана для этапа_: *0*
** _Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** _Матрица состояний_: для видов _Договор_, _Дополнительное соглашение_ для состояния этапа *на согласовании* при отрицательном решении настроен результат *На согласовании*.
