= Этап "Согласование с контрагентом"

Этап *Согласование с контрагентом* маршрута *Согласование договоров* предназначен для демонстрации сценария согласования с контрагентом.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** _Режим_: *Консолидация*;
** _Тип маршрутизации_: *Последовательное*;
** _Согласующие_: использовать значение из поля карточки *С нашей стороны>Ответственный*.
* настройки заданий:
** _Вид_: *Согласование с контрагентом*;
** _Варианты решений_: *Согласован и подписан контрагентом*, *Согласован контрагентом*, *Отмена*, *Повторить согласование*;
** _Содержание_: *Согласуйте, пожалуйста, приложенные файлы с Контрагентом. Результат зафиксируйте с помощью кнопок в ленте команд.*;
** _Уровень дерева версий_: *Этап*;
** _Длительность указана для этапа_: *72*
** _Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** _Матрица состояний_: для видов _Договор_, _Дополнительное соглашение_ для состояния этапа *на согласовании контрагентом* при отрицательном результате настроено состояние *Согласован*.
** _Семантика завершения этапа по умолчанию_: *Положительное*.
