= Этап "Печать"

Этап *Печать* маршрута *Согласование договоров* предназначен для демонстрации сценария печати бумажного экземпляра документа.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: *Согласование*;
** [.keyword .parmname]_Тип маршрутизации_: *Альтернативное*;
** [.keyword .parmname]_Согласующие_: использовать значение из группы *Печать договоров*.
* настройки заданий:
** [.keyword .parmname]_Вид_: *На подписание*;
** [.keyword .parmname]_Варианты решений_: *Распечатано*;
** установлен флаг *Не добавлять решение в Лист согласования*;
** [.keyword .parmname]_Содержание_: *Распечатайте, пожалуйста, приложенные файлы для подписания Договора.*;
** [.keyword .parmname]_Уровень дерева версий_: *Этап*;
** [.keyword .parmname]_Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_ для состояния этапа *на подписании* при отрицательном результате настроено состояние *На подписании*.
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: *Положительное*.

