= Этап "Подписание"

Этап *Подписание* маршрута *Согласование договоров* предназначен для демонстрации сценария подписания документа внутри собственной организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: *Согласование*;
** [.keyword .parmname]_Тип маршрутизации_: *Параллельное*;
** [.keyword .parmname]_Согласующие_: использовать значение из поля карточки *Подписанты>Подписано*.
* настройки заданий:
** [.keyword .parmname]_Вид_: *На подписание*;
** [.keyword .parmname]_Варианты решений_: *Подписано*, *Отказано в подписании*;
** [.keyword .parmname]_Содержание_: *Подпишите, пожалуйста, документ.*;
** [.keyword .parmname]_Уровень дерева версий_: *Этап*;
** [.keyword .parmname]_Длительность указана для задания_: *24*
** [.keyword .parmname]_Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа *на подписании* при отрицательном результате настроено состояние *на подписании*.
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: *Положительное*.

*Parent topic:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут "Согласование договоров"]
