= Этап "Завершен этап подписания"

Этап *Завершен этап подписания* маршрута *Согласование договоров* предназначен для демонстрации сценария консолидации -- создания итогового документа по итогам подписания внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** _Режим_: *Консолидация*;
** _Тип маршрутизации_: *Последовательное*;
** _Согласующие_: *Инициатор* (использовать значение из поля карточки *С нашей стороны>Подготовил*).
* настройки заданий:
** _Вид_: *Консолидация договора*;
** _Варианты решений_: *Завершить маршрут*, *На согласование с контрагентом*, *Повторить согласование*, *Отмена*;
** _Содержание_: *Завершен этап подписания с нашей стороны. Необходимо принять решение о продолжении или завершении маршрута согласования.*;
** _Уровень дерева версий_: *Процесс*;
** _Длительность указана для этапа_: *24*
** _Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** _Семантика завершения этапа по умолчанию_: *Положительное*.
