= Этап "Согласование с контрагентом"

Этап *Согласование с контрагентом* маршрута *Согласование договоров* предназначен для демонстрации сценария согласования с контрагентом.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: *Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: *Последовательное*;
** [.keyword .parmname]_Согласующие_: использовать значение из поля карточки *С нашей стороны>Ответственный*.
* настройки заданий:
** [.keyword .parmname]_Вид_: *Согласование с контрагентом*;
** [.keyword .parmname]_Варианты решений_: *Согласован и подписан контрагентом*, *Согласован контрагентом*, *Отмена*, *Повторить согласование*;
** [.keyword .parmname]_Содержание_: *Согласуйте, пожалуйста, приложенные файлы с Контрагентом. Результат зафиксируйте с помощью кнопок в ленте команд.*;
** [.keyword .parmname]_Уровень дерева версий_: *Этап*;
** [.keyword .parmname]_Длительность указана для этапа_: *72*
** [.keyword .parmname]_Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа *на согласовании контрагентом* при отрицательном результате настроено состояние *Согласован*.
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: *Положительное*.

