[[ariaid-title1]]
== Этап «Согласование с контрагентом»

Этап [.keyword]*Согласование с контрагентом* маршрута [.keyword]*Согласование договоров* предназначен для демонстрации сценария согласования с контрагентом.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: [.keyword]*Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: [.keyword]*Последовательное*;
** [.keyword .parmname]_Согласующие_: использовать значение из поля карточки [.keyword]*С нашей стороны>Ответственный*.
* настройки заданий:
** [.keyword .parmname]_Вид_: [.keyword]*Согласование с контрагентом*;
** [.keyword .parmname]_Варианты решений_: [.keyword]*Согласован и подписан контрагентом*, [.keyword]*Согласован контрагентом*, [.keyword]*Отмена*, [.keyword]*Повторить согласование*;
** [.keyword .parmname]_Содержание_: [.keyword]*Согласуйте, пожалуйста, приложенные файлы с Контрагентом. Результат зафиксируйте с помощью кнопок в ленте команд.*;
** [.keyword .parmname]_Уровень дерева версий_: [.keyword]*Этап*;
** [.keyword .parmname]_Длительность указана для этапа_: [.keyword]*72*
** [.keyword .parmname]_Автосогласование_: [.keyword]*Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа [.keyword]*на согласовании контрагентом* при отрицательном результате настроено состояние [.keyword]*Согласован*.
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: [.keyword]*Положительное*.

*На уровень выше:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут «Согласование договоров»]
