= Этап "Согласование внутри организации"

Этап *Согласование внутри организации* маршрута *Согласование договоров* предназначен для демонстрации сценария согласования внутри собственной организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: *Согласование*;
** [.keyword .parmname]_Тип маршрутизации_: *Параллельное*;
** [.keyword .parmname]_Согласующие_: использовать значение из группы *Согласование договоров*.
* настройки заданий:
** [.keyword .parmname]_Вид_: *На согласование*;
** [.keyword .parmname]_Варианты решений_: *Согласовано*, *Согласовано с замечаниями*, *Не согласовано*;
** [.keyword .parmname]_Содержание_: *Примите, пожалуйста, участие в согласовании договорного документа. Файлы для согласования приложены к данному заданию.*;
** [.keyword .parmname]_Уровень дерева версий_: *Этап*;
** [.keyword .parmname]_Длительность указана для этапа_: *0*
** [.keyword .parmname]_Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа *на согласовании* при отрицательном решении настроен результат *На согласовании*.

