= Этап "Согласовано с нашей стороны"

Этап *Согласовано c нашей стороны* маршрута *Согласование договоров* предназначен для демонстрации сценария консолидации - подготовки итогового документа по результатам согласования внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: *Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: *Последовательное*;
** [.keyword .parmname]_Согласующие_: *Инициатор* (использовать значение из поля карточки *С нашей стороны>Подготовил*).
* настройки заданий:
** [.keyword .parmname]_Вид_: *Консолидация договора*;
** [.keyword .parmname]_Варианты решений_: *На подписание*, *На согласование с контрагентом*, *Отменить*;
** [.keyword .parmname]_Содержание_: *Договор согласован с нашей стороны. При необходимости учтите замечания и инициируйте согласование с контрагентом*;
** [.keyword .parmname]_Уровень дерева версий_: *Процесс*;
** [.keyword .parmname]_Длительность указана для этапа_: *24*
** [.keyword .parmname]_Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа *согласован* при отрицательном результате настроено состояние *На согласовании*.

