= Этап "Завершен этап подписания"

Этап *Завершен этап подписания* маршрута *Согласование договоров* предназначен для демонстрации сценария консолидации - создания итогового документа по итогам подписания внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: *Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: *Последовательное*;
** [.keyword .parmname]_Согласующие_: *Инициатор* (использовать значение из поля карточки *С нашей стороны>Подготовил*).
* настройки заданий:
** [.keyword .parmname]_Вид_: *Консолидация договора*;
** [.keyword .parmname]_Варианты решений_: *Завершить маршрут*, *На согласование с контрагентом*, *Повторить согласование*, *Отмена*;
** [.keyword .parmname]_Содержание_: *Завершен этап подписания с нашей стороны. Необходимо принять решение о продолжении или завершении маршрута согласования.*;
** [.keyword .parmname]_Уровень дерева версий_: *Процесс*;
** [.keyword .parmname]_Длительность указана для этапа_: *24*
** [.keyword .parmname]_Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: *Положительное*.

