[[ariaid-title1]]
== Этап «Подписание»

Этап [.keyword]*Подписание* маршрута [.keyword]*Согласование договоров* предназначен для демонстрации сценария подписания документа внутри собственной организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: [.keyword]*Согласование*;
** [.keyword .parmname]_Тип маршрутизации_: [.keyword]*Параллельное*;
** [.keyword .parmname]_Согласующие_: использовать значение из поля карточки [.keyword]*Подписанты>Подписано*.
* настройки заданий:
** [.keyword .parmname]_Вид_: [.keyword]*На подписание*;
** [.keyword .parmname]_Варианты решений_: [.keyword]*Подписано*, [.keyword]*Отказано в подписании*;
** [.keyword .parmname]_Содержание_: [.keyword]*Подпишите, пожалуйста, документ.*;
** [.keyword .parmname]_Уровень дерева версий_: [.keyword]*Этап*;
** [.keyword .parmname]_Длительность указана для задания_: [.keyword]*24*
** [.keyword .parmname]_Автосогласование_: [.keyword]*Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа [.keyword]*на подписании* при отрицательном результате настроено состояние [.keyword]*на подписании*.
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: [.keyword]*Положительное*.

*Parent topic:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут «Согласование договоров»]
