[[ariaid-title1]]
== Этап «Завершен этап подписания»

Этап [.keyword]*Завершен этап подписания* маршрута [.keyword]*Согласование договоров* предназначен для демонстрации сценария консолидации - создания итогового документа по итогам подписания внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: [.keyword]*Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: [.keyword]*Последовательное*;
** [.keyword .parmname]_Согласующие_: [.keyword]*Инициатор* (использовать значение из поля карточки [.keyword]*С нашей стороны>Подготовил*).
* настройки заданий:
** [.keyword .parmname]_Вид_: [.keyword]*Консолидация договора*;
** [.keyword .parmname]_Варианты решений_: [.keyword]*Завершить маршрут*, [.keyword]*На согласование с контрагентом*, [.keyword]*Повторить согласование*, [.keyword]*Отмена*;
** [.keyword .parmname]_Содержание_: [.keyword]*Завершен этап подписания с нашей стороны. Необходимо принять решение о продолжении или завершении маршрута согласования.*;
** [.keyword .parmname]_Уровень дерева версий_: [.keyword]*Процесс*;
** [.keyword .parmname]_Длительность указана для этапа_: [.keyword]*24*
** [.keyword .parmname]_Автосогласование_: [.keyword]*Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: [.keyword]*Положительное*.

*На уровень выше:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут «Согласование договоров»]
