[[ariaid-title1]]
== Этап «Согласование внутри организации»

Этап [.keyword]*Согласование внутри организации* маршрута [.keyword]*Согласование договоров* предназначен для демонстрации сценария согласования внутри собственной организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: [.keyword]*Согласование*;
** [.keyword .parmname]_Тип маршрутизации_: [.keyword]*Параллельное*;
** [.keyword .parmname]_Согласующие_: использовать значение из группы [.keyword]*Согласование договоров*.
* настройки заданий:
** [.keyword .parmname]_Вид_: [.keyword]*На согласование*;
** [.keyword .parmname]_Варианты решений_: [.keyword]*Согласовано*, [.keyword]*Согласовано с замечаниями*, [.keyword]*Не согласовано*;
** [.keyword .parmname]_Содержание_: [.keyword]*Примите, пожалуйста, участие в согласовании договорного документа. Файлы для согласования приложены к данному заданию.*;
** [.keyword .parmname]_Уровень дерева версий_: [.keyword]*Этап*;
** [.keyword .parmname]_Длительность указана для этапа_: [.keyword]*0*
** [.keyword .parmname]_Автосогласование_: [.keyword]*Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Матрица состояний_: для видов [.keyword .parmname]_Договор_, [.keyword .parmname]_Дополнительное соглашение_ для состояния этапа [.keyword]*на согласовании* при отрицательном решении настроен результат [.keyword]*На согласовании*.

*На уровень выше:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут «Согласование договоров»]
