= Этап "Не согласовано с нашей стороны"

Этап *Не согласовано c нашей стороны* маршрута *Согласование договоров* предназначен для демонстрации сценария повторного согласования внутри организации и консолидации - подготовки итогового документа по результатам согласования внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: *Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: *Последовательное*;
** [.keyword .parmname]_Согласующие_: *Инициатор* (использовать значение из поля карточки *С нашей стороны>Подготовил*).
* настройки заданий:
** [.keyword .parmname]_Вид_: *Консолидация договора*;
** [.keyword .parmname]_Варианты решений_: *Отмена*, *Повторить согласование*;
** [.keyword .parmname]_Содержание_: *Этап согласования с нашей стороны завершился отрицательно. Примите решение о продолжении согласования.*;
** [.keyword .parmname]_Уровень дерева версий_: *Процесс*;
** [.keyword .parmname]_Длительность указана для этапа_: *0*
** [.keyword .parmname]_Автосогласование_: *Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: *Положительное*.

