[[ariaid-title1]]
== Этап «Не согласовано с нашей стороны»

Этап [.keyword]*Не согласовано c нашей стороны* маршрута [.keyword]*Согласование договоров* предназначен для демонстрации сценария повторного согласования внутри организации и консолидации - подготовки итогового документа по результатам согласования внутри организации.

Для данного этапа настроены следующие параметры:

* параметры этапа:
** [.keyword .parmname]_Режим_: [.keyword]*Консолидация*;
** [.keyword .parmname]_Тип маршрутизации_: [.keyword]*Последовательное*;
** [.keyword .parmname]_Согласующие_: [.keyword]*Инициатор* (использовать значение из поля карточки [.keyword]*С нашей стороны>Подготовил*).
* настройки заданий:
** [.keyword .parmname]_Вид_: [.keyword]*Консолидация договора*;
** [.keyword .parmname]_Варианты решений_: [.keyword]*Отмена*, [.keyword]*Повторить согласование*;
** [.keyword .parmname]_Содержание_: [.keyword]*Этап согласования с нашей стороны завершился отрицательно. Примите решение о продолжении согласования.*;
** [.keyword .parmname]_Уровень дерева версий_: [.keyword]*Процесс*;
** [.keyword .parmname]_Длительность указана для этапа_: [.keyword]*0*
** [.keyword .parmname]_Автосогласование_: [.keyword]*Семантика завершения задания: Положительное*.
* дополнительные настройки:
** [.keyword .parmname]_Семантика завершения этапа по умолчанию_: [.keyword]*Положительное*.

*На уровень выше:* xref:../topics/Route_Contracts_Approvement.adoc[Маршрут «Согласование договоров»]
