[[ariaid-title1]]
== Настройка состояний

Настройка состояний может потребоваться при создании собственных решений на платформе Docsvision. При настройке состояний имеется ряд особенностей, которые следует учитывать при проектировании.

=== Настройка состояний для использования параметров завершения заданий

Для использования параметров завершения заданий требуется, чтобы в [.dfn .term]_Конструкторе состояний_ при переходе из одного состояния в другое была определена [.dfn .term]_основная_ ветка перехода (см. [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_#), так как варианты завершения работают только для основной ветки перехода. Если доступных переходов окажется несколько, а ветка перехода не будет конкретизирована, задание будет завершено без применения параметров завершения.

* *xref:../topics/EditOperations_DocUD.adoc[Операции редактирования карточек 'ДокументУД']* +
* *xref:../topics/EditOperations_TaskUD.adoc[Операции редактирования карточек 'ЗаданиеУД']* +

*На уровень выше:* xref:../topics/Administrator_functions.adoc[Функции администратора]
