[[ariaid-title1]]
== Структура Приложения

Приложение «Управление документами» состоит из двух частей:

. Серверная часть (для установки на компьютер с сервером Docsvision), которая включает:
[loweralpha]
.. Библиотеку карточек «Управление документами» (нужна для регистрации пакета установки клиентской части приложения «Управление документами»).
.. Загружаемые в систему Docsvision данные:
* xref:CardSubtypes_DocManagement.adoc[виды карточек];
* xref:Roles_list.adoc[роли];
* xref:Navigator_folders.adoc[папки];
* xref:Groups.adoc[группы сотрудников];
* данные Конструктора состояний для карточек видов: Договор, Дополнительное соглашение, Акт, Согласование с контрагентом, Консолидация договора;
* данные Конструктора разметок для карточек видов: Договор, Дополнительное соглашение, Акт, Согласование с контрагентом, Консолидация договора;
* данные Конструктора ролей для карточек видов: Договор, Дополнительное соглашение, Акт;
* xref:DesignerDirectory_default_nodes.html[данные [.dfn .term]_Конструктора справочников_];
* xref:DesignerNumerationRules_default_rules.html[данные [.dfn .term]_Конструктора нумераторов_];
* xref:BP_DocManagement_templates.adoc[бизнес-процессы];
* скрипты карточек.
.. Библиотеки DLL с методами объектной модели карточек Приложения, [.dfn .term]_функциями_ БП (для работы с объектами Приложения в БП).
.. Пакет установки клиентской части приложения «Управление документами».
. Клиентская часть (для установки на компьютеры пользователей Docsvision) включает следующие элементы:
[loweralpha]
.. Библиотеки DLL с элементами пользовательского интерфейса для карточек Приложения (для Windows-клиента и РМА), элементами пользовательского интерфейса для настройки Приложения в [.dfn .term]_справочниках_ Docsvision.

* *xref:../topics/CardSubtypes_DocManagement.adoc[Виды карточек]* +
* *xref:../topics/Roles_list.adoc[Роли]* +
* *xref:../topics/Navigator_folders.adoc[Папки]* +
* *xref:../topics/Groups.adoc[Служебные группы]* +
* *xref:../topics/DesignerDirectory_default_nodes.adoc[Записи Конструктора справочников]* +
* *xref:../topics/DesignerNumerationRules_default_rules.adoc[Записи Конструктора правил нумерации]* +
* *xref:../topics/BP_DocManagement_templates.adoc[Бизнес-процессы]* +
