= Структура Приложения

Приложение "{dm}" состоит из двух частей:

. Серверная часть (для установки на компьютер с сервером {dv}), которая включает:
[loweralpha]
.. Библиотеку карточек "{dm}" (нужна для регистрации пакета установки клиентской части приложения "{dm}").
.. Загружаемые в систему {dv} данные:
* xref:CardSubtypes_DocManagement.adoc[виды карточек];
* xref:Roles_list.adoc[роли];
* xref:Navigator_folders.adoc[папки];
* xref:Groups.adoc[группы сотрудников];
* данные Конструктора состояний для карточек видов: Договор, Дополнительное соглашение, Акт, Согласование с контрагентом, Консолидация договора;
* данные Конструктора разметок для карточек видов: Договор, Дополнительное соглашение, Акт, Согласование с контрагентом, Консолидация договора;
* данные Конструктора ролей для карточек видов: Договор, Дополнительное соглашение, Акт;
* xref:DesignerDirectory_default_nodes.html[данные _Конструктора справочников_];
* xref:DesignerNumerationRules_default_rules.html[данные _Конструктора нумераторов_];
* xref:BP_DocManagement_templates.adoc[бизнес-процессы];
* скрипты карточек.
.. Библиотеки DLL с методами объектной модели карточек Приложения, _функциями_ БП (для работы с объектами Приложения в БП).
.. Пакет установки клиентской части приложения "{dm}".
. Клиентская часть (для установки на компьютеры пользователей {dv}) включает следующие элементы:
[loweralpha]
.. Библиотеки DLL с элементами пользовательского интерфейса для карточек Приложения (для {wincl}а и РМА), элементами пользовательского интерфейса для настройки Приложения в _справочниках_ {dv}.

