[[ariaid-title1]]
== Настройка синхронизации полей для шаблонов документов

Под синхронизацией подразумевается настройка автоматического копирования значений ряда полей из карточки во вложенный в карточку файл и наоборот.

Настройка синхронизации выполняется администратором приложения в [.dfn .term]_Справочнике видов карточек_. Данная операция является базовой для системы Docsvision, описание приведено в документе [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_#, пункт «Настройка синхронизации свойств карточки и файла».

В карточках видов [.dfn .term]_Договор_ и [.dfn .term]_Дополнительное соглашение_ по умолчанию настроена синхронизация полей в файл договорного документа. Для обеспечения синхронизации договорные документы должны быть созданы на основе шаблонов, входящих к комплект поставки. Администратор может изменить параметры синхронизации.

* *xref:../topics/task_Synch_fields_contract.adoc[Преднастроенная синхронизация полей в договоре]* +
* *xref:../topics/task_Synch_fields_SuppAgreement.adoc[Преднастроенная синхронизация полей в доп.соглашении]* +

*На уровень выше:* xref:../topics/Setting_Card_Contract_Document.adoc[Настройка карточек договорных документов]
