= Настройка личной папки пользователя приложения

В _Личную папку_ пользователя могут быть добавлены папки-делегаты на настроенные администратором папки маршрутизации. В стандартной поставке Приложения настроены следующие наборы папок маршрутизации:

* *Мои договоры* -- для поиска карточек договоров различных состояний, а также для контроля хода согласования договора; предназначена для пользователей, исполняющих роли _Ответственный_ и _Подписал_;
* *Договоры к ознакомлению* -- для поиска карточек договоров; предназначена для пользователей, исполняющих роль *Группа ознакомления*.

Настроить личную папку сотрудника для работы с договорами, можно одним из описанных ниже способов.

[[task_wwc_bzq_tm__steps_hdh_rhv_pr]]
. [.ph .cmd]#Чтобы создать папки маршрутизации для всех пользователей, добавьте папки ветки ([.ph .menucascade]#*Договоры* > *Служебные* > *Маршрутизация*#) *Мои договоры* и/или папки ветки *Договоры к ознакомлению* в использующуюся структуру маршрутизации (например, папку [.ph .menucascade]#*Служебные* > *Маршрутизация*. Для этого выполните действия:#
[loweralpha]
.. [.ph .cmd]#Откройте {wincl} и выделите в _Дереве папок_ папку *Мои договоры* или *Договоры к ознакомлению*.
.. [.ph .cmd]#Выберите из контекстного меню опцию *Копировать структуру папки* или *Создать делегата на эту папку*.
.. [.ph .cmd]#В открывшемся окне *Выбор папки* выделите папку маршрутизации (если используется маршрутизация приложения _{dm}_, то это папка *Маршрутизация*); нажмите кнопку выбора.
+
После обновления дерева папок скопированная ветка появится в личных папках пользователей приложения.
. [.ph .cmd]#Чтобы создать папки маршрутизации в личной папке определенного пользователя, настройте для него делегаты на нужные папки ветки [.ph .menucascade]#*Договоры* > *Служебные* > *Маршрутизация*.
