[[ariaid-title1]]
== Настройка режима создания карточки

Администратор Docsvision может определить различные режимы создания карточек. Для приложения «Управление документами» предусмотрен дополнительный способ создания карточек: xref:task_Set_card_create_mode_answer.adoc[в ответ на полученную карточку].

При установке приложения по умолчанию для карточек уже настроены следующие режимы создания:

* для карточки [.dfn .term]_Документ_:
** для вида [.keyword]*Документ УД/Исходящий* – режим «Исходящий в ответ на входящий»: из карточки вида [.keyword]*Входящий* будет создана карточка [.keyword]*Исходящий*;
** для вида [.keyword]*Документ УД/Входящий* – режимы:
*** «Входящий в ответ»: из карточки [.keyword]*Исходящий* будет создана карточка [.keyword]*Входящий*;
*** «Входящий по штрих-коду»: из карточки [.keyword]*Входящий* при сканировании штрих-кода документа будет автоматически создаваться новая карточка вида [.keyword]*Входящий*.
** для вида [.keyword]*Документ УД/Договор/Акт* – режим «Акт»: из карточки вида [.keyword]*Договор* будет создана карточка [.keyword]*Договор/Акт*;
** для вида [.keyword]*Документ УД/Договор/Дополнительное соглашения* – режимы:
*** «Доп. соглашение»: из карточки вида [.keyword]*Договор* будет создана карточка [.keyword]*Договор/Дополнительное соглашения*;
*** «Доп. соглашение о продлении сроков» – из карточки вида [.keyword]*Договор* будет создана карточка [.keyword]*Договор/Дополнительное соглашения* c новыми сроками действия договора;
* для карточки [.dfn .term]_Задание_ – вариант создания задания xref:task_Set_card_create_mode_answer.adoc[без размещения]:
** для вида [.keyword]*на исполнение* режим [.keyword .parmname]_На исполнение_: в случае создания задания на исполнение при помощи кнопки [.ph .uicontrol]*Создать задание* ленты инструментов Windows-клиента ярлык карточки не будет сохранен в выбранной папке [.dfn .term]_Дерева папок_.

При необходимости, администратор Docsvision может настроить другие режимы создания карточек в [.dfn .term]_Справочнике видов карточек_ (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_#).

* *xref:../topics/task_Set_card_create_mode_answer.adoc[Режим 'В ответ на']* +
* *xref:../topics/task_Set_card_create_mode_without_place.adoc[Режим 'Задание без размещения']* +
* *xref:../topics/task_Set_doc_card_create_mode_without_place.adoc[Режим 'Документ без размещения']* +

*На уровень выше:* xref:../topics/CardKindGuide.adoc[Настройка Справочника видов карточек]
