= Настройка режима создания карточки

Администратор {dv} может определить различные режимы создания карточек. Для приложения {dm} предусмотрен дополнительный способ создания карточек: xref:task_Set_card_create_mode_answer.adoc[в ответ на полученную карточку].

При установке приложения по умолчанию для карточек уже настроены следующие режимы создания:

* для карточки _Документ_:
** для вида *Документ УД/Исходящий* -- режим "Исходящий в ответ на входящий": из карточки вида *Входящий* будет создана карточка *Исходящий*;
** для вида *Документ УД/Входящий* -- режимы:
*** "Входящий в ответ": из карточки *Исходящий* будет создана карточка *Входящий*;
*** "Входящий по штрих-коду": из карточки *Входящий* при сканировании штрих-кода документа будет автоматически создаваться новая карточка вида *Входящий*.
** для вида *Документ УД/Договор/Акт* -- режим "Акт": из карточки вида *Договор* будет создана карточка *Договор/Акт*;
** для вида *Документ УД/Договор/Дополнительное соглашения* -- режимы:
*** "Доп. соглашение": из карточки вида *Договор* будет создана карточка *Договор/Дополнительное соглашения*;
*** "Доп. соглашение о продлении сроков" -- из карточки вида *Договор* будет создана карточка *Договор/Дополнительное соглашения* c новыми сроками действия договора;
* для карточки _Задание_ -- вариант создания задания xref:task_Set_card_create_mode_answer.adoc[без размещения]:
** для вида *на исполнение* режим _На исполнение_: в случае создания задания на исполнение при помощи кнопки *Создать задание* ленты инструментов {wincl}а ярлык карточки не будет сохранен в выбранной папке _Дерева папок_.

При необходимости, администратор {dv} может настроить другие режимы создания карточек в _Справочнике видов карточек_ (см. документ _Модуль "{dv} 5. {bo}". Руководство администратора_#).
