= Настройка автоматического завершения и отзыва подчиненных заданий и групп заданий

Администратор {dv} может настроить поведение подчиненных заданий и групп заданий при завершении и отзыве родительского задания.

. [.ph .cmd]#Откройте _Справочник видов карточек_.
. [.ph .cmd]#Выберите в поле *Тип карточки* значение _Задание_.
. [.ph .cmd]#Выберите в перечне видов нужный вид задания.
. [.ph .cmd]#Перейдите на вкладку *Подчиненное задание*.
. [.ph .cmd]#В области *Поведение подчинённых заданий при отзыве* выберите вариант завершения подчиненных заданий при отзыве родительского:#
* Не менять -- состояние подчиненных заданий не будет изменяться;
* Отозвать -- подчиненные задания будут отзываться;
* Удалить -- подчиненные задания будут удаляться.
. [.ph .cmd]#Аналогичным образом на вкладке *Подчиненная группа заданий* настройте поведение подчиненных групп задания при отзыве родительского задания.
. [.ph .cmd]#Перейдите на вкладку *Завершение задания*.
. [.ph .cmd]#Установите флаг *При завершении задания автоматически завершать подчиненные группы заданий*, чтобы при завершении родительского задания автоматически завершались все подчиненные группы заданий (фактически завершаются задания из групп).
. [.ph .cmd]#Установите флаг *При завершении задания автоматически завершать подчиненные задания*, чтобы при завершении родительского задания автоматически завершались все подчиненные задания.
