[[ariaid-title1]]
== Предоставление прав СУБП

Администратор Docsvision должен добавить в [.dfn .term]_Справочник сотрудников_ технологического сотрудника, от имени которого сервис Workflow будет работать с карточками Приложения.

[[task_ds2_nkz_b2b__steps_xfw_nkz_b2b]]
. [.ph .cmd]#Запустите Windows-клиент от имени администратора Docsvision.#
. [.ph .cmd]#Откройте [.dfn .term]_Справочник сотрудников_.#
. [.ph .cmd]#Добавьте нового сотрудника, указав в поле [.kbd .ph .userinput]`Пользователь` учетную запись сервиса Workflow (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Управление процессами». Руководство администратора_#), и любое допустимое значение в поле [.kbd .ph .userinput]`Фамилия` – прочие данные можно не указывать.#
. [.ph .cmd]#Предоставьте администратору Docsvision права на редактирование группы сотрудников «Системная для WF» по дискреционной модели безопасности (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Windows-клиент». Руководство пользователя_#, пункт «Управление доступом к объектам»).#
. [.ph .cmd]#Добавьте созданного на шаге 3 сотрудника в группу «Системная для WF».#
+
Если для обработки БП используется кластер Workflow с разными учетными записями сервисов Workflow, создайте технологического сотрудника для каждой учетной записи СУБП.

*Parent topic:* xref:../topics/task_Setup_order_empty_base.adoc[Настройка безопасности]
