[[ariaid-title1]]
== Назначение администраторов УД

Администраторы УД – группа пользователей, которым предоставлены дополнительные права (относительно других пользователей) на модификацию структуры папок Приложения, а также права на просмотр истории карточек УД.

Сравнение прав Администратора УД и рядового пользователя приведено в таблице.

.[.table--title-label]##Табл. 1. ##[.title]##Сравнение прав администратора УД и пользователя##
[width="100%",cols="50%,50%",options="header",]
|===
|Группа пользователей |Права
|*Права на общие папки* |
|Администраторы УД |Полный доступ. Может создавать и менять настройки папок, включая настройки безопасности.
|Все пользователи a|
Создание карточек, просмотр атрибутов и настроек. Запрещены операции:

* удаление общих папок;
* изменение атрибутов и настроек безопасности.

К папкам отчетов и поиска по категориям всем пользователям назначается доступ на чтение.

|*Шаблонная структура папок маршрутизации* |
|Администраторы УД |Полный доступ. Может настраивать и менять атрибуты.
|Все пользователи |Только просмотр папок-делегатов.
|===

Администратор Docsvision должен назначить Администраторов УД. Для этого:

. [.ph .cmd]#Откройте Windows-клиент от имени администратора Docsvision.#
. [.ph .cmd]#Откройте [.dfn .term]_Справочник сотрудников_.#
. [.ph .cmd]#Добавьте требуемого сотрудника в группу «Администраторы УД».#
+
Если при включении пользователя в группу система выдала сообщение о нехватке прав, выдайте себе права на редактирование группы сотрудников «Администраторы УД» по дискреционной модели безопасности (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Windows-клиент». Руководство пользователя_#, пункт «Управление доступом к объектам»).

*На уровень выше:* xref:../topics/task_Setup_order_empty_base.adoc[Настройка безопасности]
