[[ariaid-title1]]
== Настройка личной папки пользователя приложения

В [.dfn .term]_Личную папку_ пользователя могут быть добавлены папки-делегаты на настроенные администратором папки маршрутизации. В стандартной поставке Приложения настроены следующие наборы папок маршрутизации:

* [.keyword]*Мои договоры* – для поиска карточек договоров различных состояний, а также для контроля хода согласования договора; предназначена для пользователей, исполняющих роли [.dfn .term]_Ответственный_ и [.dfn .term]_Подписал_;
* [.keyword]*Договоры к ознакомлению* – для поиска карточек договоров; предназначена для пользователей, исполняющих роль [.keyword]*Группа ознакомления*.

Настроить личную папку сотрудника для работы с договорами, можно одним из описанных ниже способов.

[[task_wwc_bzq_tm__steps_hdh_rhv_pr]]
. [.ph .cmd]#Чтобы создать папки маршрутизации для всех пользователей, добавьте папки ветки ([.ph .menucascade]#[.ph .uicontrol]*Договоры* > [.ph .uicontrol]*Служебные* > [.ph .uicontrol]*Маршрутизация*#) [.keyword]*Мои договоры* и/или папки ветки [.keyword]*Договоры к ознакомлению* в использующуюся структуру маршрутизации (например, папку [.ph .menucascade]#[.ph .uicontrol]*Служебные* > [.ph .uicontrol]*Маршрутизация*#. Для этого выполните действия:#
[loweralpha]
.. [.ph .cmd]#Откройте Windows-клиент и выделите в [.dfn .term]_Дереве папок_ папку [.keyword]*Мои договоры* или [.keyword]*Договоры к ознакомлению*.#
.. [.ph .cmd]#Выберите из контекстного меню опцию [.keyword]*Копировать структуру папки* или [.keyword]*Создать делегата на эту папку*.#
.. [.ph .cmd]#В открывшемся окне [.keyword .wintitle]*Выбор папки* выделите папку маршрутизации (если используется маршрутизация приложения [.dfn .term]_Управление документами_, то это папка [.keyword]*Маршрутизация*); нажмите кнопку выбора.#
+
После обновления дерева папок скопированная ветка появится в личных папках пользователей приложения.
. [.ph .cmd]#Чтобы создать папки маршрутизации в личной папке определенного пользователя, настройте для него делегаты на нужные папки ветки [.ph .menucascade]#[.ph .uicontrol]*Договоры* > [.ph .uicontrol]*Служебные* > [.ph .uicontrol]*Маршрутизация*#.#

*На уровень выше:* xref:../topics/Settings_Folder_Tree.adoc[Настройка папок]
