= Согласование и подписание договорных документов

Согласование договорных документов выполняется средствами модуля "{dv} 5. {ad}". Модуль позволяет настроить маршрут согласования таким образом, чтобы он полностью соответствовал бизнес-процессам использующего его предприятия.

В Приложение включен xref:Contract_Plan_Approval_Route.html[[.keyword .parmname]_демонстрационный процесс согласования_], в рамках которого выполняется:

* согласование внутри компании с подготовкой итогового варианта документа;
* отправка итогового варианта документа на согласование контрагенту и проставление отметки о согласовании контрагентом;
* печать согласованного варианта договорного документа;
* подписание документа внутри компании и подписание документа контрагентом с проставлением соответствующих отметок в карточке.

В поставляемых видах карточек _Договор_ и _Дополнительное соглашение_ запуск [.keyword .parmname]_Демонстрационного процесса согласования_ производится при выполнении команды *Создать согласование*. После разработки предприятием собственных маршрутов согласования, администратор приложения заменяет для данной команды демонстрационный маршрут на актуальный.

После запуска процесса согласования, система формирует задания (на согласование, консолидацию или подписание) и рассылает эти задания назначенным участникам. Участники согласования получают задания и принимают решения по согласованию (создают собственные версии документов, добавляют комментарии, накладывают согласующие подписи и т.д.). Согласование считается завершенным после принятия положительного решения всеми согласующими на всех этапах согласования.

[NOTE]
====
Описание правил завершения согласования содержится в документе _Модуль "{dv} 5. {ad}". Руководство администратора_.
====

Инициатор согласования может управлять запущенным согласованием (наблюдать за ходом согласования, приостанавливать и повторно запускать процесс). Доступ к управлению открывается по команде *Открыть согласование*, расположенной на ленте карточек договорных документов.

