[[ariaid-title1]]
== Краткое описание возможностей

«Docsvision 5. Управление документами» является [.dfn .term]_базовым модулем_ системы «Docsvision 5.5», содержащим готовое к использованию прикладное [.dfn .term]_решение_ по работе с обычными и договорными документами. Предоставляемое Приложением [.dfn .term]_решение_ ориентировано на массовое использование – повседневную работу сотрудников и их взаимодействие в составе рабочих групп.

Приложение является удобным средством для эффективной и упорядоченной работы с документами на любом предприятии, где нет сложной системы делопроизводства, либо планируется начать автоматизацию документооборота с простых процессов.

В приложении «Управление документами» реализованы в упрощенном виде основные элементы классического делопроизводства:

* регистрация, хранение и поиск электронных документов;
* классификация документов;
* согласование и подписание документов;
* согласование проектов договоров, в том числе с контрагентом;
* ознакомление;
* фиксация хода исполнения договоров, в том числе:
** прикрепление рабочих материалов (файлов и карточек);
** прикрепление результатов (консолидированной версии договорного документа, актов, дополнительных соглашений, других дополнительных документов);
* работа с заданиями.

*На уровень выше:* xref:../topics/Introduction.adoc[Введение]
