= Интерфейс и назначение видов карточек приложения '{dm}'

В приложении _{dm}_ используются специальные виды карточек, созданные на основе базовых для системы _Docsvision 5_ видов карточек _Документ_, _Задание_, _Группа заданий_, _Согласование_.

Для различия с базовыми видами, названия видов карточек приложения дополняются постфиксом "УД":

* xref:DC_Descr.html[_Документ УД_];
* xref:TC_Descr.html[_Задание УД_];
* xref:GroupTasks_Card.html[_Группа заданий УД_].

На основе данных видов для приложения созданы дочерние виды карточек, позволяющие упростить работу пользователя с документами и заданиями. По умолчанию в приложении используются следующие дочерние виды:

* _Документ УД_:
** xref:DC_Descr_input.html[_Входящий_];
** xref:DC_Descr_output.html[_Исходящий_];
** xref:DC_Descr_note.html[_Служебная записка_];
** xref:DC_Descr_Zayavka.html[_Заявка_];
** xref:DC_Descr_ord.html[_ОРД_];
** xref:DC_Descr_work.html[_Рабочий_];
* _Задание УД_:
** xref:TC_Descr_Look.html[_На ознакомление_];
** xref:TC_Descr_Perform.html[_На исполнение_].

Для ввода в систему произвольных документов предназначена карточка xref:FC_Descr.html[_Файл_].

Для работы с договорами предназначены карточки:

* xref:Card_Contract.html[карточка _Договор_];
* xref:Card_SuppAgreement.html[Карточка _Дополнительное соглашение_];
* xref:Card_Act.html[Карточка _Акт_];
* xref:Card_Dogovor_Consolidation.html[Карточка _Консолидация договора_];
* xref:Card_Task_Approval.html[Карточка _Согласование с контрагентом_].
