= Интерфейс и назначение видов карточек приложения "{dm}"

В приложении _{dm}_ используются специальные виды карточек, созданные на основе базовых для системы _Docsvision 5_ видов карточек _Документ_, _Задание_, _Группа заданий_, _Согласование_.

Для различия с базовыми видами, названия видов карточек приложения дополняются постфиксом "УД":

* xref:DC_Descr.adoc[_Документ УД_];
* xref:TC_Descr.adoc[_Задание УД_];
* xref:GroupTasks_Card.adoc[_Группа заданий УД_].

На основе данных видов для приложения созданы дочерние виды карточек, позволяющие упростить работу пользователя с документами и заданиями. По умолчанию в приложении используются следующие дочерние виды:

* _Документ УД_:
** xref:DC_Descr_input.adoc[_Входящий_];
** xref:DC_Descr_output.adoc[_Исходящий_];
** xref:DC_Descr_note.adoc[_Служебная записка_];
** xref:DC_Descr_Zayavka.adoc[_Заявка_];
** xref:DC_Descr_ord.adoc[_ОРД_];
** xref:DC_Descr_work.adoc[_Рабочий_];
* _Задание УД_:
** xref:TC_Descr_Look.adoc[_На ознакомление_];
** xref:TC_Descr_Perform.adoc[_На исполнение_].

Для ввода в систему произвольных документов предназначена карточка xref:FC_Descr.adoc[_Файл_].

Для работы с договорами предназначены карточки:

* xref:Card_Contract.adoc[карточка _Договор_];
* xref:Card_SuppAgreement.adoc[Карточка _Дополнительное соглашение_];
* xref:Card_Act.adoc[Карточка _Акт_];
* xref:Card_Dogovor_Consolidation.adoc[Карточка _Консолидация договора_];
* xref:Card_Task_Approval.adoc[Карточка _Согласование с контрагентом_].
