= Демонстрационный процесс согласования

Приложение включает демонстрационный процесс согласования, по которому могут согласовываться и подписываться карточки _Договор_ и _Дополнительное соглашение_.

[NOTE]
====
Для _Демонстрационного процесса согласования_ используется маршрут *Согласование договоров*, описание которого приведено в руководстве администратора Приложения.
====

Перед запуском процесса необходимо добавить пользователей в группы:

* *Согласование договоров*;
* *Печать договоров*,

а также заполнить поля карточки _Договор_ или _Дополнительное соглашение_:

* *С нашей стороны>Подготовил*
* *С нашей стороны>Ответственный*
* *С нашей стороны>Подписывает*
* *Контрагент>Контактное лицо*, в _Справочнике контрагентов_ для данного сотрудника должен быть указан e-mail.

_Демонстрационный процесс согласования_ представляет собой выполнение следующего сценария работы с договором:

1. Согласование документа внутри организации::
При запуске согласования карточка договорного документа переводится в состояние `На согласовании`.
+
 Всем пользователям, состоящим в группе _Согласование Договоров_ рассылаются задания вида _На согласование_, к которым приложены согласуемые файлы. Режим исполнения заданий -- _Параллельно_, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.
+
 В процессе согласования документа исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок ленты карточки задания _На согласование_. Решение по согласованию выполняется сразу для всех файлов, приложенных к карточке задания.
+
 См. xref:task_Approving_get.adoc[Согласование договора (дополнительного соглашения) внутри организации]
2. Консолидация -- создание итогового документа по итогам согласования внутри организации::
После того, как все согласующие лица высказали свое мнение по документу, консолидатор (в роли которого выступает _Инициатор_ согласования) должен принять решение о дальнейшей судьбе договора.
+
. Если принято решение о том, что договор в текущей редакции _не согласован_, то консолидатор может:
* составить новую редакцию договора и отправить ее на согласование;
* отменить согласование.
. Если договор _согласован_ или _согласован с замечаниями_, карточка договорного документа переводится в состояние `Согласован`. Консолидатор (после выбора итоговой на данном этапе версии документа) может:
* отправить договор на согласование с контрагентом;
* отправить договор на печать (если согласование с контрагентом было произведено ранее);
* отменить согласование.
+
 См. xref:task_Consolidation_get.adoc[Консолидация согласованного договора]
3. Согласование/подписание документа с контрагентом::
При переходе к этому этапу карточка договорного документа переводится в состояние `На согласовании Контрагентом`. _Ответственному_ за договорной документ приходит задание вида _Согласование с контрагентом_, к которому приложена согласованная внутри организации версия договора.
+
 Получив такое задание, сотрудник должен передать полученную версию договора на согласование в организацию контрагента, получить ответ контрагента и принять решение о дальнейшей судьбе договора.
+
. Если принято решение о том, что договор в текущей редакции _не согласован_, то _Ответственный_ может:
* погрузить в карточку версию, полученную от контрагента и отправить ее на согласование внутри организации;
* отменить согласование.
. Если договор _согласован_ или _согласован с замечаниями_, _Ответственный_ может:
* отправить договор на печать;
* отправить договор на подписание внутри организации (если от контрагента вернулся *подписанный оригинал*);
* отменить согласование.
+
 См.xref:task_Task_Approve.adoc[Выполнение приёмки задания]

[NOTE]
====
Этапы согласования договора внутри организации, консолидации и согласования с контрагентом могут циклически повторяться до выработки одобренного всеми согласующими варианта договора.
====

4. Печать бумажного экземпляра документа::
Этап является техническим, предваряющим подписание бумажного оригинала договорного документа. При передаче на печать карточка договорного документа переводится в состояние `На подписании`.
+
 Печать договора осуществляет сотрудник из _Группы печати_, получивший задание вида _Подписание_. После печати бумажный оригинал договорного документа передается на подписание сотрудникам, указанным в поле *Подписал* карточки договорного документа.
5. Подписание документа внутри организации::
При передаче на подписание карточка договорного документа переводится (или остается) в состояние `На подписании`.
+
 Всем пользователям, указанным в поле *Подписано* рассылаются задания вида _Подписание_, к которым приложены согласованные договорные документы, требующие подписания. Режим исполнения заданий -- _Параллельно_, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.
+
 В процессе подписания документа исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок ленты инструментов карточки задания вида _Подписание_. Решение по подписанию выполняется сразу для всех _Основных_ файлов, приложенных к карточке.
+
[CAUTION]
====
При согласовании договора (дополнительного соглашения) с использованием демонстрационного процесса, заполнение полей _Подписано_ и _Ответственный_ в карточке _Договор_ (_Дополнительное соглашение_) является обязательным.
====
+
6. Консолидация -- создание итогового документа по итогам подписания внутри организации и завершение маршрута::
После того, как все подписанты высказали свое мнение по документу, консолидатор (в роли которого выступает _Инициатор_ согласования) должен принять решение о дальнейшей судьбе договора.
+
. Если в подписании отказано, то консолидатор может:
* составить новую редакцию договора и начать новый цикл согласования;
* отменить согласование.
. Если договор _подписан_, то консолидатору следует:
* завершить согласование, если ранее договор был согласован/подписан контрагентом;
* передать договор на согласование/подписание контрагенту, если ранее этого сделано не было.
