[[ariaid-title1]]
== Добавление файла в карточку

Файл можно добавить в карточку следующими способами:

* при создании карточки 'Документ';
* с помощью перетаскивания из файловой системы;
* путем простого сканирования файла;
* путем сканирования файла с распознаванием;
* с помощью перетаскивания из приложения [.dfn .term]_Microsoft Outlook_;
* с использованием контекстного команды меню области вложений карточки [.dfn .term]_Документ_;
* с помощью перетаскивания приложенного файла из другой карточки;
* из буфера обмена Windows.

Также специалистами по внедрению системы могут быть настроены дополнительные способы добавления файлов в _Справочнике видов карточек_:

* основной файл может будет автоматически создан по шаблону при создании карточки;
* карточка может изначально содержать основной и/или дополнительные файлы;
* при создании карточки может автоматически выдаваться запрос на добавление основного файла со сканера или с файловой системы.

=== Особенности механизма загрузки файлов

Добавление файлов в карточку документа осуществляется в асинхронном режиме – пользователь может продолжать работать с карточкой, пока файлы загружаются на сервер. До завершения загрузки название файла отображается серым цветом, после загрузки – чёрным. Во время загрузки на иконке файла отображается значок «Песочные часы» – наведите курсор мыши на данный значок, чтобы узнать прогресс загрузки (отображается размер загруженных данных и общий размер файла).

Если требуется, загрузка может быть прервана пользователем: выберите команду «Отменить загрузку файла» в контекстном меню загружаемого файла.

При одновременной загрузке нескольких файлов они будут загружены последовательно (каждый в асинхронном режиме).

До завершения загрузки файла (файлов) карточки допускается изменение её данных (без сохранения), но запрещено закрытие карточки. Во избежание ошибок *не рекомендуется* сохранять, подписывать карточку или изменять её состояние (регистрировать, отправлять на согласование и т.п.) до завершения загрузки всех файлов.

* *xref:../topics/DCard_file_add_drag_and_drop_filesystem.adoc[Добавление перетаскиванием из файловой системы]* +
* *xref:../topics/DCard_file_add_contexmenu_filesystem.adoc[Добавление командой контекстного меню из файловой системы]* +
* *xref:../topics/DCard_file_add_Outlook.adoc[Добавление перетаскиванием из MS Outlook]* +
* *xref:../topics/DCard_file_add_drag_and_drop_Dcard.adoc[Добавление перетаскиванием из другой карточки 'Документ']* +
* *xref:../topics/DCard_file_add_clipboard.adoc[Добавление из буфера обмена]* +

*На уровень выше:* xref:../topics/Dcard_files.adoc[Работа с файлами карточки 'Документ']
