[[ariaid-title1]]
== Работа с файлами карточки 'Документ'

Для хранения совместно с регистрационной карточкой документа больших объемов сопутствующей информации к карточкам документов могут прикрепляться файлы.

Карточка документа может содержать:

* набор [.dfn .term]_основных_ файлов, для хранения и обработки которых была создана карточка. Создание новых версий и автоматическое включение в цифровую подпись, доступны только для основных файлов карточки.
* набор [.dfn .term]_дополнительных_ файлов, поясняющих или дополняющих содержание основных файлов. Например, если основным файлом является распознанная копия документа, одним из дополнительных файлов может быть отсканированное изображение документа.

Приложить можно неограниченное количество файлов, как основных, так и дополнительных. Чтобы сделать из [.dfn .term]_основного_ файла [.dfn .term]_дополнительный_ или наоборот, достаточно перетащить файл из одной области в другую.

При отображении файлов применяется сортировка в алфавитном порядке. [.dfn .term]_Основные_ и [.dfn .term]_дополнительные_ файлы сортируются отдельно. Обновление порядка отображения файлов в списке выполняется при каждом добавлении и переименовании файлов карточки.

С [.dfn .term]_основными_ файлами могут быть выполнены следующие операции:

* открытие на редактирование;
* предварительный просмотр;
* сохранение в указанное место файловой системы;
* копирование в буфер обмена;
* блокирование, возврат с блокировки и отмена блокировки файла в карточке;
* удаление файла.

С [.dfn .term]_дополнительными_ файлами могут быть выполнены следующие операции:

* предварительный просмотр;
* сохранение в указанное место файловой системы;
* копирование в буфер обмена;
* выделение всех дополнительных файлов (если их несколько);
* удаление файла.

* *xref:../topics/DCard_file_add.adoc[Добавление файла в карточку]* +
* *xref:../topics/DCard_file_open.adoc[Открытие 'основного' файла]* +
* *xref:../topics/DCard_file_preview.adoc[Предварительный просмотр файла]* +
* *xref:../topics/DCard_file_block.adoc[Блокирование и разблокирование файлов]* +
* *xref:../topics/DCard_file_versions.adoc[Управление версиями файлов]* +
* *xref:../topics/DCard_file_save_as.adoc[Сохранение файла на локальный компьютер]* +
* *xref:../topics/DCard_file_rename.adoc[Переименование файла]* +
* *xref:../topics/DCard_file_delete.adoc[Удаление файла из карточки 'Документ']* +
* *xref:../topics/DCard_properties_synsynchronization.adoc[Синхронизация свойств файла и карточки]* +

*На уровень выше:* xref:../topics/Doc_Work_General.adoc[Общие сценарии работы с электронными документами]
