[[ariaid-title1]]
== Создание заданий по документу

Задания позволяют создавать распоряжения по документу, предназначенные определенным исполнителям. Например, при помощи заданий можно отправить документ на ознакомление другим сотрудникам или исполнить данное руководителем задание с приложенным сопроводительным документом.

Каждое задание снабжено описанием работ, сроками их исполнения и другими параметрами, а также предусматривает необходимый контроль за ходом его реализации.

Задание предназначено для выполнения одним исполнителем. Если указано несколько исполнителей, работа с заданием будет выполняться тем из них, кто первым возьмет задание в работу.

Для создания заданий в приложении [.dfn .term]_Управление документами_ предусмотрены специальные карточки xref:TC_Descr.html[[.dfn .term]_Задание УД_] видов:

* xref:TC_Descr_Look.html[[.keyword .parmname]_На ознакомление_];
* xref:TC_Descr_Perform.html[[.keyword .parmname]_На исполнение_].

Работа с заданиями описана в разделе xref:task_Task_Creation.adoc[Создание заданий].

*На уровень выше:* xref:../topics/Doc_Work_General.adoc[Общие сценарии работы с электронными документами]
