= Создание группы заданий по документу

Группы заданий позволяют создавать детализированные распоряжения по документу, предназначенные для выполнения сразу несколькими исполнителями. В зависимости от настройки, задания могут быть отправлены либо одновременно всем назначенным исполнителям, либо последовательно "передаваться" от одного исполнителя к другому. В последнем случае отправка задания следующему исполнителю будет происходить после завершения задания предыдущим исполнителем из очереди.

Для создания группы заданий в приложении _{dm}_ предусмотрена специальная xref:GroupTasks_Card.html[карточка _Группа заданий УД_.] После активизации данной карточки система создает бизнес-процесс в соответствии с указанными параметрами, и выполняется рассылка заданий исполнителям.

Каждое из заданий, отправленных исполнителям, снабжено описанием работ, сроками их исполнения и другими параметрами, а также предусматривает контроль за ходом выполнения задания.

Работа с данным видом заданий описана в разделе xref:task_GroupTask_create.adoc[Создание группы заданий].
