[[ariaid-title1]]
== Проставление отметки об аннулировании договора (дополнительного соглашения)

Аннулировать можно [.dfn .term]_Договор_ и [.dfn .term]_Дополнительное соглашение_ в состоянии `Подготавливается`, `На подписании                     контрагентом`.

Для аннулирования договорного документа следует выполнить следующие действия:

. [.ph .cmd]#Откройте карточку договорного документа.#
. [.ph .cmd]#Выполните любое из действий:#
* нажмите кнопку [.ph .uicontrol]*Аннулировать*;
* нажмите на ленте карточки кнопку [.ph .uicontrol]*Выполнить*, затем выберите опцию [.keyword]*Аннулирован*.
+
При наличии связанных актов и дополнительных соглашений на экран будет выведено соответствующее предупреждение.
. [.ph .cmd]#Подтвердите аннулирование договорного документа.#
+
Договор будет переведен в состояние `Аннулирован`. Задания по документу, созданные на вкладке [.keyword]*Задания*, отозваны не будут.
. [.ph .cmd]#Выполните необходимое действие с карточкой:#
* xref:Preparation_Doc_Contract.adoc[верните договор в состояние подготовки].

*На уровень выше:* xref:../topics/Work_Contracts.adoc[Работа по договору и дополнительному соглашению]
