= Создание договорного документа из {wincl}а

. [.ph .cmd]#Откройте {wincl}.
. [.ph .cmd]#В дереве папок выберите папку, в которой будет создана карточка.
+
Рекомендуется создавать договорные документы в папке *Договоры*.
. [.ph .cmd]#Выполните одно из действий:#
* В контекстном меню области представлений выберите [.ph .menucascade]#[.ph .uicontrol]*Создать карточку* > [.ph .uicontrol]*Документ* > [.ph .uicontrol]*Документы УД* > [.ph .uicontrol]*Договор* > [.ph .uicontrol]*<Вид карточки договора>*.
* Нажмите на ленте стрелку рядом с кнопкой [.ph .uicontrol]*Создать карточку* и выберите из списка пункт [.ph .menucascade]#[.ph .uicontrol]*Документ* > [.ph .uicontrol]*Документы УД* > [.ph .uicontrol]*Договор* > [.ph .uicontrol]*<Вид карточки договора>*.
* Нажмите на ленте кнопку [.ph .uicontrol]*Создать карточку*, в открывшемся окне [.keyword .wintitle]*Создание новой карточки* выберите пункт [.ph .menucascade]#[.ph .uicontrol]*Документ* > [.ph .uicontrol]*Документы УД* > [.ph .uicontrol]*Договор* > [.ph .uicontrol]*<Вид карточки договора>*# и дважды щелкните по нему левой кнопкой мыши или нажмите кнопку [.ph .uicontrol]*OK*.
+
Будет открыта новая карточка договорного документа с чистыми полями.

