[[ariaid-title1]]
== Завершение задания

Задание могут завершить:

* [.keyword]*Исполнитель*, его [.keyword]*Заместитель* или [.keyword]*Делегат*, после окончания работы над заданием;
* [.keyword]*Автор задания* или [.keyword]*Контролёр* могут xref:task_Task_Force_Finish.adoc[прекратить] выполнение задания, когда посчитают, что задание уже выполнено.

[.ph]#Для делегированных заданий вида [.keyword .parmname]_На исполнение_ [.keyword]*Исполнитель* или его [.keyword]*Заместитель* могут завершить задание без взятия его в работу.#

Для завершения задания исполнителю необходимо выполнить следующие действия:

[[task_hq4_1bz_wj__steps_qp1_hrc_mk]]
. [.ph .cmd]#Откройте карточку [.keyword .parmname]_Задание УД_.#
. [.ph .cmd]#Если это предусмотрено, добавьте отчет в текстовое поле [.kbd .ph .userinput]`Отчет`.#
. [.ph .cmd]#При необходимости, приложите файл отчета или выберите для отчета карточку документа.#
+
Добавленная в качестве отчета карточка будет доступна автору задания, если для документа настроена ролевая модель, предусматривающая данную возможность.
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Завершить* на ленте инструментов карточки [.dfn .term]_Задание_.#
+
Карточка задания будет закрыта. Ссылка на карточку будет перемещена в папку [.ph .filepath]`Мои задания / Входящие / Завершено`.

Если задание было делегировано, и был настроен xref:task_Task_Delegate.adoc[возврат] с делегирования, ярлык для доступа к карточке будет перемещен в папку [.ph .filepath]`Мои задания / Входящие` исполнителя, делегировавшего задание.

Если для задания требовалась xref:task_Task_Approve.adoc[приемка], после завершения исполнителем оно перейдет на приемку к [.keyword]*Контролеру*. При соответствующей настройке, контролеру может быть отправлено по электронной почте уведомление следующего содержания: `В системе Docsvision Вам передано на                             приемку задание "Название задания", в котором Вы назначены контролером.                             Для того, чтобы получить детальную информацию и ознакомиться с                             результатами исполнения задания, перейдите по ссылке. Будет открыта                             карточка задания.`

После перехода задания в состояние `завершено` [.keyword]*Автору* задания может быть отправлено по электронной почте уведомление следующего содержания: `В системе Docsvision                             пользователем "ФИО сотрудника, завершившего задание" было завершено                             задание "Название задания", автором которого Вы являетесь. Для того,                             чтобы ознакомиться с результатами, перейдите по ссылке. Будет открыта                             карточка задания`.

*На уровень выше:* xref:../topics/Task_Work.adoc[Работа с  заданиями и группами заданий]
