= Просмотр журнала организационно-распорядительных документов

Журнал _Действующие ОРД_ предназначен для поиска документов вида _Документ УД - Организационно-распорядительный_, которые были назначены действующими. Результаты поиска будут содержать только документы, доступные роли пользователя.

Для поиска информации в журнале можно воспользоваться операциями фильтрации, сортировки и группировки:

* фильтрация доступна по виду документа (по умолчанию - _ОРД и его дочерние_), состоянию (по умолчанию - _Действует_);
* группировка доступна по подразделению;
* сортировка доступна по дате регистрации (по умолчанию - по убыванию).

Чтобы открыть журнал, выполните следующие действия:

[[task_tt5_pdp_jp__steps_flr_ddp_jp]]
. [.ph .cmd]#В Дереве папок откройте папку [.ph .menucascade]#*Документы* > *Организационно-распорядительные* > *Действующие ОРД*.
. [.ph .cmd]#В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.
. [.ph .cmd]#Нажмите на кнопку *ОК*.
+
Найденные карточки будут отображены в _Области представления_. Для отображения будет использован вид представления: *Отчеты\Действующие ОРД*.
