= Завершение задания

Задание могут завершить:

* *Исполнитель*, его *Заместитель* или *Делегат*, после окончания работы над заданием;
* *Автор задания* или *Контролёр* могут xref:task_Task_Force_Finish.adoc[прекратить] выполнение задания, когда посчитают, что задание уже выполнено.

Для делегированных заданий вида _На исполнение_ *Исполнитель* или его *Заместитель* могут завершить задание без взятия его в работу.

Для завершения задания исполнителю необходимо выполнить следующие действия:

. Откройте карточку _Задание УД_.
. Если это предусмотрено, добавьте отчёт в текстовое поле `Отчёт`.
. При необходимости приложите файл отчёта или выберите для отчёта карточку документа.
+
Добавленная в качестве отчёта карточка будет доступна автору задания, если для документа настроена ролевая модель, предусматривающая данную возможность.
. Нажмите кнопку *Завершить* на ленте инструментов карточки _Задание_.
+
Карточка задания будет закрыта. Ссылка на карточку будет перемещена в папку  menu:Мои задания[Входящие > Завершено].

Если задание было делегировано, и был настроен xref:task_Task_Delegate.adoc[возврат] с делегирования, ярлык для доступа к карточке будет перемещен в папку  menu:Мои задания[Входящие] исполнителя, делегировавшего задание.

Если для задания требовалась xref:task_Task_Approve.adoc[приёмка], после завершения исполнителем оно перейдет на приёмку к *Контролеру*. При соответствующей настройке, контролеру может быть отправлено по электронной почте уведомление следующего содержания: `В системе {dv} Вам передано на приёмку задание "Название задания", в котором Вы назначены контролером. Для того, чтобы получить детальную информацию и ознакомиться с результатами исполнения задания, перейдите по ссылке. Будет открыта карточка задания.`

После перехода задания в состояние `завершено` *Автору* задания может быть отправлено по электронной почте уведомление следующего содержания: `В системе {dv} пользователем "ФИО сотрудника, завершившего задание" было завершено задание "Название задания", автором которого Вы являетесь. Для того, чтобы ознакомиться с результатами, перейдите по ссылке. Будет открыта карточка задания`.
