[[ariaid-title1]]
== Просмотр журнала организационно-распорядительных документов

Журнал [.dfn .term]_Действующие ОРД_ предназначен для поиска документов вида [.dfn .term]_Документ УД - Организационно-распорядительный_, которые были назначены действующими. Результаты поиска будут содержать только документы, доступные роли пользователя.

Для поиска информации в журнале можно воспользоваться операциями фильтрации, сортировки и группировки:

* фильтрация доступна по виду документа (по умолчанию - [.keyword .parmname]_ОРД и его дочерние_), состоянию (по умолчанию - [.keyword .parmname]_Действует_);
* группировка доступна по подразделению;
* сортировка доступна по дате регистрации (по умолчанию - по убыванию).

Чтобы открыть журнал, выполните следующие действия:

[[task_tt5_pdp_jp__steps_flr_ddp_jp]]
. [.ph .cmd]#В Дереве папок откройте папку [.ph .menucascade]#[.ph .uicontrol]*Документы* > [.ph .uicontrol]*Организационно-распорядительные* > [.ph .uicontrol]*Действующие ОРД*#.#
. [.ph .cmd]#В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.#
. [.ph .cmd]#Нажмите на кнопку [.keyword]*ОК*.#
+
Найденные карточки будут отображены в [.dfn .term]_Области представления_. Для отображения будет использован вид представления: [.keyword]*Отчеты\Действующие ОРД*.

*Parent topic:* xref:../topics/ORD_Work.adoc[Организационно-распорядительная документация]
