[[ariaid-title1]]
== Работа заместителя с заданиями замещаемого

Чтобы получить задание замещаемого сотрудника:

. Перейдите в папку:
* [.ph .filepath]`Замещение / Входящие` – если нужно взять задание в работу,
* [.ph .filepath]`Замещение / Входящие / На контроле` или [.ph .filepath]`Замещение / Входящие / Ответственное исполнение` – если нужно взять в работу задание, находящееся на контроле или ответственном исполнении у замещаемого сотрудника.
. Откройте любое из полученных заданий.
. Выполните доступные операции с заданием.
+
Заместитель может в задании замещаемого выполнять все действия, доступные замещаемому. При этом действуют следующие правила:

* если заместитель xref:task_Task_TakeInWork.adoc[взял в работу] задание замещаемого сотрудника, [.keyword]*Исполнителем* задания будет считаться заместитель (в задании автоматически фиксируется делегирование типа `Автоматически`);
* если заместитель xref:task_Task_Finish.adoc[завершил] задание, он будет указан в задании в качестве завершившего задание [.keyword]*Исполнителя*.
+
После завершения данных заданий они будут возвращены [.keyword]*Автору* задания.
+
Задания, делегированные заместителем, будут возвращены в зависимости от xref:task_Task_Deputy_Delegate.adoc[способа] делегирования.

*На уровень выше:* xref:../topics/task_Task_Fulfil_Replace.adoc[Замещение при исполнении заданий]
