= Просмотр журнала исходящих документов

_Журнал исходящих документов_ предназначен для поиска всех документов вида _Документ УД - Исходящий_, доступных роли текущего пользователя, за период, указанный пользователем.

Для поиска информации в журнале можно воспользоваться операциями фильтрации, сортировки и группировки:

* фильтрация доступна по виду документа (по умолчанию - _Исходящий и его дочерние_), состоянию (по умолчанию - _Все_) и периоду регистрации (по умолчанию - _Неделя_);
* группировка доступна по дате регистрации и организации;
* сортировка доступна по дате регистрации (по умолчанию - по убыванию).

Чтобы открыть журнал, выполните следующие действия:

[[task_z1m_wcp_jp__steps_flr_ddp_jp]]
. [.ph .cmd]#В _Дереве папок_ откройте папку [.ph .menucascade]#*Документы* > *Исходящие* > *Журнал исходящих документов*.
. [.ph .cmd]#В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.
. [.ph .cmd]#Нажмите на кнопку *ОК*.
+
Найденные карточки будут отображены в _Области представления_. Для отображения будет использован вид представления: *Отчеты\Журнал исходящих документов*.
