= Завершение экземпляра группы заданий исполнителем

Для завершения работы с экземпляром карточки _Группа заданий_ *Исполнителю* необходимо завершить задание. По умолчанию для вида _Группа заданий УД_ экземпляром является задание вида _На исполнение_. Для исполнителя работа с экземпляром группы заданий не отличается от xref:task_Task_Take.adoc[работы] с обычным заданием.

Чтобы завершить задание, выполните следующие действия:

[[task_ydh_dtc_mk__steps_qp1_hrc_mk]]
. [.ph .cmd]#Откройте карточку _Задание УД_.
+
Понять, что задание групповое, исполнитель может в карточке _Задание УД_, на вкладке *Дополнения* в таблице *Связанные карточки*.
. [.ph .cmd]#Нажмите кнопку *Завершить* на ленте инструментов карточки _Задание УД_.
+
Карточка задания будет закрыта.

Дальнейшие действия зависят от типа маршрутизации карточки _Группа заданий УД_, а также назначенных для группы заданий *Ответственного исполнителя* и *Контролера*.

В случае использования _параллельного_ способа маршрутизации:

* если данный исполнитель не назначен *Ответственным исполнителем*:
** при отсутствии назначенного *Контролера* задание будет завершено;
** при наличии назначенного *Контролера* задание будет доступно в папке *Я - контролер* указанного *Контролера* (к контролеру поступят задания от всех исполнителей).
* если данный исполнитель является *Ответственным исполнителем* и назначен *Контролер*, на приемку Контролеру поступит только задание *Ответственного исполнителя* и будет доступно в папке `Мои задания / Входящие / На контроле`. Задания остальных исполнителей на приёмку после завершения не переходят.

В случае использования _последовательного_ способа маршрутизации дополнительно к описанному выше:

* если данный исполнитель не последний в очереди, у текущего исполнителя задание будет завершено и доступно в папке `Мои задания / Входящие / Завершено`. У следующего по очереди исполнителя задание появится в папке `Мои задания / Входящие`;
* если данный исполнитель последний, действия полностью аналогичны _параллельному_ способу маршрутизации.
