[[ariaid-title1]]
== Создание заданий из карточки Документ

Создание заданий из карточки [.keyword .parmname]_Документ УД_ является одной из основных операций по работе с карточкой. При создании заданий данным способом родительская карточка [.dfn .term]_Документ_ будет автоматически приложена к создаваемой карточке [.dfn .term]_Задание_. Родительскую карточку можно будет xref:task_Task_OpenAttachment.adoc[открыть из панели вложений] карточки [.dfn .term]_Задание_.

Задания создаются из карточек [.keyword .parmname]_Документ УД_ при помощи кнопок ленты инструментов карточки. Виды заданий, которые будут создаваться при нажатии на кнопки ленты, определяются администратором (документ [.ph]#[.dfn .term]_Приложение «Docsvision 5. Управление документами». Руководство администратора_#, раздел «Настройка видов связанных заданий»).

При создании заданий из карточки вида [.keyword .parmname]_ДокументУД-Рабочий_ предусмотрено автоматическое заполнение поля [.keyword]*Рабочая группа* (данное поле присутствует в схеме карточки) (см. xref:task_Work_Doc_Create.adoc[Ввод рабочего документа в систему]).

* *xref:../topics/task_Task_For_Fulfil.adoc[Задание на исполнение]* +
* *xref:../topics/task_Task_For_Look.adoc[Задание на ознакомление]* +

*На уровень выше:* xref:../topics/task_Task_Creation.adoc[Создание заданий]
