[[ariaid-title1]]
== Просмотр журнала исходящих документов

[.dfn .term]_Журнал исходящих документов_ предназначен для поиска всех документов вида [.dfn .term]_Документ УД - Исходящий_, доступных роли текущего пользователя, за период, указанный пользователем.

Для поиска информации в журнале можно воспользоваться операциями фильтрации, сортировки и группировки:

* фильтрация доступна по виду документа (по умолчанию - [.keyword .parmname]_Исходящий и его дочерние_), состоянию (по умолчанию - [.keyword .parmname]_Все_) и периоду регистрации (по умолчанию - [.keyword .parmname]_Неделя_);
* группировка доступна по дате регистрации и организации;
* сортировка доступна по дате регистрации (по умолчанию - по убыванию).

Чтобы открыть журнал, выполните следующие действия:

[[task_z1m_wcp_jp__steps_flr_ddp_jp]]
. [.ph .cmd]#В [.dfn .term]_Дереве папок_ откройте папку [.ph .menucascade]#[.ph .uicontrol]*Документы* > [.ph .uicontrol]*Исходящие* > [.ph .uicontrol]*Журнал исходящих документов*#.#
. [.ph .cmd]#В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.#
. [.ph .cmd]#Нажмите на кнопку [.keyword]*ОК*.#
+
Найденные карточки будут отображены в [.dfn .term]_Области представления_. Для отображения будет использован вид представления: [.keyword]*Отчеты\Журнал исходящих документов*.

*На уровень выше:* xref:../topics/Out_Doc_Work.adoc[Исходящая корреспонденция]
