[[ariaid-title1]]
== Делегирование задания заместителем

Возникают ситуации, когда заместитель по каким-либо причинам отказывается от самостоятельного выполнения задания и хочет передать его другому исполнителю. Для таких ситуаций можно использовать операцию делегирования.

Выполнение делегирования задания заместителем выполняется аналогично xref:task_Task_Delegate.adoc[обычному] делегированию, за исключением некоторых особенностей.

Чтобы делегировать задание, заместителю необходимо выполнить следующие действия:

. [.ph .cmd]#Чтобы делегированное задание вернулось обратно заместителю, перед делегированием задание необходимо выполнить любое из следующих действий: #
* xref:task_Task_TakeInWork.adoc[взять в работу];
* делегировать задание самому себе.
+
Чтобы делегировать задание себе, выполните следующие действия:
[loweralpha]
.. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*Делегировать* в карточке задания.#
.. [.ph .cmd]#В открывшемся окне [.keyword .wintitle]*Делегирования* в поле [.keyword]*Делегаты* выберите текущего сотрудника (себя).#
.. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*Принять*.#
+
При этом карточка задания будет закрыта, ярлык задания будет перемещен в папку [.ph .filepath]`Замещение / Входящие` заместителя. Заместитель станет текущим исполнителем данного задания. Далее можно заново открыть карточку задания и снова выполнить операцию делегирования, только выбрать в качестве делегата другого исполнителя и установить флаг [.ph .uicontrol]*Возврат с делегирования*.
. [.ph .cmd]#Чтобы делегированное задание вернулось с делегирования назначенному [.keyword]*Исполнителю*, следует делегировать задание, не беря его в работу (из состояния `Не начато`). Для этого выполните следующие действия:#
[loweralpha]
.. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*Делегировать* в карточке задания.#
.. [.ph .cmd]#В открывшемся окне [.keyword .wintitle]*Делегирования* в поле [.keyword]*Делегаты* выберите нового исполнителя задания.#
.. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*Принять*.#
+
При завершении такое задание попадёт в папку [.ph .filepath]`Мои задания / Входящие` замещаемого сотрудника.

*На уровень выше:* xref:../topics/task_Task_Fulfil_Replace.adoc[Замещение при исполнении заданий]
