[[ariaid-title1]]
== Замещение при исполнении заданий

В приложении «Управление документами» предусмотрено несколько вариантов замещения сотрудника при выполнении заданий:

* сотрудник может быть назначен постоянным заместителем – в этом случае ему будут всегда доступны задания замещаемого;
* или сотрудник может являться временным заместителем – в данном случае задания замещаемого будут доступны ему только во время неактивности (болезнь, командировка и т. п.), если при создании задания был установлен флаг xref:task_Task_set_deputy.adoc[«Доступно заместителю»].

Заместители работают с заданиями замещаемого сотрудника с помощью папок:

* [.ph .filepath]`Замещение / Входящие` – для поступающих заданий;
** [.ph .filepath]`Замещение / Входящие / В работе` – для заданий замещаемого сотрудника, находящихся в работе;
** [.ph .filepath]`Замещение / Входящие / На контроле` – для заданий замещаемого сотрудника, находящихся на контроле;
** [.ph .filepath]`Замещение / Входящие / Ответственное исполнение` – для заданий замещаемого сотрудника, в которых он является ответственным исполнителем;
* [.ph .filepath]`Замещение / Исходящие` – для заданий, автором которых является замещаемый сотрудник;
** [.ph .filepath]`Замещение / Исходящие / Делегировано` – для заданий, которые были делегированы и автором которых является замещаемый сотрудник;
** [.ph .filepath]`Замещение / Исходящие / Завершено` – для заданий, которые были завершены и автором которых является замещаемый сотрудник.

Настройка замещения может быть выполнена как администратором (документ [.ph]#[.dfn .term]_Приложение «Docsvision 5. Управление документами». Руководство администратора_#, пункт «Настройка замещения»), так и самим сотрудником (документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Windows-клиент». Руководство пользователя_#, пункт «Управление состоянием сотрудника»).

* *xref:../topics/task_Task_Deputy_Work.adoc[Работа заместителя с заданиями замещаемого]* +
* *xref:../topics/task_Task_Deputy_Delegate.adoc[Делегирование задания заместителем]* +

*На уровень выше:* xref:../topics/Task_Work.adoc[Работа с  заданиями и группами заданий]
