= Просмотр журнала входящих документов

_Журнал входящих документов_ предназначен для поиска всех документов вида _Документ УД - Входящий_, доступных роли текущего пользователя, за период, указанный пользователем.

Для поиска информации в журнале можно воспользоваться операциями фильтрации, сортировки и группировки:

* фильтрация доступна по виду документа (по умолчанию - [.keyword .parmname]_Входящий и его дочерние_), состоянию (по умолчанию - [.keyword .parmname]_Все_) и периоду регистрации (по умолчанию - [.keyword .parmname]_Неделя_);
* группировка доступна по дате регистрации и получателю;
* сортировка доступна по дате регистрации (по умолчанию - по убыванию).

Чтобы открыть журнал, выполните следующие действия:

[[task_wd4_41p_jp__steps_flr_ddp_jp]]
. [.ph .cmd]#В _Дереве папок_ откройте папку [.ph .menucascade]#[.ph .uicontrol]*Документы* > [.ph .uicontrol]*Входящие* > [.ph .uicontrol]*Журнал входящих документов*.
. [.ph .cmd]#В открывшемся окне укажите параметры поиска: начало и окончание периода, за который должны быть найдены карточки.
. [.ph .cmd]#Нажмите на кнопку *ОК*.
+
Найденные карточки будут отображены в _Области представления_. Для отображения будет использован вид представления: *Отчеты\Журнал входящих документов*.

