[[ariaid-title1]]
== Работа с файлом вне системы Docsvision

При разработке текста документа  можно выгрузить файл из системы [.dfn .term]_Docsvision_ для корректировки, а затем загрузить его обратно в систему. На время такой корректировки файл становится недоступен для редактирования другими пользователями.

Операция доступна при работе с документами в состоянии [.dfn .term]_Подготовка_. Для реализации этой операции выполните следующие действия:

. [.ph .cmd]#В карточке [.dfn .term]_Документ_ в области отображения списка прикреплённых файлов выделите нужный файл и, открыв на нём контекстное меню, выберите пункт [.ph .uicontrol]*Заблокировать для работы*.#
+
Для xref:task_Doc_Encrypting.adoc[зашифрованных] файлов блокирование запрещено.
. [.ph .cmd]#В открывшемся диалоговом окне выберите (или создайте новую) папку для размещения файла.#
. [.ph .cmd]#Выполните необходимую обработку файла с помощью внешнего приложения (например, Microsoft Word).#
. [.ph .cmd]#По окончании работы отмените блокировку файла или верните файл с блокировки, выбрав в контекстном меню пункт [.ph .uicontrol]*Отменить блокировку* или [.ph .uicontrol]*Вернуть с блокировки* соответственно.#
+
Пункт меню [.ph .uicontrol]*Вернуть с блокировки* применим в том случае, если заблокированный файл был изменён.
+
В результате в систему будет загружена новая версия файла, которая станет текущей.

*На уровень выше:* xref:../topics/task_Files_Edit.adoc[Редактирование прикреплённых файлов]
