= Проставление в карточке 'Акт' отметки о подписании

Для проставлении в карточке _Акт_ отметки о его подписании внутри организации, выполните следующие действия:

[[task_wpg_4p5_lk__steps_lsy_ckd_mk]]
. [.ph .cmd]#Откройте карточку акта в состоянии `На                     подписании`.
. [.ph .cmd]#Выполните любое из действий:#
* нажмите на ленте инструментов карточки кнопку [.ph .uicontrol]*Подписан*;
* нажмите на ленте карточки кнопку [.ph .uicontrol]*Выполнить*, затем выберите опцию *Подписан*.
+
Карточка _Акт_ будет переведена в состояние `Подписан`. Если поле [.keyword .parmname]_Дата подписания нами_ было пусто, то его значением устанавливается текущая дата.
. [.ph .cmd]#Выполните необходимое действие с карточкой:#
* xref:task_Act_Return_to_Preparation.adoc[верните акт в состояние подготовки];
* xref:task_Act_Transfer_to_Sign_Counterparty.adoc[проставьте отметку о передаче на подписание контрагентом];
* xref:task_Act_Mark_on_Validity.adoc[проставьте отметку о действительности акта];
* xref:task_Act_Cancel.adoc[аннулируйте акт].

