[[ariaid-title1]]
== Настройка контроля группы заданий

При отправке группы заданий исполнителям можно предусмотреть контроль выполнения заданий ответственным сотрудником. Настройка контроля различается в зависимости от выбранного варианта исполнения карточки. 

Чтобы настроить контроль за выполнением группы заданий, выполните следующие действия:

. [.ph .cmd]#На вкладке [.keyword]*Основная* раскройте область [.keyword]*Приемка и контроль*.#
. [.ph .cmd]#Установите флаг [.ph .uicontrol]*На контроле*.#
+
Станут доступными для заполнения поля [.keyword]*Дата контроля* и [.keyword]*Контролёр*.
. [.ph .cmd]#Выполните одно из доступных действий:#
* если выбран вариант исполнения [.keyword]*Параллельно*, в поле [.keyword]*Дата контроля* укажите дату, когда должен быть выполнен контроль выполнения задания. Выбор даты можно произвести при помощи встроенного календаря, который открывается при нажатии на стрелку в правой части поля;
* если выбран вариант исполнения [.keyword]*Последовательно*, в поле [.keyword]*Контроль до завершения (ч.)* укажите количество часов, за которое должен быть выполнен контроль выполнения задания.
. [.ph .cmd]#В поле [.keyword]*Контролёр* укажите сотрудника, который будет контролировать качество выполнения задания. Выбор можно произвести из [.dfn .term]_Справочника сотрудников_, который открывается при нажатии на кнопку в правой части поля, либо при помощи быстрого поиска по подстроке.#
+
Назначенный контролёр будет отображаться во всех запущенных заданиях.
+
Контролёр сможет осуществлять контроль выполнения заданий. Все завершенные задания сразу переходят в состояние _Завершено_ (и не переходят на приемку).

[[task_mvc_xks_kk__two_flags]]
Если в карточке Группы заданий установлен флаг [.ph .uicontrol]*На контроле*, то во всех заданиях группы в поля [.keyword]*Контролёр* и [.keyword]*Дата контроля* переносятся значения из соответствующих полей Группы заданий (при варианте исполнения [.keyword]*Последовательно* значение поля [.keyword]*Дата контроля* рассчитывается вычитанием значения поля [.keyword]*Контроль до завершения (ч.)* из значения поля [.keyword]*Дата завершения*).

Если в карточке одновременно установлены флаги [.ph .uicontrol]*Требуется приемка* и [.ph .uicontrol]*На контроле*:

* Если одновременно указаны Контролёр и Ответственный исполнитель, Контролёр будет проверять выполнение задания только Ответственного исполнителя. Задания остальных исполнителей на приёмку после завершения не переходят.
* Если указан только Контролёр, а Ответственный исполнитель – нет, Контролёру на приемку переходят задания всех исполнителей.

*На уровень выше:* xref:../topics/task_GroupTask_create_Dcard.adoc[Создание группы заданий из карточки 'Документ УД']
