[[ariaid-title1]]
== Создание договорного документа из Windows-клиента

. [.ph .cmd]#Откройте Windows-клиент.#
. [.ph .cmd]#В дереве папок выберите папку, в которой будет создана карточка.#
+
Рекомендуется создавать договорные документы в папке [.keyword]*Договоры*.
. [.ph .cmd]#Выполните одно из действий:#
* В контекстном меню области представлений выберите [.ph .menucascade]#[.ph .uicontrol]*Создать карточку* > [.ph .uicontrol]*Документ* > [.ph .uicontrol]*Документы УД* > [.ph .uicontrol]*Договор* > [.ph .uicontrol]*<Вид карточки договора>*#.
* Нажмите на ленте стрелку рядом с кнопкой [.ph .uicontrol]*Создать карточку* и выберите из списка пункт [.ph .menucascade]#[.ph .uicontrol]*Документ* > [.ph .uicontrol]*Документы УД* > [.ph .uicontrol]*Договор* > [.ph .uicontrol]*<Вид карточки договора>*#.
* Нажмите на ленте кнопку [.ph .uicontrol]*Создать карточку*, в открывшемся окне [.keyword .wintitle]*Создание новой карточки* выберите пункт [.ph .menucascade]#[.ph .uicontrol]*Документ* > [.ph .uicontrol]*Документы УД* > [.ph .uicontrol]*Договор* > [.ph .uicontrol]*<Вид карточки договора>*# и дважды щелкните по нему левой кнопкой мыши или нажмите кнопку [.ph .uicontrol]*OK*.
+
Будет открыта новая карточка договорного документа с чистыми полями.

*На уровень выше:* xref:../topics/task_Creat_Card_Doc.adoc[Создание карточки договорного документа]
