= Замещение при исполнении заданий

В приложении "{dm}" предусмотрено несколько вариантов замещения сотрудника при выполнении заданий:

* сотрудник может быть назначен постоянным заместителем -- в этом случае ему будут всегда доступны задания замещаемого;
* или сотрудник может являться временным заместителем -- в данном случае задания замещаемого будут доступны ему только во время неактивности (болезнь, командировка и т. п.), если при создании задания был установлен флаг xref:task_Task_set_deputy.adoc["Доступно заместителю"].

Заместители работают с заданиями замещаемого сотрудника с помощью папок:

* `Замещение / Входящие` -- для поступающих заданий;
** `Замещение / Входящие / В работе` -- для заданий замещаемого сотрудника, находящихся в работе;
** `Замещение / Входящие / На контроле` -- для заданий замещаемого сотрудника, находящихся на контроле;
** `Замещение / Входящие / Ответственное исполнение` -- для заданий замещаемого сотрудника, в которых он является ответственным исполнителем;
* `Замещение / Исходящие` -- для заданий, автором которых является замещаемый сотрудник;
** `Замещение / Исходящие / Делегировано` -- для заданий, которые были делегированы и автором которых является замещаемый сотрудник;
** `Замещение / Исходящие / Завершено` -- для заданий, которые были завершены и автором которых является замещаемый сотрудник.

Настройка замещения может быть выполнена как администратором (документ _Приложение "{dv} 5. {dm}". Руководство администратора_#, пункт "Настройка замещения"), так и самим сотрудником (документ _Модуль "{dv} 5. {wincl}". Руководство пользователя_#, пункт "Управление состоянием сотрудника").

