[[ariaid-title1]]
== Прикрепление файлов к карточке договорного документа

К карточке договорного документа может быть прикреплено произвольное количество основных и дополнительных файлов различных форматов. Файлы, прикрепленные как основные, будут участвовать в согласовании и подписании договорного документа.

По умолчанию к карточке Договора и Дополнительного соглашения прикрепляется файл xref:Templates.adoc[шаблона договора].

Файлы прикрепляются к карточке договорного документа следующим образом:

. [.ph .cmd]#Откройте карточку договорного документа и перейдите на вкладку [.keyword]*Файл*.#
. [.ph .cmd]#Выберите из контекстного меню области [.ph .uicontrol]*Вложенные файлы* один из вариантов:#
* Добавить файл из файловой системы,
* Добавить отсканированный файл,
* Добавить отсканированный и распознанный файл.
. [.ph .cmd]#Выберите назначение файла:#
* Основной,
* Дополнительный.
+
Если на предыдущем шаге был выбран вариант [.ph .uicontrol]*Добавить отсканированный и распознанный файл*, то данный шаг пропускается.
. [.ph .cmd]#Выберите файл из файловой системы или файл, полученный сканированием.#
+
Ссылка на карточку файла будет помещена в таблицу [.ph .uicontrol]*Файлы*.

[NOTE]
====
[.note__title]#Прим.:# См. особенности асинхронной загрузки файлов в пункте xref:DCard_file_add.adoc[Добавление файла в карточку].
====

*На уровень выше:* xref:../topics/ContractOperations.adoc[Основные операции с карточками договорных документов]
