= Работа с файлом вне системы {dv}

При разработке текста документа можно выгрузить файл из системы _Docsvision_ для корректировки, а затем загрузить его обратно в систему. На время такой корректировки файл становится недоступен для редактирования другими пользователями.

Операция доступна при работе с документами в состоянии _Подготовка_. Для реализации этой операции выполните следующие действия:

. В карточке _Документ_ в области отображения списка прикреплённых файлов выделите нужный файл и, открыв на нём контекстное меню, выберите пункт *Заблокировать для работы*.
+
Для xref:task_Doc_Encrypting.adoc[зашифрованных] файлов блокирование запрещено.
. В открывшемся диалоговом окне выберите (или создайте новую) папку для размещения файла.
. Выполните необходимую обработку файла с помощью внешнего приложения (например, Microsoft Word).
. По окончании работы отмените блокировку файла или верните файл с блокировки, выбрав в контекстном меню пункт *Отменить блокировку* или *Вернуть с блокировки* соответственно.
+
Пункт меню *Вернуть с блокировки* применим в том случае, если заблокированный файл был изменён.
+
В результате в систему будет загружена новая версия файла, которая станет текущей.
