[[ariaid-title1]]
== Фиксация хода исполнения задания

При работе с заданиями предусмотрены следующие возможности фиксации хода исполнения задания: добавление комментариев, прикрепление отчета, добавление дополнительных файлов и ссылок, установка напоминания о задании.

. [.ph .cmd]#Для добавления комментария к заданию перейдите на вкладку [.keyword .wintitle]*Комментарии*, введите комментарий в поле для ввода, после чего нажмите кнопку [.ph .uicontrol]*Добавить*. Комментарий с датой будет добавлен в список комментариев.#
. [.ph .cmd]#Чтобы прикрепить к заданию отчет нажмите кнопку [.ph .uicontrol]*Добавить файл* в группе команд [.keyword .wintitle]*Отчет* и выберите файл отчета, или нажмите кнопку [.ph .uicontrol]*Выбрать карточку* и выберите карточку документа, которая будет добавлена в качестве отчета.#
+
Добавленная в качестве отчета карточка будет доступна автору задания, если для документа настроена ролевая модель, предусматривающая данную возможность.
. [.ph .cmd]#Для добавления дополнительных файлов или ссылок перейдите на вкладку [.keyword .wintitle]*Файлы и ссылки* и добавьте файл, ссылку на карточку, папку или ресурс.#
. [.ph .cmd]#Для создания напоминания о сроках исполнения задания в группе полей [.ph .uicontrol]*Напоминания* в карточке [.dfn .term]_Задание_ установите флаг [.ph .uicontrol]*Напомнить за* или точную дату напоминания. +++Программа Microsoft Outlook должна быть открыта+++. В Outlook будет создано напоминание с нужной датой (персонально для каждого пользователя).#

*На уровень выше:* xref:../topics/task_Task_Fulfil.adoc[Исполнение задания]
