[[ariaid-title1]]
== Создание группы заданий из Windows-клиента

Карточка [.keyword .parmname]_Группа заданий УД_ может быть создана из программы «Windows-клиент» несколькими способами:

* при помощи кнопки ленты приложения [.keyword]*Создать карточку*;
* при помощи контекстного меню [.dfn .term]_Области представления_ или папки.

Чтобы создать карточку [.dfn .term]_Группа заданий_ вида [.keyword .parmname]_Группа заданий УД_ из стандартной (не виртуальной) папки Windows-клиента, выполните следующие действия:

. [.ph .cmd]#Щелкните правой кнопкой мыши по свободному пространству в представлении, либо по папке в левой части Windows-клиента и выберите в контекстном меню пункт [.ph .menucascade]#[.ph .uicontrol]*Создать карточку* > [.ph .uicontrol]*Группа заданий* > [.ph .uicontrol]*Группа заданий УД*#. #
+
Будет открыта новая карточка [.keyword .parmname]_Группа заданий УД_.
. [.ph .cmd]#Заполните поля карточки, как это описано в п. xref:task_GroupTask_create_Dcard.adoc[Создание группы заданий из карточки 'Документ УД']. #

*На уровень выше:* xref:../topics/task_GroupTask_create.adoc[Создание группы заданий]
