[[ariaid-title1]]
== Завершение экземпляра группы заданий исполнителем

Для завершения работы с экземпляром карточки [.dfn .term]_Группа заданий_ [.keyword]*Исполнителю* необходимо завершить задание. По умолчанию для вида [.keyword .parmname]_Группа заданий УД_ экземпляром является задание вида [.keyword .parmname]_На исполнение_. Для исполнителя работа с экземпляром группы заданий не отличается от xref:task_Task_Take.adoc[работы] с обычным заданием.

Чтобы завершить задание, выполните следующие действия:

[[task_ydh_dtc_mk__steps_qp1_hrc_mk]]
. [.ph .cmd]#Откройте карточку [.keyword .parmname]_Задание УД_.#
+
Понять, что задание групповое, исполнитель может в карточке [.keyword .parmname]_Задание УД_, на вкладке [.keyword]*Дополнения* в таблице [.keyword]*Связанные карточки*.
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Завершить* на ленте инструментов карточки [.keyword .parmname]_Задание УД_.#
+
Карточка задания будет закрыта.

Дальнейшие действия зависят от типа маршрутизации карточки [.keyword .parmname]_Группа заданий УД_, а также назначенных для группы заданий [.keyword]*Ответственного исполнителя* и [.keyword]*Контролера*.

В случае использования [.keyword .parmname]_параллельного_ способа маршрутизации:

* если данный исполнитель не назначен [.keyword]*Ответственным исполнителем*:
** при отсутствии назначенного [.keyword]*Контролера* задание будет завершено;
** при наличии назначенного [.keyword]*Контролера* задание будет доступно в папке [.keyword]*Я - контролер* указанного [.keyword]*Контролера* (к контролеру поступят задания от всех исполнителей).
* если данный исполнитель является [.keyword]*Ответственным исполнителем* и назначен [.keyword]*Контролер*, на приемку Контролеру поступит только задание [.keyword]*Ответственного исполнителя* и будет доступно в папке [.ph .filepath]`Мои задания / Входящие / На контроле`. Задания остальных исполнителей на приёмку после завершения не переходят.

В случае использования [.keyword .parmname]_последовательного_ способа маршрутизации дополнительно к описанному выше:

* если данный исполнитель не последний в очереди, у текущего исполнителя задание будет завершено и доступно в папке [.ph .filepath]`Мои задания / Входящие / Завершено`. У следующего по очереди исполнителя задание появится в папке [.ph .filepath]`Мои задания / Входящие`;
* если данный исполнитель последний, действия полностью аналогичны [.keyword .parmname]_параллельному_ способу маршрутизации.

*На уровень выше:* xref:../topics/GroupTask_finish.adoc[Завершение группы заданий]
