= Делегирование задания заместителем

Возникают ситуации, когда заместитель по каким-либо причинам отказывается от самостоятельного выполнения задания и хочет передать его другому исполнителю. Для таких ситуаций можно использовать операцию делегирования.

Выполнение делегирования задания заместителем выполняется аналогично xref:task_Task_Delegate.adoc[обычному] делегированию, за исключением некоторых особенностей.

Чтобы делегировать задание, заместителю необходимо выполнить следующие действия:

. Чтобы делегированное задание вернулось обратно заместителю, перед делегированием задание необходимо выполнить любое из следующих действий:
* xref:task_Task_TakeInWork.adoc[взять в работу];
* делегировать задание самому себе.
+
Чтобы делегировать задание себе, выполните следующие действия:
[loweralpha]
.. Нажмите на кнопку *Делегировать* в карточке задания.
.. В открывшемся окне *Делегирования* в поле *Делегаты* выберите текущего сотрудника (себя).
.. Нажмите на кнопку *Принять*.
+
При этом карточка задания будет закрыта, ярлык задания будет перемещен в папку  menu:Замещение[Входящие] заместителя. Заместитель станет текущим исполнителем данного задания. Далее можно заново открыть карточку задания и снова выполнить операцию делегирования, только выбрать в качестве делегата другого исполнителя и установить флаг *Возврат с делегирования*.
. Чтобы делегированное задание вернулось с делегирования назначенному *Исполнителю*, следует делегировать задание, не беря его в работу (из состояния `Не начато`). Для этого выполните следующие действия:
[loweralpha]
.. Нажмите на кнопку *Делегировать* в карточке задания.
.. В открывшемся окне *Делегирования* в поле *Делегаты* выберите нового исполнителя задания.
.. Нажмите на кнопку *Принять*.
+
При завершении такое задание попадёт в папку  menu:Мои задания[Входящие] замещаемого сотрудника.
