[[ariaid-title1]]
== Создание карточки договорного документа

Карточку [.dfn .term]_Договор_ можно создать одним из следующих способов:

* из Windows-клиента;
* по шаблону.

Карточки [.dfn .term]_Дополнительное соглашение_ и [.dfn .term]_Акт_ могут быть созданы следующим образом:

* из Windows-клиента;
* по шаблону;
* xref:task_Creat_ActSAgr_of_CardsContract.adoc[из карточки договора].

К созданной карточки будет приложен файл, сформированный из стандартного шаблона договора (для карточки Договор) или шаблона дополнительного соглашения. Описание стандартных шаблонов договорных документов приведено в xref:Templates.adoc[Приложении B]. Наличие приложенного документа регулируется соответствующей настройкой в [.dfn .term]_Справочнике видов_.

* *xref:../topics/task_Creat_Doc_of_Navigator.adoc[Создание договорного документа из Windows-клиента]* +
* *xref:../topics/task_Creat_ActSAgr_of_CardsContract.adoc[Создание карточек 'Дополнительное соглашение' и 'Акт' из карточки 'Договор']* +

*На уровень выше:* xref:../topics/ContractOperations.adoc[Основные операции с карточками договорных документов]
