= Работа заместителя с заданиями замещаемого

Чтобы получить задание замещаемого сотрудника:

. Перейдите в папку:
* `Замещение / Входящие` -- если нужно взять задание в работу,
* `Замещение / Входящие / На контроле` или `Замещение / Входящие / Ответственное исполнение` -- если нужно взять в работу задание, находящееся на контроле или ответственном исполнении у замещаемого сотрудника.
. Откройте любое из полученных заданий.
. Выполните доступные операции с заданием.
+
Заместитель может в задании замещаемого выполнять все действия, доступные замещаемому. При этом действуют следующие правила:

* если заместитель xref:task_Task_TakeInWork.adoc[взял в работу] задание замещаемого сотрудника, *Исполнителем* задания будет считаться заместитель (в задании автоматически фиксируется делегирование типа `Автоматически`);
* если заместитель xref:task_Task_Finish.adoc[завершил] задание, он будет указан в задании в качестве завершившего задание *Исполнителя*.
+
После завершения данных заданий они будут возвращены *Автору* задания.
+
Задания, делегированные заместителем, будут возвращены в зависимости от xref:task_Task_Deputy_Delegate.adoc[способа] делегирования.
