[[ariaid-title1]]
== 'Группа ознакомления с договором' и работа ее сотрудников

[.keyword .parmname]_Группа ознакомления_ с договором – сотрудники, имеющие право на чтение карточки [.dfn .term]_Договор_ или [.dfn .term]_Дополнительное соглашение_.

Создает и заполняет [.keyword .parmname]_Группу ознакомления_ администратор. Как правило, для каждой определенной в [.dfn .term]_Конструкторе справочников_ группы договоров создается своя [.keyword .parmname]_Группа ознакомления_.

Если в карточке [.dfn .term]_Договор_ ([.dfn .term]_Дополнительное соглашение_) заполняется поле [.ph .uicontrol]*Группа договора*, то сотрудники, включенные в соответствующую [.keyword .parmname]_Группу ознакомления_ получают права на чтение этой карточки.

[NOTE]
====
[.note__title]#Прим.:# При необходимости администратор может настроить рассылку уведомлений о ходе согласования договора [.keyword .parmname]_Группе ознакомления_ с договором.
====

В [.dfn .term]_Личной_ папке включенного в [.keyword .parmname]_Группу ознакомления_ пользователя может быть создана папка-делегат на папку [.keyword]*Договоры к ознакомлению*.

*На уровень выше:* xref:../topics/WorkWithContracts.adoc[Работа с договорами]
