[[ariaid-title1]]
== Управление рабочими группами

При управлении документами часто возникает необходимость формирования из числа сотрудников "рабочих групп", которые совместно участвуют в работе над каким-либо проектом.

В рамках системы [.dfn .term]_Docsvision_ для объединения сотрудников используются группы, создание которых выполняется в [.dfn .term]_Справочнике сотрудников_. Однако, доступ к данному справочнику у некоторых пользователей может быть ограничен настройками дискреционной безопасности. В этом случае, использование механизма управления рабочими группами остается единственным возможным средством объединения сотрудников. Группы, создаваемые данным способом, будут отображаться в списке групп [.dfn .term]_Справочника сотрудников_, и могут настраиваться как средствами управления рабочими группами, так и средствами справочника.

[NOTE]
====
[.note__title]#Внимание:# Возможности настройки групп в [.dfn .term]_Справочнике сотрудников_ преобладают над настройками групп механизма управления рабочими группами.
====

После добавления сотрудников в данную группу, ее членам можно определить различные права: в составе группы могут быть администраторы, обладающие полным набором прав по управлению группой, участники и читатели, которым доступен только режим просмотра. Для рабочей группы определяется набор доступных папок, возможность управления которыми зависит от настроек роли участника группы.

Правами на создание и управление рабочими группами обладает пользователь, входящий в служебную группу [.keyword]*Администраторы РГ*. У данного пользователя на ленте программы «Windows-клиент» появляется дополнительная вкладка [.keyword]*Рабочие группы*, включающая команды для добавления новой группы, добавления участников в существующую группу, а также редактирования и удаления групп. Участники группы получают по электронной почте уведомления о включении/исключении из группы.

* *xref:../topics/Navigator_tab_work_groups.adoc[Лента вкладки 'Рабочие группы']* +
* *xref:../topics/task_WorkGroups_create.adoc[Создание рабочей группы]* +
* *xref:../topics/task_WorkGroups_change.adoc[Редактирование рабочей группы]* +
* *xref:../topics/task_WorkGroups_delete.adoc[Удаление рабочей группы]* +
* *xref:../topics/task_WorkGroups_members_add.adoc[Добавление участников в группу]* +
* *xref:../topics/task_WorkGroups_members_delete.adoc[Удаление участника группы]* +

*На уровень выше:* xref:../topics/Operations.adoc[Описание операций]
