= Управление рабочими группами

При управлении документами часто возникает необходимость формирования из числа сотрудников "рабочих групп", которые совместно участвуют в работе над каким-либо проектом.

В рамках системы _{dv}_ для объединения сотрудников используются группы, создаваемые в _Справочнике сотрудников_. Однако, доступ к данному справочнику у некоторых пользователей может быть ограничен настройками дискреционной безопасности. В этом случае механизма управления рабочими группами остается единственным возможным средством объединения сотрудников. Группы, создаваемые данным способом, будут отображаться в списке групп _Справочника сотрудников_, и могут настраиваться как средствами управления рабочими группами, так и средствами справочника.

[WARNING]
====
Возможности настройки групп в _Справочнике сотрудников_ преобладают над настройками групп с помощью механизма управления рабочими группами.
====

После добавления сотрудников в данную группу, её членам можно определить различные права: в составе группы могут быть администраторы, обладающие полным набором прав по управлению группой, участники и читатели, которым доступен только режим просмотра. Для рабочей группы определяется набор доступных папок, возможность управления которыми зависит от настроек роли участника группы.

Правами на создание и управление рабочими группами обладает пользователь, входящий в служебную группу _Администраторы РГ_. У данного пользователя на ленте программы "{wincl}" появляется дополнительная вкладка _Рабочие группы_, включающая команды для добавления новой группы, добавления участников в существующую группу, а также редактирования и удаления групп. Участники группы получают по электронной почте уведомления о включении и исключении из группы.
