[[ariaid-title1]]
== Работа с актом

Карточка [.dfn .term]_Акт_ предназначена для хранения сведений об акте по договору. [.dfn .term]_Акт_ не предполагает согласования и подписания в системе Docsvision, работа с ним заключается в проставлении отметок о движении бумажного документа, приводящих к изменению состояния карточки:

* передаче на подписание внутри организации;
* подписание внутри организации;
* передаче на подписание контрагенту;
* перевод в состояние `Действителен`;
* аннулирование (при возникновении такой необходимости).

При помощи команд ленты можно либо перевести карточку в другое состояние относительно текущего, либо вернуться в предыдущее состояние.

Для карточек актов предусмотрен следующий набор доступных состояний:

=== Подготовка акта

Подготовка::
  Создание новой карточки акта и заполнение первичных регистрационных данных. Сохранение карточки с присвоением регистрационного номера и заполнением даты регистрации. См. xref:task_Act_RegData_insert.adoc[Подготовка и регистрация акта].

=== Проставление отметок о движении документа

На подписании::
  В карточке договорного документа выполнена команда [.keyword]*На подписание контрагентом*. См. xref:task_Act_Transfer_to_Sign.adoc[Проставление в карточке 'Акт' отметки о передаче на подписание].
Подписан::
  В карточке договорного документа выполнена команда [.keyword]*Подписан*. В карточке в поле [.keyword]*Дата подписания контрагентом* проставлена дата. См. xref:task_Act_Mark_Signing.adoc[Проставление в карточке 'Акт' отметки о подписании].
На подписание контрагенту::
  В карточке договорного документа выполнена команда [.keyword]*На подписание контрагенту*. В карточке в поле [.keyword]*Дата подписания контрагентом* проставлена дата. См. xref:task_Act_Transfer_to_Sign_Counterparty.adoc[Проставление в карточке 'Акт' отметки о передаче на подписание контрагентом].
Действителен::
  В карточке договорного документа выполнена команда [.keyword]*Назначить действительным*. См. xref:task_Act_Mark_on_Validity.adoc[Проставление отметки о действительности акта]
Аннулирован::
  В карточке договорного документа выполнена команда [.keyword]*Аннулировать*. См. xref:task_Act_Cancel.adoc[Аннулирование акта].

* *xref:../topics/task_Act_RegData_insert.adoc[Подготовка и регистрация акта]* +
* *xref:../topics/task_Act_Transfer_to_Sign.adoc[Проставление в карточке 'Акт' отметки о передаче на подписание]* +
* *xref:../topics/task_Act_Mark_Signing.adoc[Проставление в карточке 'Акт' отметки о подписании]* +
* *xref:../topics/task_Act_Transfer_to_Sign_Counterparty.adoc[Проставление в карточке 'Акт' отметки о передаче на подписание контрагентом]* +
* *xref:../topics/task_Act_Mark_on_Validity.adoc[Проставление отметки о действительности акта]* +
* *xref:../topics/task_Act_Return_to_Preparation.adoc[Возврат акта на подготовку]* +
* *xref:../topics/task_Act_Cancel.adoc[Аннулирование акта]* +

*На уровень выше:* xref:../topics/WorkWithContracts.adoc[Работа с договорами]
