= Модификация разметки карточки вида "Документ УД"

== Общие рекомендации

В разметке карточек видов Документ УД все подключаемые элементы управления допускается изменять и перенастраивать. Все встроенные элементы управления могут быть удалены, если их использование не предполагается.

== Недопустимые изменения

Замена встроенных элементов управления на подключаемые запрещена для объекта `Файлы`. В карточке вида _Документ УД_ элемент управления расположен на вкладке "Основной файл и вложения", в дочерних видах -- на вкладке "Регистрационные данные", в виде _Договор_ и его дочерних видах (*Акт* и _Дополнительное соглашение_) -- на вкладке "Вложенные файлы".

== Допустимые изменения

Замена встроенных элементов управления на подключаемые разрешена для следующих объектов:

* `Категории`. В карточке вида _Документ УД_ элемент управления расположен на вкладке Категории, в дочерних видах не используется.
* `История`. В карточке вида Документ УД и дочерних видах элемент управления расположен на вкладке История.