= Модификация разметки карточки вида "Документ УД"

== Общие рекомендации

В разметке карточек видов Документ УД все подключаемые элементы управления допускается изменять и перенастраивать. Все встроенные элементы управления могут быть удалены, если их использование не предполагается.

== Недопустимые изменения

Замена встроенных элементов управления на подключаемые запрещена для объекта `Файлы`. В карточке вида _Документ УД_ элемент управления расположен на вкладке _Основной файл и вложения_, в дочерних видах -- на вкладке _Регистрационные данные_, в виде _Договор_ и его дочерних видах (_Акт_ и _Дополнительное соглашение_) -- на вкладке "Вложенные файлы".

== Допустимые изменения

Замена встроенных элементов управления на подключаемые разрешена для следующих объектов:

* `_Категории_`. В карточке вида _Документ УД_ элемент управления расположен на вкладке Категории, в дочерних видах не используется.
* `_История_`. В карточке вида Документ УД и дочерних видах элемент управления расположен на вкладке История.