= Допустимые и недопустимые изменения

== Допустимые изменения

Допускаются изменения, не влияющие на логику поведения и работоспособность приложения, а именно:

* Справочник видов карточек:
* изменение специальных настроек карточки Документ;
* изменение специальных настроек карточки Задание;
* изменение специальных настроек карточки Группа заданий;
* добавление и настройка режимов создания видов карточек.
* Конструктор состояний:
* изменение доступности операций редактирования;
* добавление состояний.
* Конструктор ролей:
* добавление новых ролей, их переименование, изменение и удаление;
* настройка матрицы доступа (в том числе – для базовых ролей).
* Конструктор разметок:
* добавление расширенного поля;
* изменение разметки:
** смена места расположения преднастроенных элементов управления и добавление элементов, не влияющих на бизнес-логику карточек,
** удаление элементов управления и изменение Дерева дизайнов (кроме видов Документ УД и Задание УД);
* изменение иконок кнопок.
* Конструктор правил нумерации:
* изменение настроенных записей в настроенных правилах нумерации;
* добавление собственных правил.
* Конструктор справочников: ограничения отсутствуют.
* Справочник ссылок: добавление новых записей в справочник/удаление/изменение существующих записей.
* Справочник категорий: ограничения отсутствуют.
* Справочник меток подписей: добавление новых записей в справочник/удаление/изменение существующих записей.
* Отчеты (Excel): добавление новых отчетов/изменение/удаление существующих отчетов.
* Справочники и настройки библиотеки Делопроизводства 4.5: ограничения отсутствуют.
* Добавление/удаление/изменение собственных представлений и поисковых запросов: ограничения отсутствуют.
* Скрипты Конструктора скриптов: любые изменения кроме корневых видов Документ УД, Задание УД. При обновлении версии модуля скрипты карточки Группа заданий УД будут перезаписаны (при необходимости, предварительно сохраненные скрипты могут быть восстановлены после обновления).
* Изменение структуры общих папок (в том числе для поиска), кроме папок, указанных в списке «Недопустимые изменения».

== Недопустимые изменения

. Удаление групп из Справочника сотрудников:
* «Системная для Workflow»,
* «Администраторы УД»,
* «Администраторы РГ»,
* «Администраторы КС».
. Удаление или модификация бизнес-процессов в папках: `Конструктор согласований/Бизнес-процессы/Шаблоны` и `Служебные/Бизнес-процессы`.
. Удаление или модификация стандартных папок, включая папки: `Договоры/Служебные`, `Служебные/Маршрутизация` и их подпапки.
. Удаление или модификация стандартных представлений и поисковых запросов.