= Прикрепление файлов к карточке договорного документа

К карточке договорного документа может быть прикреплено произвольное количество основных и дополнительных файлов различных форматов. Файлы, прикрепленные как основные, будут участвовать в согласовании и подписании договорного документа.

По умолчанию к карточке Договора и Дополнительного соглашения прикрепляется файл xref:Templates.adoc[шаблона договора].

.Файлы прикрепляются к карточке договорного документа следующим образом:
. Откройте карточку договорного документа и перейдите на вкладку _Файл_.
. Выберите из контекстного меню области _Вложенные файлы_ один из вариантов:
+
* Добавить файл из файловой системы.
* Добавить отсканированный файл.
* Добавить отсканированный и распознанный файл.
+
. Выберите назначение файла:
+
* Основной.
* Дополнительный.
+
Если на предыдущем шаге был выбран вариант _Добавить отсканированный и распознанный файл_, то данный шаг пропускается.
+
. Выберите файл из файловой системы или файл, полученный сканированием.
. Ссылка на карточку файла будет помещена в таблицу _Файлы_.
+
[NOTE]
====
См. особенности асинхронной загрузки файлов в пункте xref:scenarios/files/add-to-card.adoc[Добавление файла в карточку].
====
