= Настройка приёмки группы заданий

При отправке группы заданий исполнителям можно предусмотреть приёмку заданий ответственным исполнителем. Настройка приёмки различается в зависимости от выбранного варианта исполнения карточки.

.Чтобы настроить приёмку, выполните следующие действия:
. xref:tasks/create-groups/performers.adoc[Укажите] Ответственного исполнителя.
. Раскройте область _приёмка и контроль_.
. Установите флаг `*Требуется приёмка*`.
+
Все задания (кроме задания _Ответственного исполнителя_) в состоянии `На приёмке` будут переходить _Ответственному исполнителю_. При *_Последовательном_* варианте исполнения, пока предыдущее задание находится в состоянии `На приёмке`, следующее задание не будет выслано очередному исполнителю. Отправка произойдет только после перехода предыдущего задания в состояние `Завершено`.

.Если в карточке установлен флаг "Требуется приёмка":
* Если одновременно указаны _Контролёр_ и _Ответственный исполнитель_, _Контролёр_ будет проверять выполнение задания только _Ответственного исполнителя_. Задания остальных исполнителей на приёмку после завершения не переходят.
* Если указан только _Контролёр_, а _Ответственный исполнитель_ -- нет, _Контролёру_ на приёмку переходят задания всех исполнителей.
* Если указан только _Ответственный исполнитель_, задания всех исполнителей (кроме своего собственного) переходят ему на приёмку.

В экземплярах заданий, которые по завершении должны перейти в состояние `На приёмке`, также автоматически устанавливается флаг `*Требуется приёмка*`, а в поле _Контролёр_ переносится значение либо из поля _Контролёр_ (если он указан), либо из поля _Ответственный исполнитель_, если не указан _Контролёр_, но указан _Ответственный исполнитель_.
