= Настройка контроля группы заданий

При отправке группы заданий исполнителям можно предусмотреть контроль выполнения заданий ответственным сотрудником. Настройка контроля различается в зависимости от выбранного варианта исполнения карточки.

.Чтобы настроить контроль за выполнением группы заданий:
. На вкладке _Основная_ раскройте область _приёмка и контроль_.
. Установите флаг `*На контроле*`.
+
Станут доступными для заполнения поля _Дата контроля_ и _Контролёр_.
+
. Выполните одно из доступных действий:
+
* Если выбран вариант исполнения *_Параллельно_*, в поле _Дата контроля_ укажите дату, когда должен быть выполнен контроль выполнения задания.
+
Выбрать дату можно при помощи встроенного календаря, который открывается при нажатии на стрелку в правой части поля.
+
* Если выбран вариант исполнения *_Последовательно_*, в поле _Контроль до завершения (ч.)_ укажите количество часов, за которое должен быть выполнен контроль выполнения задания.
+
. В поле _Контролёр_ укажите сотрудника, который будет контролировать качество выполнения задания.
+
Выбрать контролёра можно из _Справочника сотрудников_, который открывается нажатием на кнопку в правой части поля, либо при помощи быстрого поиска по подстроке.
+
Назначенный контролёр будет отображаться во всех запущенных заданиях.
+
Контролёр сможет осуществлять контроль выполнения заданий. Все завершенные задания сразу переходят в состояние `Завершено` (и не переходят на приёмку).

Если в карточке Группы заданий установлен флаг `*На контроле*`, то во всех заданиях группы в поля _Контролёр_ и _Дата контроля_ переносятся значения из соответствующих полей Группы заданий. При варианте исполнения *_Последовательно_* значение поля _Дата контроля_ рассчитывается вычитанием значения поля _Контроль до завершения (ч.)_ из значения поля _Дата завершения_.

Если в карточке одновременно установлены флаги `*Требуется приёмка*` и `*На контроле*`:

* Если одновременно указаны _Контролёр_ и _Ответственный исполнитель_, _Контролёр_ будет проверять выполнение задания только _Ответственного_ исполнителя. Задания остальных исполнителей на приёмку после завершения не переходят.
* Если указан только _Контролёр_, а _Ответственный исполнитель_ -- нет, _Контролёру_ на приёмку переходят задания всех исполнителей.
